### PR TITLE
fix: typo spelling

### PR DESCRIPTION
**Pull request by slowy07**
fix typo spelling from ```keras```

### CODE REVIEW

**Review by fchollet — APPROVED** [review]

**Review by fchollet — APPROVED** [review]
LGTM

**Comment by fchollet** [comment]
> This branch cannot be rebased due to conflicts

This PR needs to be rebased, please take a look.

**Comment by slowy07** [comment]
okay thanks sir @fchollet , i rebase PR

**Comment by fchollet** [comment]
Basically reapply the changes on top of the latest version of the master branch. There is currently a merge conflict.

**Pull request merged**
