### PR TITLE
Allow third party strategies to support LossScaleOptimizer

### PR DESCRIPTION
**Pull request by georgepaw**
Allow strategies to indicate that they support LossScaleOptimizer

### CODE REVIEW

**Comment by qlzh727** [comment]
@reedwm for review.

**Review by reedwm — CHANGES_REQUESTED** [review]
Instead of hardcoding a list of supported strategies and also checking a `supports_loss_scaling` attribute, I think we should just hardcode a list of built-in strategies that LossScaleOptimizer does *not* support, and allow all other strategies (including third party strategies). This is already what the base optimizer does in certain cases:

https://github.com/keras-team/keras/blob/7afc5c520f3bc3e9581cf47be0d1cfd4e840a218/keras/optimizer_v2/optimizer_v2.py#L642-L650

In particular, `CentralStorageStrategy`, `ParameterServerStrategy` and `TPUStrategy` are not supported by LossScaleOptimizer.

Doing this would mean that if a third party strategy similar to ParameterServerStrategy was used, strange hard-to-debug issues may occur, but I don't think it will occur frequently in practice.

@georgepaw, are you willing to make this change? If so, you can just modify this PR. If not, I can make the change.

**Comment by gbaned** [comment]
@georgepaw Any update on this PR? Please. Thanks!

**Comment by qlzh727** [comment]
Closing this PR since this is a bit staled. @georgepaw feel free to open this PR again when the comment from Reed is addressed.

**Pull request closed without merging**
