### PR TITLE
Add unittest for supporting VariablePolicy in saved_model.load

### PR DESCRIPTION
**Pull request by wenscarl**
This PR adds unittest for adding VariablePolicy to saved_model.load when soft placement is disabled. A related PR is https://github.com/tensorflow/tensorflow/pull/54319

### CODE REVIEW

**Comment by qlzh727** [comment]
Assign to Kathy since she is also reviewing the other PR on tf side.

**Comment by k-w-w** [comment]
since this is testing something in TensorFlow, could I ask that you move this test to the TensorFlow codebase (and change the Keras-related part of the code)? The low-level equivalent class of a Keras model is `tf.Module`.

**Comment by k-w-w** [comment]
I would put it here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/load_test.py

**Comment by wenscarl** [comment]
Add the unittest there. Thanks and closing.

**Pull request closed without merging**
