### PR TITLE
master

### PR DESCRIPTION
**Pull request by danFromTelAviv**
add ops to to numpy backend - cos,  sin

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
Can you add tests for cos and sin? It seems we never tested them (which is bad). You can add them here:

https://github.com/keras-team/keras/blob/2ad932ba4ea501af7c3163573fce994ef878d8ef/tests/keras/backend/backend_test.py#L355

Thanks!

**Comment by danFromTelAviv** [comment]
ok - I added them. I also see now I was working on master instead of the branch I opened. oops :/

**Comment by danFromTelAviv** [comment]
hallejaluja. passed travis

**Comment by gabrieldemarmiesse** [comment]
The issue is, there are now 18 files changed displayed in github, and I don't think it's a good idea to merge this PR since commits from master ended up there. Could you open a new PR and follow the instructions I gave here: https://github.com/keras-team/keras/pull/11207#issuecomment-425458379 ? Thank you for your patience.

**Comment by danFromTelAviv** [comment]
ok. sure. I did the whole thing over. In Hebrew we say "third time. ice cream" - it means that typically things work out by the third try. Hopefully this one is good. Thank you for your patience as well.

**Pull request closed without merging**
