### PR TITLE
Add compute_output_shape in TFOpLambda

### PR DESCRIPTION
**Pull request by FancyXun**
Create a new pr from the old pr: https://github.com/keras-team/keras/pull/15381
If this could be merged, I would delete the old one.

### CODE REVIEW

**Comment by FancyXun** [comment]
@fchollet Thanks for your advice in https://github.com/keras-team/keras/pull/15381, I create a new one for that.

**Comment by FancyXun** [comment]
I wonder why this pr merging is blocked?

**Comment by fchollet** [comment]
@fancyXun unfortunately, it appears that a test is failing:

```
keras/layers/core:core_test
```

Specifically

```
TFOpLambdaTest.test_compute_output_shape_v1_session
```

Please fix the failing test and push your changes. We'll re-approve the PR and attempt to merge it. Thank you!

**Comment by gbaned** [comment]
@FancyXun Can you please check @fchollet's comments and keep us posted ? Thanks!

**Comment by gbaned** [comment]
@FancyXun Any update on this PR? Please. Thanks!

**Comment by gbaned** [comment]
@FancyXun Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
@FancyXun Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
@FancyXun Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
@FancyXun Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
@FancyXun Any update on this PR? Please. Thank you!

**Comment by gbaned** [comment]
Hi @FancyXun  I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! Thank you!

**Pull request closed without merging**
