### PR TITLE
Speed up and simplified the convolution in the reference operations.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
### PR Overview

- [ ] This PR requires new unit tests [y/n] (make sure tests are included)
- [ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
Seems like there is this timeout issue again.

**Comment by gabrieldemarmiesse** [comment]
I restarted the job a few times, but the timeout is still there. Maybe it's not so random after all?

**Comment by taehoonlee** [comment]
@gabrieldemarmiesse, I think it is better to leave them as they are. The reference operations should help users to understand underlying primitive operations. Thus, it is good to elaborate the operations even indexing if there is not much runtime difference. The current simplification is not so effective for runtime.

**Comment by gabrieldemarmiesse** [comment]
Ok fair enough!

**Comment by taehoonlee** [comment]
Thank you @gabrieldemarmiesse!

**Pull request closed without merging**
