### PR TITLE
bug fix in scatter update for jax backend

### PR DESCRIPTION
**Pull request by anas-rz**
`ops.scatter_update` throws an exception with the JAX backend. 

To reproduce:
```
import os
os.environ['KERAS_BACKEND'] = 'jax'

from keras import ops

adjacency_matrix = ops.zeros((12))
indices = [[0],[1], [3]]
updates = ops.ones(shape=(3))
adjacency_matrix = ops.scatter_update(adjacency_matrix, indices, updates)
```

This patch can fix this error.

### CODE REVIEW

**Review by fchollet — COMMENTED** [review]
Thanks for the fix! Can you add a unit test, so we avoid breaking it in the future?

**Comment by fchollet** [comment]
> was done on np.array instead of jnp.array. Should we convert_to_tensor in backend scatter_update?

Yes, that's preferable. Outputs should be JAX arrays.

**Comment by anas-rz** [comment]
This should check the returned arrays are JAX, PyTorch, or TensorFlow arrays.

**Review by fchollet — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
