### PR TITLE
Add Input layer to the docs

### PR DESCRIPTION
**Pull request by ozabluda**

### CODE REVIEW

**Comment by fchollet** [comment]
Not sure about putting it in `layers`, it's not a layer, it's an API for instantiating an input tensor.

**Comment by ozabluda** [comment]
Out of existing sections, "layer" is the only one matching. That's where I was looking for it, and I presume other would. input/hidden/output layer is standard terminology (with industry finally mercifully settling on not counting input in the number of layers). Maybe `Input` should be made into a layer eventually? In Caffe `Data/Input` is a layer.

**Comment by fchollet** [comment]
There is a layer associated with it, called `InputLayer`. Using `Input` does create an `InputLayer`.

**Comment by fchollet** [comment]
I should also mention that `InputLayer` is deliberately left undocumented, as it isn't meant to be part of the public API.

**Pull request merged**
