### PR TITLE
Update nn.py

### PR DESCRIPTION
**Pull request by gautam1858**
- Avoiding unnecessary conditional casting by directly operating on `y`.
- Performing all-reduces for sum, squared sum, and count using `replica_ctx`.
- Simplifying the variance calculation.

### CODE REVIEW

**Review by haifeng-jin — CHANGES_REQUESTED** [review]
Thanks for the PR! It seems the PR breaks the code style and failed on the TF tests. Would you mind fixing them?

**Comment by mihaimaruseac** [comment]
Please don't use "add file"/"update file"/"fix file"/etc. commit messages. These are hard to reason about when looking at the history of the file/repository. Instead, please write explanatory git commit messages.

The commit message is also the title of the PR if the PR has only one commit. It is thus twice important to have commit messages that are relevant, as PRs would be easier to understand and easier to analyze in search results.

For how to write good quality git commit messages, please consult https://cbea.ms/git-commit/

**Comment by mihaimaruseac** [comment]
The author has sent 3 spam PRs on TF repo and one PR that got merged.

**Comment by gautam1858** [comment]
> Thanks for the PR! It seems the PR breaks the code style and failed on the TF tests. Would you mind fixing them?

Sure I will try to fix them

**Pull request closed without merging**
