### PR TITLE
DCGAN on MNIST example

### PR DESCRIPTION
**Pull request by roatienza**
Shows how to build and tune a DCGAN on MNIST dataset.

Sample output after 10k train steps:

mnist_dcgan_10000

### CODE REVIEW

**Comment by fchollet** [comment]
We already have a MNIST ACGAN example. Also a CIFAR10 DCGAN example here: https://github.com/fchollet/deep-learning-with-python-notebooks/blob/master/8.5-introduction-to-gans.ipynb

**Comment by roatienza** [comment]
@fchollet I think it would be beneficial to readers to see different GANs implemented in Keras (DCGAN, ACGAN, CGAN, CycleGAN, DiscoGAN, Progressive GAN, WGAN, VAEGAN, etc). We have only one of these many useful GANs in the examples so far.

**Comment by ozabluda** [comment]
I agree on the need for various cool GANs, but it seems DCGAN is just ACGAN with AC turned off, so DCGAN can trivially be created from ACGAN and so is completely redundant [1]. ACGAN inherited DCGAN pretty much wholesale anyhow, which inherited LAPGAN pretty much wholesale. This DCGAN example code structure is also very different from ACGAN example (which is far from perfect), but it makes unnecessarily harder to understand both and to potentially have the same code structure for many/all GAN examples in the future.

[1] Maybe ACGAN example can have an option to turn AC off (=DCGAN), useful for demonstration just how much DCGAN sucks in comparison i.e. how much AC helps (but it should be weighted against increasing example complexity). 

@roatienza, if you haven't already, check out ACGAN pictures:
https://github.com/keras-team/keras/pull/8616#issuecomment-347673312

and ACGAN videos:
https://github.com/keras-team/keras/pull/8616#issuecomment-357831662

**Comment by fchollet** [comment]
It would be nice to have a WGAN example on CIFAR10, if you are up for it.

**Comment by fchollet** [comment]
Closing, feel free to submit a WGAN example if you are interested!

**Pull request closed without merging**
