### PR TITLE
fix a bug

### PR DESCRIPTION
**Pull request by XikunZhang**
If we change the `trainable` property of `layer`, the weights will be updated. So the comments on the line I have moved are wrong.

### CODE REVIEW

**Comment by fchollet** [comment]
No, because we do not recompile `frozen_model`.

**Comment by XikunZhang** [comment]
I get your point. But after doing a simple experiment by printing the weights of the 2 models before and after training, I find that both weights change. Also, I mean, the 2 models share the same layer instance, why can the weights be different after training?

**Comment by fchollet** [comment]
They're the same. They're just not changing when calling `frozen_model.fit()`. They're changing when calling `model.fit()`. Hence they end up having changed.

**Comment by XikunZhang** [comment]
Thank you for your explanation!

**Pull request closed without merging**
