### PR TITLE
Fix `CategoryEncoding` generates output with 1 additional dimension in all backends except NumPy (#19724)

### PR DESCRIPTION
**Pull request by Grvzard**
Make the behavior consistent across all backends.

### CODE REVIEW

**Comment by hertschuh** [comment]
@Grvzard ,

Thank you for catching and fixing this bug. This all looks correct. 

The fact that there was a discrepancy with one backend shows that we're missing a unit test in `nn_test.py`. Can you please add an input covering this case of a last dimension of 1 here: https://github.com/keras-team/keras/blob/master/keras/src/ops/nn_test.py#L1652

Thanks!

**Comment by Grvzard** [comment]
The original one_hot in numpy will fail on this test

**Review by hertschuh — APPROVED** [review]
Great, thank you!

**Comment by Grvzard** [comment]
Fixed #19724

**Pull request merged**
