### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by diogofferreira**
### PR Overview

- [ ] This PR requires new unit tests [y/n] (make sure tests are included)
- [x] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by fabiomaia** [comment]
It's not a typo, it's a half-open interval.

https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.uniform.html

**Comment by fchollet** [comment]
Wouldn't half open be `[0, 1[`?

**Comment by fabiomaia** [comment]
I've seen both notations, take your pick.

`[-1.0, +1.0]` is just wrong though, see the `numpy.random.uniform` documentation which uses the curvy parenthesis notation.

> numpy.random.uniform(low=0.0, high=1.0, size=None)
> Draw samples from a uniform distribution.
> 
> Samples are uniformly distributed over the **half-open interval [low, high)** (includes low, but excludes high). In other words, any value within the given interval is equally likely to be drawn by uniform.

https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.uniform.html

**Comment by diogofferreira** [comment]
> I've seen both notations, take your pick.
> 
> `[-1.0, +1.0]` is just wrong though, the interval does not include +1.0. See the `numpy.random.uniform` documentation (which uses the curvy parenthesis notation by the way).
> 
> > numpy.random.uniform(low=0.0, high=1.0, size=None)
> > Draw samples from a uniform distribution.
> > Samples are uniformly distributed over the **half-open interval [low, high)** (includes low, but excludes high). In other words, any value within the given interval is equally likely to be drawn by uniform.
> 
> https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.uniform.html

Yup, @fabiomaia is right, the interval does not include +1.0, so my PR does not make sense.
Sorry guys.

**Pull request merged**
