### PR TITLE
Fixed Conv1D deprecated arguments

### PR DESCRIPTION
**Pull request by jjangsangy**
# Fixed
* Updated deprecated `data_format` in `Conv1D` from `{NCHW, NHWC}`, to `{NCW, NWC}` to fit the new [tensorflow api](https://www.tensorflow.org/api_docs/python/tf/nn/conv1d)

### CODE REVIEW

**Comment by fchollet** [comment]
We need to stay compatible with the old behavior.

**Comment by fchollet** [comment]
(Basically, we shouldn't break people who are using a slightly older TF version)

**Comment by jjangsangy** [comment]
So I'm looking deeper into the code and I'm wondering if this function is ever called in when calling `K.conv1d`?

https://github.com/keras-team/keras/blob/24e7ac0756aeba06ce1cf7f7e72219a11b14b101/keras/backend/tensorflow_backend.py#L3398-L3439

So it seems that `K.conv1d` is using the new API, however, I am still getting a warning from tensorflow which is warning that `data_format` is using the old api.

```
WARNING:tensorflow:From /usr/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py:497: calling conv1d (from tensorflow.python.ops.nn_ops) with data_format=NHWC is deprecated and will be removed in a future version.
Instructions for updating:
`NHWC` for data_format is deprecated, use `NWC` instead
```

I am currently running `Keras 2.1.4` and `Tensorflow 1.7.0`

**Comment by taehoonlee** [comment]
Thank you for the PR @jjangsangy. The `_preprocess_conv1d_input` is used for calling `tf.nn.separable_conv2d` in `separable_conv1d. It is correct not to modify. When does the warning occur exactly?

**Comment by jjangsangy** [comment]
Oh that is interesting. I'm training a mobilenet model which uses `tf.nn.separable_conv2d`

**Comment by taehoonlee** [comment]
@jjangsangy, The `MobileNet` and the `MobileNetV2` don't call `K.conv1d`. It is hard to know why you got such a warning.

**Comment by fchollet** [comment]
I've actually had to fix this in a recent commit (while adding support for the `data_format` argument in `Conv1D`. Regardless, thanks for the PR!

**Pull request closed without merging**
