### PR TITLE
Add ResNet, ResNetV2, and ResNeXt variants

### PR DESCRIPTION
**Pull request by taehoonlee**
This PR adds declarations of ResNet, ResNetV2, and ResNeXt variants. In order to add new models into `keras-applications`,  we should first add those declarations into `keras`. Please refer to the cores (keras-team/keras-applications#26).

### CODE REVIEW

**Comment by fchollet** [comment]
> In order to add new models into keras-applications, we should first add those declarations into keras.

That seems like a problem. Could you detail what the issue is?

Will try to review both PRs tomorrow.

**Comment by taehoonlee** [comment]
@fchollet, all the models have been accepted `kwargs` since the recent backend interfacing changes. The `keras_modules_injection` in `keras` can put backend into `kwargs` at runtime. Can we make the same function in `keras-applications` not `keras`?

For example, in `keras-applications/tests/application_tests.py`, not `keras-applications` but `keras` modules have been imported (e.g., `from keras.applications import densenet`). If we have `keras_modules_injection` in `keras-applications`, we can decouple the application importing and calling from `keras` (e.g., `from keras_applications import densenet; model = densenet.DenseNet121()`).

**Comment by fchollet** [comment]
> The keras_modules_injection in keras can put backend into kwargs at runtime. Can we make the same function in keras-applications not keras?

Yes, that's a good idea, we should definitely consider this. We just need to make sure it would also work for tf.keras: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/__init__.py

**Comment by taehoonlee** [comment]
@fchollet, I would like you to confirm that I understood it correctly. Please refer to the `tests/applications_test.py` in keras-team/keras-applications#26. I think that the way to add new models are:
1. Add core files into `keras-applications` and test them with locally defined `keras_modules_injection` on `tests/applications_test.py`.
2. Add wrapper files into `keras` like this PR.

**Comment by fchollet** [comment]
@taehoonlee ok, I just saw the test you added in the other PR. Initially I thought you wanted to abstract the module injection logic directly into `keras_applications`, so that `keras` would only call that abstraction rather than wrapping individual models on its own.

Your proposed solution makes sense and looks good to me. The workflow you describe for adding new applications looks good to me.

I will review your other PR. Thanks!

**Comment by taehoonlee** [comment]
@fchollet, Since keras-team/keras-applications#26 is merged, I think this PR also needs to be merged. I would like you to review this PR at your convenience.

**Pull request merged**
