### PR TITLE
Speed up `DataAdapter` tests by testing only the current backend.

### PR DESCRIPTION
**Pull request by hertschuh**
There is no use case for using an iterator for a different backend than the current backend.

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
LGTM, thank you!

**Comment by fchollet** [comment]
Tests seem to be consistently timing out with JAX, which seems related to the PyDataset fixes. What could we do?

**Comment by hertschuh** [comment]
> Tests seem to be consistently timing out with JAX, which seems related to the PyDataset fixes. What could we do?

I'm looking into. I don't think it's normal that spawning a process takes something like 8 seconds.

**Comment by hertschuh** [comment]
> > Tests seem to be consistently timing out with JAX, which seems related to the PyDataset fixes. What could we do?
> 
> I'm looking into. I don't think it's normal that spawning a process takes something like 8 seconds.

By the way, the slow PyAdapter testing is not JAX specific, it's the same with TF, it's just that JAX was already close to the limit before.

**Comment by hertschuh** [comment]
> > > Tests seem to be consistently timing out with JAX, which seems related to the PyDataset fixes. What could we do?
> > 
> > 
> > I'm looking into. I don't think it's normal that spawning a process takes something like 8 seconds.
> 
> By the way, the slow PyAdapter testing is not JAX specific, it's the same with TF, it's just that JAX was already close to the limit before.

Tests are passing now (I further cut down the number of tests we do with multiprocessing).

**Pull request merged**
