### PR TITLE
Add verbosity to DirectoryIterator and method

### PR DESCRIPTION
**Pull request by pavol6999**
Add verbosity to DirectoryIterator and flow_from_directory method to optionally disable the `Found X images belonging to Y classes.` print to console.

### CODE REVIEW

**Comment by Haaris-Rahman** [comment]
I believe it is better to keep verbose as a bool variable.
Use  `if self.verbose` instead of `if self.verbose>0`

**Comment by pavol6999** [comment]
> I believe it is better to keep verbose as a bool variable. Use `if self.verbose` instead of `if self.verbose>0`

For as long as I think your answer is the correct approach, I have followed the implementation of verbosity in Callback classes (https://github.com/keras-team/keras/blob/master/keras/callbacks.py#L1434)

If this is a problem I can rewrite it

**Comment by Haaris-Rahman** [comment]
> > I believe it is better to keep verbose as a bool variable. Use `if self.verbose` instead of `if self.verbose>0`
> 
> For as long as I think your answer is the correct approach, I have followed the implementation of verbosity in Callback classes (https://github.com/keras-team/keras/blob/master/keras/callbacks.py#L1434)
> 
> If this is a problem I can rewrite it

Oh my bad. Didn't notice that.

**Comment by fchollet** [comment]
Thanks for the PR! We're no longer adding features to (or maintaining) numpy-based data loading utilities. You'll notice they're no longer documented on [keras.io](https://keras.io/api/).

**Pull request closed without merging**
