### PR TITLE
Improved TimeseriesGenerator() -- backward compatible version

### PR DESCRIPTION
**Pull request by TanguyUrvoy**
Improved from PR #9918.

**changes relative to PR #9918**
- kept `length` (with a depreciation warning)
- added `hlength` as a replacement
- same parameters order

**Other changes relative to keras version**
- consolidated the init method by adding a host of assertions
- now it also works with text
- added prediction gap parameter
- shuffle is now a real shuffle (i.e. without replacement) 
- added target_seq option for seq2seq models
- added dtype parameter to force output dtype
- added stateful option to help parameters tuning in stateful mode (experimental)

### CODE REVIEW

**Comment by TanguyUrvoy** [comment]
Well, my proposal breaks the new `test_TimeSeriesGenerator_doesnt_miss_any_sample()` test:

`x = np.array([[i] for i in range(10)])`
`        for length in range(3, 10):`
`            g = TimeseriesGenerator(x, x, length=length, batch_size=1)`
`            expected = max(0, len(x) - length)`
`            actual = len(g)`
`           assert expected == actual`

But there seems to be a confusion regarding the prediction gap. Either:
1- we consider the gap to be a part of the target's definition: `g = TimeseriesGenerator(x, x[1:], length=length)`. In which case the expected len is `len(x)-length`
2- we deal with prediction gap inside the generator `g = TimeseriesGenerator(x, x, length=length, gap=1)` in which case the expected len is `len(x[)-length-gap`

The other test,  `test_TimeseriesGenerator()` expects a prediction at t+1.

Maybe he best option is the first: it's simpler.

Tanguy

**Comment by TanguyUrvoy** [comment]
Improved from PR #9918.

**changes relative to PR #9918**

- **API change**: default prediction `gap` is now 0, *making `targets[t]` the target predicted from `data[t]` (instead of `targets[t+1]`)*
- kept `length`
- added `hlength` as a possible replacement for length
- kept same parameters order as in keras 

**Other changes relative to keras version 2.1.5**
- consolidated the init method by adding a host `ValueError` tests.
- now it also works with text
- added prediction `gap` parameter
- `shuffle` is now a real shuffle (i.e. without replacement)
- added `target_seq` option for seq2seq models
- added `dtype` parameter to control output `dtype`
- added `stateful` option to help parameters tuning in stateful mode (experimental)

**Tests**
- updated tests in `test/keras/preprocessing/sequence_test.py`
- added a host of new tests (including text sequences as input)

**Comment by fchollet** [comment]
@srjoglekar246 could you please review?

**Comment by fchollet** [comment]
I took a look, I have some concerns about this PR. Will try to review in detail when I get some time.

**Comment by fchollet** [comment]
Sorry I didn't have time to review this earlier. If you are still interested in this PR, please open it on https://github.com/keras-team/keras-preprocessing

**Pull request closed without merging**
