### PR TITLE
Fix models for sklearn ensemble

### PR DESCRIPTION
**Pull request by charlesmsiegel**
When using the sklearn VotingClassifier ensemble technique, it looks for predict_proba and predict_classes methods.  These methods exist on Sequential but not on Model.  Moving these methods to Model fixing this issue and maintains functionality for Sequential, as a subclass of Model.

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR. You should add such methods on the sklearn wrapper class, not on `Model`. It is not possible to define these methods for `Model` in the general case, since the model may have multiple outputs.

tbh they should not have been implemented on `Sequential` either, to start with. But they stick around for historical reasons.

**Comment by fchollet** [comment]
Checking back: do you still plan on working on this feature? Should I close the PR, or leave it open for future updates?

**Comment by charlesmsiegel** [comment]
I've been busy, but I intend to submit a fix sometime in the coming week.

**Comment by fchollet** [comment]
Cool, please open a new PR when the latest changes are ready (since there will be little overlap with the current PR), it will be easier to manage.

**Pull request closed without merging**
