### PR TITLE
Migrate complete `fit` to `fit_generator`

### PR DESCRIPTION
**Pull request by ghostplant**
Large Replicated codes are spitted for same training with different input generations.
This refactor optimization will be used for merging more input generationors.

Signed-off-by: CUI Wei <ghostplant@qq.com>

### CODE REVIEW

**Comment by ghostplant** [comment]
There are 3 copy of training existing in source code.
During the update, I noticed the following bugs:
1) 1 copy of training procedure forget to reset_metrics;
2) 1 copy of training procedure forget to transfer class_weight when doing validation;

**Comment by ghostplant** [comment]
Hi, this is the final version of update which is the best, so 2 copies were away and only 1 copy is needed to main in the future.

Please review the code and decide whether to delete whole `function _fit_loop(..)` and all codes at `Line 1710 - Line 1785` as well.

**Comment by ghostplant** [comment]
After this optimization, around 260+ line training copies can be deleted in summary.

**Comment by ghostplant** [comment]
The key idea is that `fit` support two different kinds in inputs:
1) Standard array input (both dense and sparse is possible);
2) Data tensors input;

So 2 different generators is needed by fit_generator to support each of time.

Besides, there is a 2-line enhancement on fit_generator to make it support data tensors inputs, which makes users able to use fit_generator to train model with data tensors, and it is also a must to for this training merge.

Since the upgrade can cover all types of original fit cases and wrap them to fit_generator, so legacy option is not needed.

**Comment by ghostplant** [comment]
@fchollet @Dref360 Any comments or concerns?

**Comment by fchollet** [comment]
Thanks for the PR. However, we will keep the array-based and generator-based implementations separate for the time being. They may merge eventually, but that is unlikely, and if it happens it won't be until some extensive refactoring of the Keras engine that are in the plans.

**Pull request closed without merging**
