### PR TITLE
replace legacy `fit` with `fit_generator`

### PR DESCRIPTION
**Pull request by ghostplant**
Currently, the replacement is able to apply on
all applications except whose fed with framework-native
tensor data, which will be put as a future work.

Signed-off-by: CUI Wei <ghostplant@qq.com>

### CODE REVIEW

**Comment by Dref360** [comment]
Wouldn't it be easier to modify the NumpyArrayIterator to fit our need?

**Comment by ghostplant** [comment]
NumpyArrayIterator is coupling too much image_transform and saving_images, and it forces to flow image-like data only (e.g. verifying 4D input data).
In addition, if reusing this class, we need to add checks to bypass image transform and image saving. Besides, `sample_weights` needs to be added into it. So it will also generate much changes.
So I think the name of `NumpyArrayIterator` is not suitable for its work since it does too much to support image data only.
The function `_array_generator` can be put inside the `fit` function to integrate the changes together. However, this function can be also used by `evaluate_generator` and `predict_generator`. So it is more suitable to be put into a shared place.

Maybe `_array_generator` can be put into `preprocessing` directory as a new function, will that be OK?

**Comment by ghostplant** [comment]
Well, it seems quite a long time to refine the method-differences checking in order to pass all test cases.

**Comment by fchollet** [comment]
??

**Comment by ghostplant** [comment]
@fchollet Hi, it seems currently there is a large gap to merge all same training procedure with different input sources, it is needed to do some code optimization step by step in advance: https://github.com/keras-team/keras/pull/9692

**Comment by fchollet** [comment]
@ghostplant hard disagree. It is much simpler to keep the code for these significantly different methods completely separate. See the code organization of the tf.keras engine for a clear example. We will replicate this structure here at some future time.

Our goal is to have code that is maintainable and readable, rather than to have less code in terms of line count. It is rarely the case that making a same piece of code do two things instead of one result in greater maintainability or readability. Generally it's the opposite.

**Comment by fchollet** [comment]
FYI this is what I'm referring to (see `training_*` files): https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/keras/_impl/keras/engine

**Comment by ghostplant** [comment]
@fchollet Yes, the only problem is that is easy to make some codes missing on some copies. For examples, 1 copy of current keras training version misses `steps=validation_steps` which is hard to notice.

**Comment by ghostplant** [comment]
Besides, since `fit` support some special cases that `fit_generator` does, it is not likely that users can easily migrant their `fit` implementation into `fit_generator` when `fit` is declared as replicated. In this case, merging training procedure will be necessary to meet every needs.

**Pull request closed without merging**
