### PR TITLE
Adds tests and fixes issues with CompileLoss true/pred/loss ordering

### PR DESCRIPTION
**Pull request by gustavoeb**
This PR addresses the issue described here: https://github.com/keras-team/keras/issues/20346

- Firstly improved the existing `test_list_loss_dict_data`; the previously chosen values of `a` and `b` are such that no matter the order of the losses (mae, mse) the total loss value is always the same, hiding potential issues.
- Added a couple more tests to mimic what happens with functional models with multiple outputs, fitted with data coming from a dictionary.
- Keeps dicts in their existing order, or output_name order, by casting them to OrderDict to circumvent optree’s sorting behaviour

### CODE REVIEW

**Comment by gustavoeb** [comment]
Thanks for the comment. Fixing the issues that came up in the tests was simple enough... I gave a go at the rebase, but the change made to multi-output models makes it a lot harder to grasp and fix.

My main issue is that the current test coverage is not tracking this bug. For tests I checked where the structure of y_true and y_pred is different things are usually in alphabetical order; and for the only test where that is not the case `test_list_loss_dict_data` the unfortunate choice of values is not catching the out-of-order issue. For clarity:
```
>>> a = losses.mean_absolute_error(y_true["a"], y_pred["a"])
>>> b = losses.mean_squared_error(y_true["b"], y_pred["b"])
>>> ops.mean(a) + ops.mean(b)
<tf.Tensor: shape=(), dtype=float64, numpy=1.0766666666666667>
>>> a = losses.mean_squared_error(y_true["a"], y_pred["a"])
>>> b = losses.mean_absolute_error(y_true["b"], y_pred["b"])
>>> ops.mean(a) + ops.mean(b)
<tf.Tensor: shape=(), dtype=float64, numpy=1.0766666666666667>
```

If you'd like I can keep only the test changes. Otherwise, feel free to close.

**Comment by fchollet** [comment]
> If you'd like I can keep only the test changes. Otherwise, feel free to close.

Any increase in test coverage is valuable! Please do.

**Comment by sampathweb** [comment]
@gustavoeb - Looks like tests are failing. Can you please address it?

**Comment by sampathweb** [comment]
@gustavoeb -
Can you sync to master and create an GitHub issue to reference the problem. We can then debug from there on the appropriate fix by adding a test first?

**Pull request closed without merging**
