### PR TITLE
Add mkl installation for all the envs on Travis

### PR DESCRIPTION
**Pull request by taehoonlee**
### Summary

Recently, the total build time has increased by about 20 minutes, especially after #11570 (see [the recent build times](https://travis-ci.org/keras-team/keras/builds)). I assumed that theano compiled with non-mkl BLAS was cached by the first env (`INTEGRATION_TESTS`) and the next envs (`KERAS_BACKEND=theano`) just uses the cache without recompiled with mkl. The theano tests were twice as slow as before #11570.

### PR Overview

- [ ] This PR requires new unit tests [y/n] (make sure tests are included)
- [ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [ ] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
It is strange. This part of the docs says that the cache should be different for each job in our case: https://docs.travis-ci.com/user/caching#caches-and-build-matrices

**Comment by gabrieldemarmiesse** [comment]
I believe it's possible to check if the jobs are using the wrong cache by checking the url used in the log for upload and download. Also https://travis-ci.org/keras-team/keras/builds/456210290?utm_source=github_status&utm_medium=notification have normal running times.

**Comment by taehoonlee** [comment]
Thank you for the comment, @gabrieldemarmiesse. It is correct that the caches have been made for the individual envs. Then, is there a possibility that Travis can not recognize the double quotes on the environments' names when loading caches?

**Comment by gabrieldemarmiesse** [comment]
I cleared the caches on travis yesterday. It seems that everytbing came back to normal on master. Let's hope it stays that way.

**Comment by taehoonlee** [comment]
@gabrieldemarmiesse, You are right. Thank you for clearing caches. Now the two Theano tests look good.

**Pull request closed without merging**
