### PR TITLE
Fix the aggregation in the codebase

### LINKED ISSUE #20695: Variable and Optimizer aggregation='mean' default is incorrect
The default policy of using `aggregation='mean'` is incorrect. This should be set to `none`. Backends do the grad reductions and var applications in distributed contexts and don't need this mean. The usage of  `aggregation='mean'` breaks optimizer moment estimates. Also compare with `keras==2.15.0` where default policy was equivalent to `aggregation='none'`

### LINKED ISSUE #20698: The default setting for aggregation='mean' in Variable and Optimizer is incorrect.
The default policy of using aggregation='mean' is incorrect and should be set to none. In distributed contexts, backends handle gradient reductions and variable updates, making the mean aggregation unnecessary. Using aggregation='mean' disrupts optimizer moment estimates. For reference, in keras==2.15.0, the default policy was effectively equivalent to aggregation='none

### LINKED ISSUE #20699: The default setting for aggregation='mean' for variables and optimizers is incorrect.
The default policy with aggregation='mean' is incorrect and should be set to none. In a distributed context, the backend handles gradient reduction and variable updates, eliminating the need for intermediate aggregations. Using aggregation='mean' breaks moment estimation in the optimizer. Ref: In keras==2.15.0, the default policy was effectively equivalent to aggregation='none

### LINKED ISSUE #20700: ValueError: creating distributed tf.Variable with aggregation=MEAN and a non-floating dtype is not supported, please use a different aggregation or dtype
It happens while using [keras-models](https://keras.io/api/applications/) in kaggle tpu.

### PR DESCRIPTION
**Pull request by james77777778**
Fix #20695 
Fix #20698 
Fix #20699 
Fix #20700 

In this PR, the aggregation behavior is now consistent with `tf_keras`.
(I'm not sure how to test this using `tf.distribute`)

### CODE REVIEW

**Comment by jeffcarp** [comment]
Thanks for the quick fix Hongyu! Just so I understand was there a recent change in default behavior that caused the linked issues? Additionally should we warn existing users that their aggregation numerics will change?

**Review by fchollet — APPROVED** [review]
Thanks for the fix. Best I can tell this is the correct default.

**Comment by james77777778** [comment]
> Thanks for the quick fix Hongyu! Just so I understand was there a recent change in default behavior that caused the linked issues?

The root cause appears to be this commit:
https://github.com/keras-team/keras/commit/28d39c0cc766767f4db54edc8b8ce68d3a05d4b4

In that commit, I tried to correctly propagate the aggregation property, but it seems to have broken distributed training.
After digging into `tf_keras`, I found that the previous default value for `aggregation` was likely incorrect.. -> This PR corrects that.

> Additionally should we warn existing users that their aggregation numerics will change?

I'm not an expert on `tf.distribute` but I don’t think a warning is necessary because we are fixing the issue, not altering the behavior. WDYT?

**Comment by rivershah** [comment]
@james77777778 You are indeed propagating the correct aggregation now and metrics are correct. I don't think a warning is necessary.

However that aggregation property correction change was breaking optimizer and layer weights (where each replica needs to remain independent till the final merge call) which is also being done correctly.

Does `keras` CI allow mirrored variable testing please using multi GPU machines? A few of the bugs that are popping up are due to the code working perfectly well for single accelerator contexts but failing on multiple accelerators (mirrored gpus or tpus). Thanks and happy new year.

**Comment by james77777778** [comment]
> @james77777778 We are now propagating the correct aggregation, and metrics look accurate. A warning doesn’t seem necessary.
> 
> That said, the earlier aggregation correction was breaking optimizer and layer weights, as each replica needs to remain independent until the final merge call. This is now being handled correctly as well.

Nice!

> Does keras CI support mirrored variable testing on multi-GPU setups? Many of these bugs seem to arise because the code works fine in single-accelerator contexts but fails on multiple accelerators (mirrored GPUs or TPUs). Thanks, and happy New Year!

The current CI seems to lack this kind of tests. @fchollet @jeffcarp does adding tests for `tf.distribute` sound good?
I can help by migrating some tests from `tf_keras` to `keras`.

**Comment by alchemiccoruja** [comment]
Great fix. Appreciate it.

**Comment by jeffcarp** [comment]
> does adding tests for tf.distribute sound good?

Adding coverage sounds great!

> Does keras CI support mirrored variable testing on multi-GPU setups?

The tests mock multiple devices on CPU, which should be enough to test the logic of tf.distribute strategies.

https://github.com/keras-team/keras/blob/97c1c00af87aaae69dd56aa2480ff304d40cf516/keras/src/backend/tensorflow/distribute_test.py#L26-L32

**Comment by rivershah** [comment]
@jeffcarp That's a great find and I have added more unit testing using this in my project. 
Do you have any further direction / snippet on I can use something like to this to also mock `TPUStrategy`? Have tried a number of avenues and hit many logical device + cluster resolution errors.

**Pull request merged**
