### PR TITLE
Update batch_normalization.py

### PR DESCRIPTION
**Pull request by shashaka**
I did several changes for batch_normalization.
Plz, feel free to comment your thought about my changes.

- Add initial values for params on build method.

```
        self.gamma = None
        self.beta = None
        self.moving_mean = None
        self.moving_variance = None
        self._reduction_axes = None
```

- Remove un-used parameter
```
        self.input_spec = InputSpec(
            ndim=len(input_shape), axes={self.axis: input_shape[self.axis]}
        )
```

- Take duplicate code out of if condition block
```
        moving_mean = ops.cast(self.moving_mean, inputs.dtype)
        moving_variance = ops.cast(self.moving_variance, inputs.dtype)
```

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
LGTM, thank you!

**Comment by fchollet** [comment]
> Furthermore, I'd love to contribute to more impactful project also. so, if you let me know, I think I could try that.

That's great! Would you be interested in one of:

- Helping bring new pretrained models in Keras (e.g. StableDiffusion 3 or Llama 3)
- Helping create a Keras backend for [MLX](https://github.com/ml-explore/mlx)?

**Comment by shashaka** [comment]
@fchollet 
Hi, I found that there are keras-cv and keras-nlp, and there are stable diffusion, and llama. So, you asked me to add pretrained model to there as matched with its model type, not only keras repo?

**Comment by fchollet** [comment]
> So, you asked me to add pretrained model to there as matched with its model type, not only keras repo?

If that's something you're interested in, we're looking for contributors in that area and we may have a project for you.

**Comment by shashaka** [comment]
@fchollet 
Actually, I am really interested in implementing algorithm from research paper. However, as of now, I am not familliar with that, I have studied with your code like convnext and research paper you refered. Maybe it takes time to do that for me. so it is kind of challenging for me to lead that project, however,if you set up that kind of project, I think I could support that project by all my efforts.

**Pull request merged**
