### PR TITLE
Add EfficientNet variants

### PR DESCRIPTION
**Pull request by taehoonlee**
### Summary

This PR adds EfficientNet variants. EfficientNet was published in ICML 2019 and is the current SOTA. @Callidior helped this PR.

### Related Issues

keras-team/keras-applications#113

### PR Overview

- [y] This PR requires new unit tests [y/n] (make sure tests are included)
- [y] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [y] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by fchollet** [comment]
I think having EfficientNet is valuable, but `EfficientNetB0 ... EfficientNetB07` is a very high number of near-indistinguishable options. Users will not be able to make a meaningful choice here. We should probably only have `EfficientNetSmall` and `EfficientNetLarge`.

**Comment by taehoonlee** [comment]
@fchollet, I agree. Unlike MobileNet having alpha, EfficientNet has three control parameters: width, depth, resolution. As you said, the mapping between the three parameters and the B0~B7 is not intuitively understandable. In my guess, the eight variants are for the performance curve with respect to the proposed scaling rather than practical uses.

@fchollet @Callidior How about mapping EfficientNetB0 and EfficientNetB4 into Small and Large? The authors showed EfficientNetB4 is competitive to NASNetLarge which is the best in keras-applications. I mean updating this PR only without modifying the eight variants in keras-applications.

**Comment by Callidior** [comment]
@taehoonlee @fchollet I agree that EfficientNetB0 is a good choice for the small variant, given that it is quite lightweight and achieves performance comparable to ResNet-50. With regard to the large variant, I would also take EfficientNetB5 into consideration, since there still is a notable performance gap (0.7%) on ImageNet between B4 and B5. It has quite some more parameters, but if users expect something in the dimension of NasNetLarge, judging by the Large suffix, they might be surprised that B4 has just as many parameters as a ResNet-50.

**Comment by taehoonlee** [comment]
@Callidior, Yes the B5 is also a good choice. And I wanna propose another option, maintaining the eight variants with only one parameter like MobileNet.

I read the paper and found some weird points. The authors said that the B0~B7 are the results of the proposed scaling, where there is only one control parameter phi with fixed alpha, beta, and gamma. But the numbers in the paper (alpha=1.2, beta=1.1, gamma=1.15) can not produce [the arguments](https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/efficientnet_builder.py#L38-L45) in the official implementation. Thus, I recalculate beta and gamma with the following codes:
```python
from math import exp, log, floor

alpha = 1.2
beta = alpha * exp((log(2.0) / log(3.1) - 1) * log(alpha))
gamma = alpha * exp((log(2.68) / log(3.1) - 1) * log(alpha))
print("New beta: {}".format(beta))
print("New gamma: {}".format(gamma))
print("| phi  |width|depth| res |")
print("|------|-----|-----|-----|")
for phi in [1.0, 1.43, 1.95, 2.85, 4.34, 5.48, 6.4, 7.21]:
    round_fn = round if phi < 2 else floor
    print("| {:4.2f} | {} | {} | {} |".format(
        phi,
        round_fn(pow(beta, phi - 1) * 10) / 10,
        round_fn(pow(alpha, phi - 1) * 10) / 10,
        round_fn(pow(gamma, phi - 1) * 224)))
```

In results, I found the new beta 1.1182 (the official: 1.1) and the new gamma 1.1722 (the official: 1.15). Based on the alpha and the new ones slightly different from the official beta and gamma, I successfully reproduced [the official arguments]((https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/efficientnet_builder.py#L38-L45)).

| phi  |width|depth| res |
|------|-----|-----|-----|
| 1.00 | 1.0 | 1.0 | 224 |
| 1.43 | 1.0 | 1.1 | 240 |
| 1.95 | 1.1 | 1.2 | 260 |
| 2.85 | 1.2 | 1.4 | 300 |
| 4.34 | 1.4 | 1.8 | 380 |
| 5.48 | 1.6 | 2.2 | 456 |
| 6.40 | 1.8 | 2.6 | 528 |
| 7.21 | 2.0 | 3.1 | 600 |

@fchollet, @Callidior, How about replacing the near-indistinguishable options with only one parameter phi, rather than mapping small and large ones? My concern is that these numbers are not official. But, I still think that adding all the variants is valuable, and introducing only one parameter will be user-friendly.

**Comment by Callidior** [comment]
@taehoonlee Having a single hyper-parameter is a very nice option, but I am afraid that the "valid" values for `phi` are a bit hard to guess, given that it is continuous. We would have to make it very clear, for which 8 values we have pre-trained weights.

**Comment by Callidior** [comment]
@taehoonlee Many numbers in the paper are outdated, so I wouldn't be surprised about that. For anyone who has read the paper, the meaning of `phi` should be totally clear, so that it in fact is a nice way of parameterizing our EfficientNet implementation. But without any *official* numbers for alpha, beta, and gamma, I would be rather hesitant.
Moreover, I think that most people who just skim through the paper will rather remember the fixed mappings of B0-B7. If we think about future research leveraging EfficientNet, it is very likely that such papers will refer to the B0-B7 mappings instead of reporting any `phi`. Thus, the vast majority of users will look for one of these 8 variants and never choose any other `phi` than the 8 fixed ones.

**Comment by taehoonlee** [comment]
@Callidior, I agree. Then, does it look reasonable now? The EfficientNetSmall and EfficientNetLarge are the B0 and B5, respectively.

**Comment by Callidior** [comment]
@taehoonlee, looks good to me, thanks! :+1:

**Comment by taehoonlee** [comment]
Updated, @fchollet. Now there are only EfficientNetSmall and EfficientNetLarge.

**Comment by MichaelMonashev** [comment]
I use MobileNetV2 and found that `alpha` is very useful for setting up the network size. I think the choice between small and large by default is good. But it would be nice to have the parameters to configure the network size. For educational purposes and for some experiments.

**Comment by MichaelMonashev** [comment]
Another reason to make all EfficientNet variants available: https://arxiv.org/pdf/1911.09070.pdf

**Comment by taehoonlee** [comment]
@MichaelMonashev, Yes I would like to add all the variants. But the problem is that there are no official hyper-parameters to generate architectures.

**Comment by MichaelMonashev** [comment]
@taehoonlee , for default architecture we can use B0.
If user choose input_shape=(240,240,3), then it will be B1.  (260, 260,3) - B2. And so on. 
If user choose input_shape with unusual hyper-parameters, for example: (224,224,3), 1.8, 2.6, 0.5, then he will get network without pretrained weights.

It's easy for juniors and flexible enough for professionals. 

```
def EfficientNet(input_shape=None,
                width_coefficient=None,
                depth_coefficient=None,
                dropout_rate=None,
                include_top=True,
                weights='imagenet',
                input_tensor=None,
                pooling=None,
                classes=1000,
                **kwargs):
```

**Comment by taehoonlee** [comment]
@MichaelMonashev, Yes it is possible. But please refer to the chollet's [comment](https://github.com/keras-team/keras/pull/13427#issuecomment-541973466). It is not always good to give users a degree of freedom. As the authors said, width and depth multipliers should be generated by phi. But the problem is that there are no official numbers for phi. You can refer to my [notes](https://github.com/keras-team/keras/pull/13427#issuecomment-543001153) about phi.

**Comment by MichaelMonashev** [comment]
This will better:
```
def EfficientNet(input_shape=None,
                default_resolution=None,
                width_coefficient=None,
                depth_coefficient=None,
                dropout_rate=None,
                include_top=True,
                weights='imagenet',
                input_tensor=None,
                pooling=None,
                classes=1000,
                **kwargs):
```
If `input_shape` or `input_tensor` size not set, `default_resolution` will use to choose architecture and weights.

>  It is not always good to give users a degree of freedom.

I think we need to be able to independently change the width, depth and resolution of the network for experimentation and better understand how quality changes after these modifications.

**Comment by ZFTurbo** [comment]
I'd better leave all B0-B7 variants as it's closer to paper and user could choose what to use after reading. For example, I already used B0, B4 and B5 in my projects.

**Comment by Callidior** [comment]
Please keep in mind that all the B0-B7 variants as well as a freely parameterizable generic interface to EfficientNet will still be available in `keras_applications.efficientnet` and has already been integrated in https://github.com/keras-team/keras-applications/pull/113.

This PR, in contrast, is mainly about which variants to provide in the `keras.applications` namespace, which is expected to be used by a variety of less advanced users as well.
Whoever wants all choices and full customization simply needs to replace the dot in `keras.applications` with an underscore.

**Comment by taehoonlee** [comment]
@fchollet, I saw [the recent commit](https://github.com/tensorflow/tensorflow/commit/0d7620c3bc50b01054804d8c631b7eed45a7925b#diff-d9a6fb3dcce12faad950a97db6abe9ad) to TF. Do you think it's better to add all the variants now? If so, I'd like to update this PR FROM the small and large version TO the B0-B7 version. And then you can merge this PR. I would appreciate it if you could check this issue.

**Pull request closed without merging**
