### PR TITLE
Update normalization.py to fix a bug when "denormalizing"

### PR DESCRIPTION
**Pull request by Vincent-SV**
I created an issue yesterday to talk about this : keras Normalization layer doesn't denormalize properly, https://github.com/keras-team/keras/issues/17047

The denormalization (the .call method of the Normalization layer with invert = True) doesn't work properly for now (if you normalize and denormalize, you don't get the inputs back) and the problem is pretty obvious : you have to multiply by standard deviation first and then add the mean in order to invert the normalization process.
This change looks like an obvious improvement to me, BUT
- I am new to github and not totally sure I am doing things right
- I didn't test this change in any way (because it looks too complicated for me to test it)
- I don't really understand the role of backend.epsilon, it is possible something should be changed (I think it is needed only when dividing ?) 
- I searched a bit and this is the only place I found where this problem, but I don't fully understand how this change will fully fix this problem, maybe another similar change is needed elsewhere ?
- There is no test for "invert = True" in normalization_test.py, maybe it is an issue ?

### CODE REVIEW

**Comment by SalmanshariffSR** [comment]
How to update

**Comment by Vincent-SV** [comment]
Oops, I stated that there is no test for invert=True in normalization_test.py but that is false. There are 2 tests but they are only working because the variance is 1 (for both of them) so the wrong denormalization works in this case. I'll propose a slight modification of these tests.

**Review by fchollet — APPROVED** [review]
LGTM, thanks for the catch

**Comment by Vincent-SV** [comment]
I fixed a small oversight in a test I modified, and this time I actually tested my modifications (using docker), sorry for not doing it before.

**Review by fchollet — APPROVED** [review]
LGTM

**Pull request merged**
