### PR TITLE
support continue training

### PR DESCRIPTION
**Pull request by fsx950223**
This feature is for continued training when training is stopped by accident.
Restore correspond epochs and steps instead of 0.

### CODE REVIEW

**Comment by AdityaKane2001** [comment]
@fsx950223 

This is currently possible in Keras. Please take a look [here](https://towardsdatascience.com/resuming-a-training-process-with-keras-3e93152ee11a).

**Comment by fsx950223** [comment]
Could you provide an easier approach?

**Comment by AdityaKane2001** [comment]
I do something like this in my code:

```python
INIT_EPOCH = 0
with strategy.scope():
    optim = get_optimizer(train_cfg)

    model =Model(...)
    model.compile(
        loss=tf.keras.losses.CategoricalCrossentropy(
            from_logits=True, label_smoothing=train_cfg.label_smoothing),
        optimizer=optim,
        metrics=[
            tf.keras.metrics.CategoricalAccuracy(name="accuracy"),
            tf.keras.metrics.TopKCategoricalAccuracy(5, name="top-5-accuracy"),
        ],
    )
    if INIT_EPOCH > 0:
        model.load_weights("my/checkpoint/path/all_model_epoch_"+str(INIT_EPOCH))
    logging.info("Model loaded")

train_ds = ...
val_ds = ...


callbacks = get_callbacks()
if INIT_EPOCH > 0:
    count = 1252*INIT_EPOCH

    for i in range(len(callbacks)):
        try:
            callbacks[i].count = count
        except:
            pass

history = model.fit(
    train_ds,
   	epochs=train_cfg.total_epochs,
    steps_per_epoch=1252,
   	validation_data=val_ds,
   	callbacks=callbacks,
    validation_steps = 49,
    initial_epoch=INIT_EPOCH + 1
)
```
And I believe this is the most efficient way to do this.

**Comment by fsx950223** [comment]
> I do something like this in my code:
> 
> ```python
> INIT_EPOCH = 0
> with strategy.scope():
>     optim = get_optimizer(train_cfg)
> 
>     model =Model(...)
>     model.compile(
>         loss=tf.keras.losses.CategoricalCrossentropy(
>             from_logits=True, label_smoothing=train_cfg.label_smoothing),
>         optimizer=optim,
>         metrics=[
>             tf.keras.metrics.CategoricalAccuracy(name="accuracy"),
>             tf.keras.metrics.TopKCategoricalAccuracy(5, name="top-5-accuracy"),
>         ],
>     )
>     if INIT_EPOCH > 0:
>         model.load_weights("my/checkpoint/path/all_model_epoch_"+str(INIT_EPOCH))
>     logging.info("Model loaded")
> 
> train_ds = ...
> val_ds = ...
> 
> 
> callbacks = get_callbacks()
> if INIT_EPOCH > 0:
>     count = 1252*INIT_EPOCH
> 
>     for i in range(len(callbacks)):
>         try:
>             callbacks[i].count = count
>         except:
>             pass
> 
> history = model.fit(
>     train_ds,
>    	epochs=train_cfg.total_epochs,
>     steps_per_epoch=1252,
>    	validation_data=val_ds,
>    	callbacks=callbacks,
>     validation_steps = 49,
>     initial_epoch=INIT_EPOCH + 1
> )
> ```
> 
> And I believe this is the most efficient way to do this.

In fact, the solution is incorrect, since iterations may not equal to INIT_EPOCH*steps_per_epoch, it may be INIT_EPOCH*steps_per_epoch+100, but your solution only set init epoch(only works when iterations=INIT_EPOCH*steps_per_epoch), which got a wrong optimizer state(the state stored when iterations=INIT_EPOCH*steps_per_epoch+100)

**Comment by AdityaKane2001** [comment]
@fsx950223 

Yeah, sorry about that. Actually, I saw the changes you made later and got the point you were trying to make. 

> `iterations=INIT_EPOCH*steps_per_epoch+100`

The only issue I see now is the ModelCheckpoint which the user will be loading. Correct me if I'm wrong, won't the user most likely save at the end of each epoch? How would this help in that case?

PS. I am not extremely familiar with the checkpoint mechanisms that you might be using. If I am saying anything wrong, please feel free to let me know.

**Comment by fsx950223** [comment]
> @fsx950223
> 
> Yeah, sorry about that. Actually, I saw the changes you made later and got the point you were trying to make.
> 
> > `iterations=INIT_EPOCH*steps_per_epoch+100`
> 
> The only issue I see now is the ModelCheckpoint which the user will be loading. Correct me if I'm wrong, won't the user most likely save at the end of each epoch? How would this help in that case?
> 
> PS. I am not extremely familiar with the checkpoint mechanisms that you might be using. If I am saying anything wrong, please feel free to let me know.

For some situations such as transferring a tf1 ckpt to tf2 ckpt and continue train it or save_freq is an integer.

**Comment by fsx950223** [comment]
The solution is not perfect, temporary closed.

**Pull request closed without merging**
