### PR TITLE
Updated f-string method

### PR DESCRIPTION
**Pull request by cyai**
Used Flynt python tool to update the f-string method on all possible files of the benchmarks folder.

### CODE REVIEW

**Review by haifeng-jin — APPROVED** [review]
Thanks for the PR! Approve

**Comment by haifeng-jin** [comment]
@cyai Would you please sign the CLA? thx

**Comment by cyai** [comment]
I have already signed the CLA. Even though there is an error regarding this!

**Comment by haifeng-jin** [comment]
Send the author email address associated with the commit has not signed the CLA. Maybe the email is not associated with your account.

**Comment by cyai** [comment]
Okay, but now how can I sign a new CLA using the email ID associated with the commit? If I open the link to sign the CLA, then I am logged in with my other email ID, I couldn't find where is log out and login with the other email ID!

**Comment by haifeng-jin** [comment]
@gbaned Any idea on how to do this?
@cyai You may just add this signed email to your GitHub account, or change the commits to use the email associated with your GitHub account. I guess these solutions should work.
Sorry for the inconvenience.

**Comment by gbaned** [comment]
> @gbaned Any idea on how to do this? @cyai You may just add this signed email to your GitHub account, or change the commits to use the email associated with your GitHub account. I guess these solutions should work. Sorry for the inconvenience.

Hi @haifeng-jin I agree with you on this. Thank you!

**Comment by haifeng-jin** [comment]
@cyai 
So now the one you signed the CLA wiht is the same as the one on the commit?

The one you signed CLA with have to be the same one on this commit.
https://github.com/keras-team/keras/commit/afd86e95fc91b98dfb30eac27933b1e10b201b97.patch

You can check the one you used to signed CLA here:
https://cla.developers.google.com/clas

**Comment by cyai** [comment]
I have updated the email associated with the commits.

**Comment by cyai** [comment]
All checks have passed!

**Review by fchollet — APPROVED** [review]

**Pull request merged**
