### PR TITLE
OptimizerV2: Allow deepcopy

### PR DESCRIPTION
**Pull request by jschueller**
Closes https://github.com/tensorflow/tensorflow/issues/58973

### CODE REVIEW

**Comment by qlzh727** [comment]
Adding chen who is the owner of the optimizer. Please also add a unit test for this change.

**Review by chenmoneygithub — CHANGES_REQUESTED** [review]
Thanks for the PR! The code looks good to me, please add a unit test, and we can merge it, thanks!

**Comment by ianstenbit** [comment]
@chenmoneygithub could you approve the CI workflow?
I don't seem to have that power

**Review by chenmoneygithub — CHANGES_REQUESTED** [review]
Thx! Sorry about this (we should've been more clear), but could you move the test into a test case of file keras/optimizers/legacy/optimizer_v2_test.py? We mainly use a flat file structure in Keras.

**Comment by chenmoneygithub** [comment]
@ianstenbit Seems I cannot approve that either.... let me ping Francois

**Comment by jschueller** [comment]
ok, I moved the test

**Review by chenmoneygithub — APPROVED** [review]
Thank you!

**Comment by jschueller** [comment]
I fixed the test

**Comment by jschueller** [comment]
can you rerun @chenmoneygithub ?

**Comment by chenmoneygithub** [comment]
@jschueller I still don't have the permission.... I added Francois to the reviewer list so he can help with trigger the testing.

**Comment by jschueller** [comment]
ping @fchollet

**Review by qlzh727 — APPROVED** [review]
Sorry for the long wait.

**Pull request merged**
