### PR TITLE
[Requests for Contributions] Refactoring _standardize_input_data to make it faster. With explanations and benchmarks.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
Hi! First pull request, I hope it'll work out.

So I got inspired by the other pull request and decided to have a take at it. 
You can see the results of the benchmark in the notebook or if you don't want to bother with the notebook, there is a PDF version.

### Benchmark results:

data is a list and we don't test the shapes : 10.2% speedup.
data is a list and we test the shapes: 15% speedup.
data is a dictionary and we don't test the shapes: 17.9% speedup.
data is a single array and we don't test the shapes: 9.68% speedup.
data is a single array and we test the shapes: 10.4% speedup.

### Modifications:

When treating a dictionary:
- we can check the keys at the same time as looking for a DataFrame by doing a list comprehension with a try catch block.

When dealing with lists:
- checking for a DataFrame with a list comprehension is faster than using a for loop. 
- I removed a variable assignment.

When dealing with single arrays:
- no changes

For all types of inputs:
- List comprehension to expand the dimensions if necessary rather than a for loop.

When checking the shapes:
- Removed a continue by inverting a if statement.
- When check_batch_axis is set to true, the variable start is set to 1 instead of 0, so we know where we need to start checking the dimensions.

All of this have been done with a line profiler, I tried to balance readability and speed. For the future, using the notebook I made to test speed can be useful.

[benchmark.pdf](https://github.com/keras-team/keras/files/1594519/benchmark.pdf)
[notebook.zip](https://github.com/keras-team/keras/files/1594521/notebook.zip)

### CODE REVIEW

**Comment by fchollet** [comment]
@taehoonlee please review. I think we may be able to merge both PRs?

**Comment by taehoonlee** [comment]
@fchollet and @gabrieldemarmiesse, I think there are four main bottlenecks:
1. The loop for retrieving dictionary value: for loop -> list comprehension
2. The loop for DataFrame checking: for loop -> list comprehension
3. The loop for singleton array checking: for loop -> list comprehension
4. The check for singleton array: `len(x.shape)` -> `x.ndim` 

Gabriel applied 1, 2, 3 while I did 1 and 4. The rest of the changes are improvements in readability. Thus, I my opinion:
- Merge #8920 after replacement of `len(x.shape)` by `x.ndim`.
- Merge #8892 for further optimizations and readability.

My benchmark results (% speed-up) with @gabrieldemarmiesse's scripts are as follows:

|         | rev 1 (#8920) | rev 2 (rev 1 + ndim) | rev 3 (#8892) |
|---------|---------------|----------------------|---------------|
| bench 1 | 14.8          | 24.0                 | 27.3          |
| bench 2 | 24            | 25.8                 | 30.6          |
| bench 3 | 22.4          | 25.8                 | 28.8          |
| bench 4 | 9.74          | 13.6                 | 31.5          |
| bench 5 | 16.6          | 14.0                 | 28.3          |

**Comment by gabrieldemarmiesse** [comment]
Thank you very much! I'll change it now!

**Comment by gabrieldemarmiesse** [comment]
It's done. I also fixed a small bug in the try except.

**Pull request merged**
