### PR TITLE
Remove reduce sum impl in batch dot

### PR DESCRIPTION
**Pull request by farizrahman4u**
### Related Issues

#11719 

### PR Overview

- [y ] This PR requires new unit tests [y/n] (make sure tests are included)
- [n ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y ] This PR is backwards compatible [y/n]
- [n ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
> Weird. Tests pass for me locally. Maybe changes in TF.

Travis has a pretty old version of tensorflow. That might explain some things.

**Comment by farizrahman4u** [comment]
Hmm. So 2 options: change Travis's TF to latest or I figure out a way to make this PR work in tf 1.9.

@gabrieldmarmiesse thoughts?

**Comment by farizrahman4u** [comment]
@gabrieldemarmiesse hmm. that should do.

**Comment by farizrahman4u** [comment]
I have made the change, but for Variables, the first dimension is not necessarily a batch dimension right?
Also losing a batch dimension after explicitly providing it would mean you cant add a stateful LSTM after etc.
Anyway this seems to be bug on TF side since it works on latest version of TF, and it has gotten too niche at this point for me to put more time into it. So I think this is it :)

**Comment by farizrahman4u** [comment]
@gabrieldemarmiesse tests passing. please merge if everything else is ok.

**Pull request merged**
