### PR TITLE
Do not copy params in `get_params`.

### PR DESCRIPTION
**Pull request by mcarbajo**
### Summary

For compatibility with the scikit-learn `clone` function `get_params` has to return the same parameters as given in the __init__ function. Fix issue #13586

### Related Issues

#13586

### PR Overview

- [ ] This PR requires new unit tests [y/n] (make sure tests are included)
- [ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by zachmayer** [comment]
[One test](https://travis-ci.org/keras-team/keras/jobs/619738176?utm_medium=notification&utm_source=github_status) on python 3.6/TF 2.0 failed:
`[gw1] [ 94%] FAILED tests/keras/utils/data_utils_test.py::test_ordered_enqueuer_timeout_threads `


```python
===== 1 failed, 1126 passed, 114 skipped, 49 warnings in 498.19s (0:08:18) =====
Using TensorFlow backend.
The command "if [[ "$MODE" == "INTEGRATION_TESTS" ]]; then PYTHONPATH=$PWD:$PYTHONPATH py.test tests/integration_tests; elif [[ "$MODE" == "PEP8_DOC" ]]; then PYTHONPATH=$PWD:$PYTHONPATH py.test --pep8 -m pep8 -n0 && py.test tests/docs; elif [[ "$MODE" == "API" ]]; then PYTHONPATH=$PWD:$PYTHONPATH pip install git+git://www.github.com/keras-team/keras.git && python update_api.py && pip install -e .[tests] --progress-bar off && py.test tests/test_api.py; elif [[ "$RUN_ONLY_BACKEND_TESTS" == "1" ]]; then PYTHONPATH=$PWD:$PYTHONPATH py.test  tests/keras/backend/; else PYTHONPATH=$PWD:$PYTHONPATH py.test tests/ --ignore=tests/integration_tests --ignore=tests/docs --ignore=tests/keras/legacy/layers_test.py --ignore=tests/test_api.py --cov-config .coveragerc --cov=keras tests/; fi" exited with 1.
cache.2
store build cache
Done. Your build exited with 1.
```

Maybe it's a flake and re-running will pass?

**Comment by mcarbajo** [comment]
It could. Clearly the error is not related to the small change made

**Comment by zachmayer** [comment]
Any idea how to re-run that test?

**Comment by zachmayer** [comment]
@fchollet How do we re-run the tests on this PR?  It seems like the test failure is a flake, but we are not sure.

**Comment by amueller** [comment]
Any news on this?

**Comment by zachmayer** [comment]
@amueller  I think we just need to get someone from keras to re-run tests on this PR.

@fchollet Can you re-trigger travis on this PR, so we can get passing tests?

**Comment by zachmayer** [comment]
This is a silly question, but how would I checkout this branch locally?

**Comment by cmarmo** [comment]
Hi all, sorry for stepping in, I was investigating the [scikit-learn issue 17022](scikit-learn/scikit-learn/issues/17022) and that led me here. I have checked out this branch: for me it fixes [scikit-learn 17022](scikit-learn/scikit-learn/issues/17022) and [scikit-learn issue 15722](https://github.com/scikit-learn/scikit-learn/issues/15722) opened by @mcarbajo himself.

> This is a silly question, but how would I checkout this branch locally?

@zachmayer, here the command line procedure I used (I beg your pardon if I misunderstood your question)
```
$ git remote add mcarbajo https://github.com/mcarbajo/keras.git
$ git fetch mcarbajo
$ git checkout -b mcarbajopatch -t mcarbajo/patch-1 
```

Hope it could help to finalize this. Thanks for listening.

**Comment by zachmayer** [comment]
@cmarmo thanks!  I'm gonna try to make a new PR sometime and see if I can get this test to pass.

**Comment by johannesjung** [comment]
Any updates on this? @zachmayer, did you create a new PR?

**Comment by zachmayer** [comment]
I still can't make my own PR:  

```bash
Mayer-2:keras zach2$ git checkout -b mcarbajopatch -t mcarbajo/patch-1 
fatal: 'mcarbajo/patch-1' is not a commit and a branch 'mcarbajopatch' cannot be created from it
```

**Comment by cmarmo** [comment]
@zachmayer do you mind checking that you have run `git fetch mcarbajo` first? Thanks.

**Comment by zachmayer** [comment]
I did run `git fetch mcarbajo` first. I just tried again, same error. `gh pr checkout 13598` worked for me though

**Comment by zachmayer** [comment]
ok, the conflict in `keras/wrappers/scikit_learn.py` is gonna be hard to fix lol.  The whole file is now just `from tensorflow.keras.wrappers.scikit_learn import *`

@fchollet Should we stop making PRs to the keras repo and try to fix this in the tensorflow repo?

**Comment by zachmayer** [comment]
https://github.com/keras-team/keras/blob/master/keras/wrappers/scikit_learn.py

**Comment by zachmayer** [comment]
I'll try making a PR here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/wrappers/scikit_learn.py

**Comment by zachmayer** [comment]
I made a PR to tensorflow here: https://github.com/tensorflow/tensorflow/pull/41341

**Comment by yishakgashew21-create** [comment]
I couldn't make it work help me please I'm a bigginer.                                                                                                                                     

AttributeError                            Traceback (most recent call last)
[/tmp/ipython-input-3664916925.py](https://localhost:8080/#) in <cell line: 0>()
      9 
     10 rnd_search_cv = RandomizedSearchCV(keras_reg, param_distribs, n_iter=10, cv=3, verbose=2)
---> 11 rnd_search_cv.fit(X_train, y_train, epochs=100,
     12                   validation_data=(X_valid, y_valid),
     13                   callbacks=[keras.callbacks.EarlyStopping(patience=10)])

4 frames
[/usr/local/lib/python3.12/dist-packages/sklearn/base.py](https://localhost:8080/#) in __sklearn_tags__(self)
    611 
    612     def __sklearn_tags__(self):
--> 613         tags = super().__sklearn_tags__()
    614         tags.estimator_type = "regressor"
    615         tags.regressor_tags = RegressorTags()

AttributeError: 'super' object has no attribute '__sklearn_tags__'

**Pull request closed without merging**
