### PR TITLE
Fix `inplace operation` in LSTM when using torch backend

### PR DESCRIPTION
**Pull request by dugujiujian1999**
Fix [#18958](https://github.com/keras-team/keras/issues/18958)

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @dugujiujian1999  Can you please sign CLA. Thank you!

**Comment by dugujiujian1999** [comment]
@gbaned i keeps got a 'A server error occurred, please try your request again.' at that page. I am trying to figure out the way to solve it.

**Comment by dugujiujian1999** [comment]
@gbaned I Signed now. May i need to use the Google email to do the pr again?

**Comment by dugujiujian1999** [comment]
@gbaned Ok. Signed. Thank you.

**Review by fchollet — APPROVED** [review]
LGTM, thanks for the fix!

**Pull request merged**
