### PR TITLE
Documentation fix for depreciated keras.preprocessing

### PR DESCRIPTION
**Pull request by AdityaPunetha**
Code still used the depreciated `tf.keras.preprocessing.image` method in usage documentation which caused other docs to show wrong documentation as well such as the [Tensorflow's img_to_array](https://www.tensorflow.org/api_docs/python/tf/keras/utils/img_to_array#usage)

### CODE REVIEW

**Comment by AdityaPunetha** [comment]
Changed indentation to multiple of 4 in line 2095 of confusion_matrix_test.py

**Comment by AdityaPunetha** [comment]
formatted confusion_matrix_test.py with black --line-length 80 as mentioned in format.sh

**Review by fchollet — APPROVED** [review]
LGTM, thanks

**Comment by fchollet** [comment]
> This branch cannot be rebased due to conflicts

Please fix.

**Comment by fchollet** [comment]
> This branch cannot be rebased due to conflicts

Please rebase.

**Comment by gbaned** [comment]
@AdityaPunetha Can you please check @fchollet's comments and keep us posted ? Thank you!

**Comment by gbaned** [comment]
@AdityaPunetha Any update on this PR? Please. Thank you!

**Comment by fchollet** [comment]
It appears this has already been fixed at head. Thanks anyway!

**Pull request closed without merging**
