### PR TITLE
Close _SESSION.session in clear_session

### PR DESCRIPTION
**Pull request by sfreilich**
Thanks to nostalgebraist for pointing out this bug:
https://nostalgebraist.tumblr.com/post/641628845811908608

clear_session sets _SESSION.session to None. But since that may have circular references, that's not sufficient to get it garbage collected immediately. The documentation for Session notes that this is important:  
https://www.tensorflow.org/api_docs/python/tf/compat/v1/Session

> A session may own resources, such as tf.Variable, tf.queue.QueueBase, and tf.compat.v1.ReaderBase. It is important to release these resources when they are no longer required. To do this, either invoke the tf.Session.close method on the session, or use the session as a context manager.

### CODE REVIEW

**Comment by deeb02** [comment]
@sfreilich, we moved the tensorflow specific implementation tf.Keras to this repository. If you think this PR is still relevant, please rebased and re-run the tests.

**Comment by sfreilich** [comment]
I merged from head. I think it's still relevant, can you merge the change?

**Review by deeb02 — APPROVED** [review]
LGTM.

**Comment by sfreilich** [comment]
Saw CI failures, updated the PR. Not sure if I overlooked that bug in my initial testing or if something changed under me.

**Pull request merged**
