### PR TITLE
Add documentation on how to use Tensorflow Optimizers

### PR DESCRIPTION
**Pull request by rohit-gupta**
### Summary

Recently there's been some research on new optimizers from the Deep Learning community (e.g. [AdamW](http://www.fast.ai/2018/07/02/adam-weight-decay/)). Some of these optimizers are implemented in Tensorflow and Tensorflow Contrib, However, its not widely known how Keras can leverage Tensorflow optimizers. This PR adds a small section to the Optimizers page of the Keras documentation explaining how it can be done. 

### Related Issues

https://github.com/keras-team/keras/issues/11067
 Mailing List: https://groups.google.com/forum/#!topic/keras-users/r_2E-WS8tXY

### PR Overview

- [n] This PR requires new unit tests [y/n] (make sure tests are included)
- [y] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [n] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
In general, since `keras-team/keras` has a strong compatibility with tensorflow (dataset API, input tensors, TF optimizers, ability to add layers even if the tensor has no `_keras_history`), I think it would make sense to have in the documentation an entire page called **tensorflow specific compatibility features** (this is a bad name, but the idea is here). 

It would incorporate and update some ideas present in https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html

Thoughts?

**Comment by rohit-gupta** [comment]
@gabrieldemarmiesse This sounds useful to me. I have run into problems sometimes because its not clear how Keras integrates with Tensorflow on some features. In addition to Francois's excellent blog post, we can also include material from this post:

http://zachmoshe.com/2017/11/11/use-keras-models-with-tf.html

**Comment by gabrieldemarmiesse** [comment]
While the post you are mentioning shows methods that are not the standard way to accomplish the act of extracting intermediate representation of a model, it shows that there are a lot of confusion about the integration between keras and Tensorflow (maybe due to historical reasons). It emphasises the case for a dedicated page in the documentation.

**Comment by gabrieldemarmiesse** [comment]
Can you merge the latest version of master into your branch? That will solve the travis CI issue.

**Comment by rohit-gupta** [comment]
Hi @gabrieldemarmiesse, I merged the latest fixes. I totally agree with your point about the need for a dedicated resource about Tensorflow compatibility. I will try and work on this and send a PR when I have something presentable.

**Comment by gabrieldemarmiesse** [comment]
I didn't have much time this week to review, sorry about that. 

I think it's better to make a separate page in the doc for everything related to Tensorflow. Don't worry if what you make is not perfect, make a PR and we'll work together to make it as nice as possible :)

**Comment by taehoonlee** [comment]
Thank you for the PR, @rohit-gupta. TF optimizers should be used with `TFOptimizer`. Please add `from keras.optimizers import TFOptimizer` and revise the example as `compile(optimizer=TFOptimizer(ADoptimizer()))`.

**Comment by gabrieldemarmiesse** [comment]
@taehoonlee That point isn't very clear. For example, https://github.com/keras-team/keras/blob/3fed40a2d6d6877694a5b034c5ea07e04757c82c/tests/integration_tests/test_tensorflow_integration.py#L20 shows that we test to make sure that Tensorflow optimizers don't need to be wrapped.
#11067  shows that some tensorflow's optimizers don't work when wrapped.

The documentation about TFOptimizer is not very developed. https://keras.io/optimizers/#tfoptimizer

Do you have any insights on this? It's not very clear to me what the "official" way of using TF optimizers is.

**Comment by taehoonlee** [comment]
@gabrieldemarmiesse, Good point. I think that it was the official way to use the wrapper, but it has been possible to use a native TF optimizer since some point. Maybe we need to investigate a Keras version that enables us to remove the wrapper.

**Comment by rohit-gupta** [comment]
So, I have been doing a bit of digging and it seems like the problem I had gotten in https://github.com/keras-team/keras/issues/11067 was incorrect. Wrapping the Tensorflow Optimizer actually works fine, the code wasn't working because I was passing the wrong arguments to the optimizer and for some reason the error message didn't make this clear.  This code works fine for example:


```
import numpy as np

from keras import optimizers, Input
from keras.models import Sequential, Model
from keras.layers.core import Dense, Activation, Lambda

from tensorflow.contrib.opt import MomentumWOptimizer, AdamWOptimizer


num_classes = 2

#tfoptimizer = AdamWOptimizer(weight_decay=0.1, learning_rate=0.001, momentum=0.9, use_nesterov=True)
# options = {'weight_decay': 0.1, 'learning_rate': 0.001, 'momentum': 0.9, 'use_nesterov': True}
#options = {'weight_decay': 0.1, 'learning_rate': 0.001}


tfoptimizer = AdamWOptimizer(weight_decay=0.1, learning_rate=0.001, beta1=0.9, beta2=0.99)
optimizer = optimizers.TFOptimizer(tfoptimizer)

model = Sequential()
model.add(Dense(num_classes, activation="tanh", input_shape=(3,)))
model.compile(loss='mean_squared_error', optimizer=optimizer)
model.fit(np.random.random((100, 3)), np.random.random((100, num_classes)), epochs=10, batch_size=5)
```


Additionally, I also looked at `keras/optimizers.py` and I think the main purpose served by the TFOptimizer wrapper is during serialization.

**Comment by fchollet** [comment]
`TFOptimizer` should not have been in the docs in the first place. I have blacklisted it in a separate commit.

Thank you.

> I think it's better to make a separate page in the doc for everything related to Tensorflow. 

That's in general a good idea. We can do this in a separate PR.

**Pull request closed without merging**
