### PR TITLE
torch backend use torch dataloader directly

### PR DESCRIPTION
**Pull request by haifeng-jin**
Related to #18408, but more follow up PRs required to fully resolve it.

When using torch backend and torch dataloader together, Keras used to convert it to numpy first.
This PR let torch backend trainer directly use the torch dataloader without the numpy conversion.

It also involves some minor refactor to keep the `data_adapters` module more modularized.

### CODE REVIEW

**Comment by hertschuh** [comment]
@haifeng-jin , looking at the data adapters, I had the same thoughts, which are that:

- it would be nice to have a mode where you get "native" tensors for the current backend, or at least you get tensors that work directly with the backend (for instance Tensorflow accepts numpy arrays directly without conversion).
- it would be nice to not do any conversion unless it's needed.

Now this raises a couple of questions:

- Do we want to explicitly support `return_type="torch"` and `return_type="jax"`? I don't think so
- How do we call that "backend native" `return_type`? You called it `auto`, which I think is fine. But maybe `backend` or `native` would be more explicit. What do you think?
- Do we need to add a `get_..._iterator()` to `DataAdapter`. Right now it has `get_tf_dataset()` and `get_numpy_iterator()`? What do we call it and what does it return? `get_backend_compatible_iterator()` which returns either native tensors or tensors that we know can be consumed directly without conversion? Once we do that, do we still need both `get_tf_dataset()` and `get_numpy_iterator()`?

By the way, I'm not saying this PR should address all of these. The only thing for now is to decide on how we call `auto`. But I'd like us to discuss these at some point.

**Comment by haifeng-jin** [comment]
@hertschuh
Thanks for the comments!

> * it would be nice to have a mode where you get "native" tensors for the current backend, or at least you get tensors that work directly with the backend (for instance Tensorflow accepts numpy arrays directly without conversion).
> * it would be nice to not do any conversion unless it's needed.

Agree.

> * Do we want to explicitly support `return_type="torch"` and `return_type="jax"`? I don't think so

Agree. The "auto" should be good enough for all current use cases.

> * How do we call that "backend native" `return_type`? You called it `auto`, which I think is fine. But maybe `backend` or `native` would be more explicit. What do you think?

I think "auto" is better, as it may not always be backend native, for example, it may just return numpy sometime. And "auto" follows the naming tradition of `verbose="auto"` in `model.fit()`.

> * Do we need to add a `get_..._iterator()` to `DataAdapter`. Right now it has `get_tf_dataset()` and `get_numpy_iterator()`? What do we call it and what does it return? `get_backend_compatible_iterator()` which returns either native tensors or tensors that we know can be consumed directly without conversion? Once we do that, do we still need both `get_tf_dataset()` and `get_numpy_iterator()`?

My plan is: `DataAdapter`'s methods will remain explicit about the types they return to keep it backend agnostic.
I think it would be better to keep the backend related logics in the `EpochIterator` subclasses in the backend directories (e.g. `backend/torch`). Each trainer would use a subclass of `EpochIterator` in `trainer.py` to get the native types.

**Comment by fchollet** [comment]
> I think it would be better to keep the backend related logics in the EpochIterator subclasses in the backend directories (e.g. backend/torch). Each trainer would use a subclass of EpochIterator in trainer.py to get the native types.

This is reasonable, +1 to this approach.

**Review by fchollet — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
