### PR TITLE
Revert #10995 since the timeout is not related to a keras test in particular.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
### Summary

Revert #10995 since the timeout is not related to a keras test in particular.
The timeout isn't useful.

### PR Overview

- [ ] This PR requires new unit tests [y/n] (make sure tests are included)
- [ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by fchollet** [comment]
> The timeout isn't useful.

I think it would be useful to restart on timeout the tests that are causing the timeout, which are most likely tests related to `Sequence`/etc.

**Comment by gabrieldemarmiesse** [comment]
You mean all tests using multiprocessing?

**Comment by fchollet** [comment]
I think the problem is likely not *all* tests related to multiprocessing. There's probably a small number of tests that cause the issue.

You can try to find them by looking at which tests do *not* get logged as passing in the past few failing builds (compare to the list of passing tests for a successful build).

**Comment by gabrieldemarmiesse** [comment]
I'll see if I can find something then by looking at the logs. Give me some time. I'll close this issue for now.

**Pull request closed without merging**
