### PR TITLE
Added constant_values support to pad

### PR DESCRIPTION
**Pull request by jackd**
Added `constant_values` kwarg to `ops.pad`. This argument is ignored if `mode != 'constant'`, which is different to `numpy` which raises.

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR!

>  This argument is ignored if mode != 'constant', which is different to numpy which raises.

Why so? I would suggest sticking to the NumPy behavior and raising.

**Comment by jackd** [comment]
>> Why so?

I don't think there's anything erroneous/exceptional about specifying constant values that are never used, and I don't like propagating bad design. I'm not going to die on this hill though...

**Comment by fchollet** [comment]
It's not bad design, raising actually helps the user notice that they've made a mistake. Specifying values that are never used cannot be intentional, so what the user intended was something else (e.g. using constant mode).

**Comment by jackd** [comment]
> Specifying values that are never used cannot be intentional

So we should also raise if `np.all(pad_width==0)` and `constant_values is not None`?

**Review by fchollet — APPROVED** [review]
LGTM, thank you

**Pull request merged**
