### PR TITLE
Add pip cache

### PR DESCRIPTION
**Pull request by taehoonlee**
This PR adds pip cache (see [the official docs](https://docs.travis-ci.com/user/caching/#before_cache-phase)). This helps CI to reduce building time of `bdist_wheel` for `theano, subprocess32, pyyaml, pytest-pep8 pytest-cache, termcolor, gast, absl-py`.

### CODE REVIEW

**Comment by taehoonlee** [comment]
Success on Travis but reopened to test the caching effect.

**Comment by taehoonlee** [comment]
Heavy cache size but slight improvements of build times:
- The `install.10`: 15.06s -> 8.73s,
- The `install.15`: 4.40s -> 3.19s,
- The `install.16`: 13.90s -> 11.14s,
- The `install.17`: 7.55s -> 3.62s,
- The cache size: 193.94MB -> 1978.99MB (10x).

This PR needs to be revised...

**Comment by gabrieldemarmiesse** [comment]
It also takes a bit of time to download the cache (at the start of the build) it's important to measure and report this speed decrease I think (decrease since the cache is going to be bigger).

**Comment by taehoonlee** [comment]
@gabrieldemarmiesse, You are right. Now it looks about 11 seconds. I'll try another approach.

**Comment by taehoonlee** [comment]
Moved to #11128.

**Pull request closed without merging**
