### PR TITLE
MAINT: Updated f-string method

### PR DESCRIPTION
**Pull request by cyai**
Used Flynt tool to update the f-string method  for each possible file from the `distribute` folder

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
Reminder: you need to sign the CLA.

**Comment by rthadur** [comment]
Please fix the lint errors 

`keras/distribute/distributed_training_utils_v1.py:387:81: E501 line too long (85 > 80 characters)
keras/distribute/distributed_training_utils_v1.py:397:81: E501 line too long (85 > 80 characters)
Please fix the code style issue.`

**Comment by gbaned** [comment]
@cyai Can you please check @rthadur's comments and keep us posted ? Thank you!

**Comment by gbaned** [comment]
@wcyai Any update on this PR? Please. Thank you!

**Pull request closed without merging**
