### PR TITLE
Metric support for cross-replica contexts

### LINKED ISSUE #16828: Reduce metrics do not support cross-replica context
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubunto 18.04.6 LTS**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **2.9.1**
- Python version: **3.9.12**
- Bazel version (if compiling from source): **N/A**
- GPU model and memory: **NVIDIA GeForce GTX 1060 6GB**
- Exact command to reproduce:

```python
import tensorflow as tf
from tensorflow import keras

with tf.distribute.MirroredStrategy().scope():
    metric = keras.metrics.Mean()
    metric.update_state(0)
```

**Describe the problem**.

Trying to call `update_state` on a `keras.metrics.Mean` object within a cross-replica context (specifically `tf.distribute.MirroredStrategy`) raises `ValueError: SyncOnReadVariable does not support 'assign_add' in cross-replica context when aggregation is set to 'tf.VariableAggregation.SUM'`

**Describe the current behavior**.

The metric throws the error: `ValueError: SyncOnReadVariable does not support 'assign_add' in cross-replica context when aggregation is set to 'tf.VariableAggregation.SUM'.`

**Describe the expected behavior**.

The metric should correctly update its state, regardless of distribution strategy.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): **yes**
- Briefly describe your candidate solution(if contributing):

Replace all `variable.assign_add(update)` calls with `variable.assign(variable.read_value() + update)`. Add a test case for distributed metrics.

**Standalone code to reproduce the issue**.

```python
import tensorflow as tf
from tensorflow import keras

with tf.distribute.MirroredStrategy().scope():
    metric = keras.metrics.Mean()
    metric.update_state(0)
```

**Source code / logs**.

```
ValueError                                Traceback (most recent call last)
Input In [8], in <cell line: 1>()
      1 with tf.distribute.MirroredStrategy().scope():
      2     metric = keras.metrics.Mean()
----> 3     metric.update_state(0)

File ~/anaconda3/envs/tf-2.9.0/lib/python3.9/site-packages/keras/utils/metrics_utils.py:70, in update_state_wrapper.<locals>.decorated(metric_obj, *args, **kwargs)
     64     raise ValueError(
     65         'Trying to run metric.update_state in replica context when '
     66         'the metric was not created in TPUStrategy scope. '
     67         'Make sure the keras Metric is created in TPUstrategy scope. ')
     69 with tf_utils.graph_context_for_symbolic_tensors(*args, **kwargs):
---> 70   update_op = update_state_fn(*args, **kwargs)
     71 if update_op is not None:  # update_op will be None in eager execution.
     72   metric_obj.add_update(update_op)

File ~/anaconda3/envs/tf-2.9.0/lib/python3.9/site-packages/keras/metrics/base_metric.py:140, in Metric.__new__.<locals>.update_state_fn(*args, **kwargs)
    137 control_status = tf.__internal__.autograph.control_status_ctx()
    138 ag_update_state = tf.__internal__.autograph.tf_convert(
    139     obj_update_state, control_status)
--> 140 return ag_update_state(*args, **kwargs)

File ~/anaconda3/envs/tf-2.9.0/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py:689, in convert.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    687 try:
    688   with conversion_ctx:
--> 689     return converted_call(f, args, kwargs, options=options)
    690 except Exception as e:  # pylint:disable=broad-except
    691   if hasattr(e, 'ag_error_metadata'):

File ~/anaconda3/envs/tf-2.9.0/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py:331, in converted_call(f, args, kwargs, caller_fn_scope, options)
    329 if conversion.is_in_allowlist_cache(f, options):
    330   logging.log(2, 'Allowlisted %s: from cache', f)
--> 331   return _call_unconverted(f, args, kwargs, options, False)
    333 if ag_ctx.control_status_ctx().status == ag_ctx.Status.DISABLED:
    334   logging.log(2, 'Allowlisted: %s: AutoGraph is disabled in context', f)

File ~/anaconda3/envs/tf-2.9.0/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py:458, in _call_unconverted(f, args, kwargs, options, update_cache)
    455   return f.__self__.call(args, kwargs)
    457 if kwargs is not None:
--> 458   return f(*args, **kwargs)
    459 return f(*args)

File ~/anaconda3/envs/tf-2.9.0/lib/python3.9/site-packages/keras/metrics/base_metric.py:465, in Reduce.update_state(self, values, sample_weight)
    463 value_sum = tf.reduce_sum(values)
    464 with tf.control_dependencies([value_sum]):
--> 465   update_total_op = self.total.assign_add(value_sum)
    467 # Exit early if the reduction doesn't have a denominator.
    468 if self.reduction == metrics_utils.Reduction.SUM:

File ~/anaconda3/envs/tf-2.9.0/lib/python3.9/site-packages/tensorflow/python/distribute/values.py:1313, in SyncOnReadVariable.assign_add(self, value, use_locking, name, read_value)
   1310 if (ds_context.in_cross_replica_context() and
   1311     not values_util.in_replica_update_context()):
   1312   values_util.mark_as_unsaveable()
-> 1313   return values_util.on_read_assign_add_cross_replica(
   1314       self, value, read_value=read_value)
   1315 else:
   1316   return super(SyncOnReadVariable,
   1317                self).assign_add(value, use_locking, name, read_value)

File ~/anaconda3/envs/tf-2.9.0/lib/python3.9/site-packages/tensorflow/python/distribute/values_util.py:197, in on_read_assign_add_cross_replica(var, value, read_value)
    195 if ds_context.in_cross_replica_context():
    196   if var.aggregation == vs.VariableAggregation.SUM:
--> 197     raise ValueError(
    198         "SyncOnReadVariable does not support `assign_add` in "
    199         "cross-replica context when aggregation is set to "
    200         "`tf.VariableAggregation.SUM`.")
    201   return assign_on_each_device(var, assign_add_on_device,
    202                                value, read_value)

ValueError: SyncOnReadVariable does not support `assign_add` in cross-replica context when aggregation is set to `tf.VariableAggregation.SUM`.
```

### PR DESCRIPTION
**Pull request by tylerpayne**
Replace all `variable.assign_add(update)` calls with `variable.assign(variable.read_value() + update)`

Resolves #16828

### CODE REVIEW

**Comment by tylerpayne** [comment]
Passed all tests minus a few timeouts running in the provided Docker image.

**Comment by tylerpayne** [comment]
Sorry about that, just ran formatting and passed linting locally. See https://github.com/keras-team/keras/pull/16829/commits/aa5e7be13e2b9b460f0a5efbe6859af345b95852

**Comment by fchollet** [comment]
Thanks for the PR!

@rchao what do you think about this change?

**Comment by rchao** [comment]
Thanks @tylerpayne for the PR! The logic makes sense to me, but there are a couple questions:

1) There appeared to be a reason why tf.distribute blocked using `assign_add`, `assign_sub`, etc. (in tensorflow/python/distribute/values_util.py). Do you understand why and is using `+=` to work around that a safe change?
2) Is the usage of `+=` here in the changes something autograph can capture properly so `metric.merge_state()` remains fully compatible with `tf.function`?

**Comment by tylerpayne** [comment]
@rchao I'll investigate and report back!

**Comment by tylerpayne** [comment]
So I think I misinterpreted "Cross-Replica-Context" vs "Per-Replica-Context." Tensorflow is correct to throw an error if I try to assign_add  in the cross replica context to a SyncOnReadVariable with Sum aggregation. In the cross-replica-context it is ambiguous how to distribute the op to each replica. To be pedantic, the difference is highlighted by these two examples:

(Incorrect) Updating the metric in the Cross Replica Context
```python
with strategy.scope():
  metric = keras.metrics.Mean()
  metric.update_state(0)
```

(Correct) Updating the metric in the Per Replica Contexts
```python
with strategy.scope():
  metric = keras.metrics.Mean()
  strategy.run(metric.update_state, args=(0,))
```

**Comment by rchao** [comment]
@tylerpayne thanks for the context and the examples make sense to me - do you imply that the PR should not be further pursued or you intend to work on alternatives?

**Comment by gbaned** [comment]
Hi @tylerpayne Can you please check @rchao's comments and keep us posted ? Thank you!

**Comment by gbaned** [comment]
Hi @tylerpayne Any update on this PR? Please. Thank you!

**Pull request closed without merging**
