### PR TITLE
Fix ImageDataGenerator preprocessing_function

### PR DESCRIPTION
**Pull request by davinnovation**
preprocessing_function must run before any other modification on image (by documentation)

by [issue](https://github.com/keras-team/keras/issues/9049)
Discussed on [keras-user-googlegroup](https://groups.google.com/forum/#!topic/keras-users/rjqLkpKIiH4), I suggested preprocessing function's option parameter for executing before resize.
But It must run before any modification according to documentation. [](url)

### CODE REVIEW

**Comment by ahundt** [comment]
Which resize is being used, bilinear or nearest neighbor? Have you tried bilinear interpolation?

This other preprocessing issue may also be related:
https://github.com/keras-team/keras/issues/8916

**Comment by davinnovation** [comment]
@ahundt In keras image preprocess function - load_img(target_shape) uses PIL.Image.NEAREST.
Haven't tried bilinear option. Thanks for the notice.

**Comment by Dref360** [comment]
On your google-doc you add a argument to specify the order, why is it not the case here?

**Comment by davinnovation** [comment]
@Dref360 By DataImageGenerator [Document](https://keras.io/preprocessing/image/), preprocessing_function should be run before any other modification on it. 
I noticed [issue](https://github.com/keras-team/keras/issues/9049) - (resize before preprocessing) isn't the considered case, but it was a bug. 
So I canceled argument suggestion and correct a bug.

In my opinion, google-doc's argument should be added after discussing change description of DataImageGenerator - preprocessing_function

**Comment by ozabluda** [comment]
@davinnovation, @Dref360  

I started getting the following exception, [I am pretty sure] due to this PR:
```
Traceback (most recent call last):
  File "oleg/ResNet50.NewClasses.py", line 118, in <module>
    validation_data=test_generator
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.5/dist-packages/keras/preprocessing/image.py", line 860, in __next__
    return self.next(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/preprocessing/image.py", line 1283, in next
    return self._get_batches_of_transformed_samples(index_array)
  File "/usr/local/lib/python3.5/dist-packages/keras/preprocessing/image.py", line 1233, in _get_batches_of_transformed_samples
    img = self.image_data_generator.preprocessing_function(img)
  File "/usr/local/lib/python3.5/dist-packages/keras/applications/imagenet_utils.py", line 178, in preprocess_input
    mode=mode)
  File "/usr/local/lib/python3.5/dist-packages/keras/applications/imagenet_utils.py", line 132, in _preprocess_symbolic_input
    x = x[..., ::-1]
TypeError: 'JpegImageFile' object is not subscriptable
```
When using
```
train_datagen = image.ImageDataGenerator(preprocessing_function = resnet50.preprocess_input)
train_generator = train_datagen.flow_from_directory("/dir/with/jpegs")
```

doing print(img) before line 1233 prints
```
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x7F6AD4FC2D30>
```

**Comment by davinnovation** [comment]
@ozabluda thanks for reporting. 
By keras documentation, Imagedatagenerator’s preprocessing function must return numpy tensor, but resnet50.preprocessing_input function returns ‘JpegImageFile’ type.

**Comment by davinnovation** [comment]
I’ll look for this. Thanks for review. @ozabluda

**Comment by mayer79** [comment]
Hi guys

Great ideas you are working on. One question: When fine tuning existing models like Inception V3, there is also a preprocessing_input function that cares about appropriate rescaling and centering. This is typically done as the last step of input preparation. How does this fit in your framework? Would it even be possible to have "preprocess_function" (applied before resizing) and "postprocess_function" (applied as final step)?

**Comment by datumbox** [comment]
@ozabluda I confirm this is a side effect of this PR. The preprocessing function is supposed to receive and return numpy arrays not Image Objects. There are more side-effects explained here: https://github.com/keras-team/keras/commit/738819de0b7e6bc45abed8d0640f02b81c6ac4e9

**Comment by kmader** [comment]
This seems to be a massive issue, all the pretrained networks are unusable with the image generator? https://github.com/keras-team/keras/issues/9624

**Comment by datumbox** [comment]
@kmader Indeed, it was agreed to rollback the change.

You can read more on the details here: https://github.com/keras-team/keras/commit/738819de0b7e6bc45abed8d0640f02b81c6ac4e9

I guess this PR will be reverted soon.

**Comment by ink1** [comment]
v2.1.5 is not fully satisfactory. It describes preprocessing_function as
```
            The function should take one argument:
            one image (Numpy tensor with rank 3),
            and should output a Numpy tensor with the same shape.
```
but _get_batches_of_transformed_samples uses it on image and expects image to be returned (to be used in img.resize). Either the doc or the code has to be fixed.

I do all the preprocessing in my own preprocessing_function which does cropping and image normalisation. It looks to me that doing this at the very beginning is the best and I wish I could totally bypass Keras preprocessing if I want. As of 2.1.5 I can't because target_size is not allowed to be None.

I agree with @datumbox that the expected action of preprocessing_function should be maintained compatible with keras.applications.imagenet_utils.preprocess_input but in 2.1.5 it is not.

**Comment by tonmoyborah** [comment]
Is this issue resolved? I get different answers when I use `preprocess_input` of pretrained networks of `keras.applications` and when I use `_get_batches_of_transformed_samples` without the preprocess. The second one seems to be the correct one, the first gives skewed predictions which I fail to understand.

**Comment by crearo** [comment]
Nope. I've made a gist [here](https://gist.github.com/crearo/5c702bf40d8df1f888108c22e0291ed1) to demonstrate this issue. It sucks!

**Comment by joshinkumar** [comment]
Is this bug corrected yet? Reading the current documentation of preprocessing_function seems like it is not. (https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/ImageDataGenerator)

Is there a workaround to this bug? 

I need to apply the preprocessing function first to make my images square after filling them with empty spaces on the edges and then resize them.

**Pull request merged**
