### PR TITLE
Make model summary wrap

### PR DESCRIPTION
**Pull request by Llamrei**
Moved from https://github.com/tensorflow/tensorflow/pull/47439

### CODE REVIEW

**Comment by Llamrei** [comment]
@deeb02 Hope this is ok!

**Comment by fchollet** [comment]
Thanks for the PR -- can you provide screenshots demonstrating the purpose of the change?

**Comment by Llamrei** [comment]
Sure thing! I wrote this as part of doing some research, trying out BERT, and noticed that when I recorded my summaries a lot of them were less than ideal for comparing models as they had character limits in columns meaning I couldn't differentiate apart architectures at a quick glance (without loading up models and inspecting them):

**Before**
image

So digging a bit into the code I re-implemented some basic logic to make it so columns wrapped, as in this PR:

**After**
image

As noted in the linked PR above, although the neatness of `connected_to` decreases I think it still adds a benefit as now layers with long names that are connected to are no longer truncated and thus the original purpose of this proposal - to make sure the summary presents all the information it has access to - is fulfilled.

I considered adding logic for handling lists/dictionaries whilst being aware of key/entry string lengths for an optimal presentation but I figured the value add would be low relative to added complexity in the code?

**Comment by fchollet** [comment]
Thanks -- I think the change looks good. Could you please decrease the column content length by 1 so that we have an additional space between the output shape column and the param count column, to improve readability?

> I considered adding logic for handling lists/dictionaries whilst being aware of key/entry string lengths for an optimal presentation but I figured the value add would be low relative to added complexity in the code?

You could simply force a line break after any `),`, `],`, or `},`, that would be simple.

**Comment by Llamrei** [comment]
> Thanks -- I think the change looks good. Could you please decrease the column content length by 1 so that we have an additional space between the output shape column and the param count column, to improve readability?
> 
> > I considered adding logic for handling lists/dictionaries whilst being aware of key/entry string lengths for an optimal presentation but I figured the value add would be low relative to added complexity in the code?
> 
> You could simply force a line break after any `),`, `],`, or `},`, that would be simple.

Ahh yes - cant believe that didnt cross my mind. Will do so!

**Comment by Llamrei** [comment]
Implemented change, see attached for screenshot of new presentation.
Screenshot from 2021-07-07 11-38-48

**Review by fchollet — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
