### PR TITLE
K.rnn multiple inputs/outputs

### PR DESCRIPTION
**Pull request by andhus**
### Summary
Solution suggestion for https://github.com/keras-team/keras/issues/11501 for tensorflow backend. 

### PR Overview
- [y] This PR requires new unit tests [y/n] (make sure tests are included)
- [y] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [y] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by andhus** [comment]
Sounds great! So the api extension suggestion makes sense then? Should docs/official api be updated for the fully general case? Is that likely to be supported for the other backends?

**Comment by ahundt** [comment]
It seems a fair number of items like this probably exist but could be easier to discover in the [tf.keras docs](https://www.tensorflow.org/guide/keras). For example, I don't see something like "arbitrarily nested rnn inputs" on that page. I believe there could be more explanation of the parts that are designed to work together beyond what is on the linked page and in the regular keras docs.

**Comment by fchollet** [comment]
> Should docs/official api be updated for the fully general case?

Yes, that would make sense.

> Is that likely to be supported for the other backends?

Yes, albeit that would require some work. This feature should be completely orthogonal to actual execution, so it can be supported in all backends.

**Comment by andhus** [comment]
So what's the best way to proceed?
1) Is it already decided that this is something we want?
2) Will it be ok to merge support in one backend (tensorflow) before others - or all or nothing?
3) We will basically need a large part of the logic in the [tensorflow nest module](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/util/nest.py) to add support for general nested structures in other backends, but we don't want to depend on tensorflow for other backends, what's the best way to port this?
4) Is it better to **start with** officially supporting _lists of inputs and outputs_ as per my API doc?

**Comment by gabrieldemarmiesse** [comment]
I think I found a way to remove this global variable from `K.rnn`. Let me look into it and then do a PR to tf.keras.

**Comment by gabrieldemarmiesse** [comment]
Closing this issue because we believe the path forward is to use `tensorflow.keras.backend.rnn` for the implementation of this function.

**Pull request closed without merging**
