### PR TITLE
Added two new correlation metrics, Pearson and Concordance Correlation Coefficients.

### PR DESCRIPTION
**Pull request by mostafa-mahmoud**

### CODE REVIEW

**Comment by mostafa-mahmoud** [comment]
@fchollet I resolved the naming comment. Do you have an idea about the error in the torch tests? It doesn't seem to be related to my code at all, and actually, this test passed in the early commits in this PR and then suddenly appeared in the last 2 commits.

**Comment by nicolaspi** [comment]
> @fchollet I resolved the naming comment. Do you have an idea about the error in the torch tests? It doesn't seem to be related to my code at all, and actually, this test passed in the early commits in this PR and then suddenly appeared in the last 2 commits.

I am facing the same problem. This indicates an issue with the backend?

**Comment by fchollet** [comment]
Looks challenging to debug since we have no indication where the infringing code might be. Not directly related though. Might be triggered by a new dependency version.

**Review by fchollet — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
