### PR TITLE
Fix error when labels contains brackets when plotting model

### PR DESCRIPTION
**Pull request by cBournhonesque**
Relevant issue: https://github.com/keras-team/keras/issues/15795

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
Thanks for the PR!

**Comment by fchollet** [comment]
Please fix code formatting (apply `black` formatting to the edited files).

**Comment by gbaned** [comment]
@cBournhonesque Can you please check @fchollet's comments and keep us posted ? Thank you!

**Comment by cBournhonesque** [comment]
Sorry, missed that. Sure, applied `sh shell/format.sh` !

**Review by fchollet — APPROVED** [review]

**Pull request merged**
