### PR TITLE
Fix dirty progress bar when callbacks print something

### PR DESCRIPTION
**Pull request by taehoonlee**
This PR fixes dirty progress bar described in "Requests for Contributions" (`When callbacks print something to stdout in on_epoch_end, this messes with the output of the progress bar in verbosity mode 1`). The idea is capture the stdout, store them temporarily, and flush them later to make the results of `ProgbarLogger` in the last order (refer to the attached).

results)

### CODE REVIEW

**Comment by taehoonlee** [comment]
@fchollet, I don't think the issue has been fixed yet, or am I addressing another issue? The results of the current master branch are:
results_master

**Comment by fchollet** [comment]
@taehoonlee this issue seems specific to Jupyter notebooks. Try it in a terminal, it should work.

**Comment by taehoonlee** [comment]
@fchollet, The results are the same even in a terminal. I tested with my Mac and a Ubuntu server. I'll check the cause and let you know.

results_terminal

**Comment by fchollet** [comment]
This is what I get with various systems, when printing "some content" on epoch end.

screen shot 2018-02-11 at 10 01 39 pm

This is what I get on batch end:

screen shot 2018-02-11 at 10 03 27 pm

**Comment by taehoonlee** [comment]
@fchollet, You mean that the `on_batch_end` is inevitable to get dirty so not an issue right now. Closed.

**Pull request closed without merging**
