### PR TITLE
add dirname to fashion mnist dataset

### PR DESCRIPTION
**Pull request by weiyinfu**
Fashion mnist dataset‘s path is written in the program and cannot be configed by programmer.

### PR Overview

- [ ] This PR requires new unit tests [y/n] (make sure tests are included)
- [ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [ ] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
What is your use case? Why do you need this to be configurable?

**Comment by weiyinfu** [comment]
Because I have downloaded this dataset in other project. And I put all the datasets in my /home/data path to save disk space . Many project can share one dataset .

**Comment by weiyinfu** [comment]
Maybe I should create an issue rather than a pull request.
So you can close this pull request.

**Comment by gabrieldemarmiesse** [comment]
I think the right solution for you is to use a symbolic link since you are using linux. That will be much easier to do.

**Comment by weiyinfu** [comment]
But other datasets under the package `keras.datasets` has a load_data function which has a ·path· parameter. The fashion mnist dataset is the only special case .
So I think the better way is to give freedom to users to config where to put the downloaded data .
```python
(x_train, y_train), (x_test, y_test) = reuters.load_data("/data/reuters.npz",num_words=max_words,test_split=0.2)
```

**Comment by weiyinfu** [comment]
fashion mnist is different from other dataset, it's very ugly.
And I cannot think up why don't give freedom to users.
```python

def load_data():
    """Loads the Fashion-MNIST dataset.

    # Returns
        Tuple of Numpy arrays: `(x_train, y_train), (x_test, y_test)`.
    """
    dirname = os.path.join('datasets', 'fashion-mnist')
    base = 'http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/'
    files = ['train-labels-idx1-ubyte.gz', 'train-images-idx3-ubyte.gz',
             't10k-labels-idx1-ubyte.gz', 't10k-images-idx3-ubyte.gz']

```

**Comment by gabrieldemarmiesse** [comment]
I see what you mean. It's true that it's inconsistent. I'll open this issue again and will let @fchollet review it since he's responsible for all changes in the API.

**Comment by gabrieldemarmiesse** [comment]
I can't open the pull request again. Did you deleted your fork of keras?

**Comment by gabrieldemarmiesse** [comment]
No problem. I don't think you need to create an issue. You can make a pull request directly.

**Pull request closed without merging**
