### PR TITLE
feature(topology): connect two layers

### PR DESCRIPTION
**Pull request by j-o-d-o**
Function to connect two layers, even if they are from different models. 

I find, that the current API is not very flexible and intuitive when it comes to merging and concatenating parts of two or more different models. I have situations where I want to load different base models and different encoders and connect these models. Sometimes I want to get rid of some layers or want to change an Input of some merge layer to use some layer from another model etc... This function helped me to archive these things. 

A current limitation is, that I haven't figured out how to handle shared layers that are descendants of the connecting layer. If anyone has a solution for that, feel free to update.

### CODE REVIEW

**Comment by fchollet** [comment]
I don't understand the use case, and I can't imagine that too many people could figure out what this function does or how it could be useful to them, either from reading the docstring, code, or unit tests. But if you explain to me what you were trying to do (in terms of model-building), I can show you how to handle it with the functional API.

**Comment by j-o-d-o** [comment]
I created a gist: https://gist.github.com/j-o-d-o/e1e8831bde3784a9583da8445edc8584

It shows how to add a second branch to an existing model using another already existing model. I could not find a way to do this with the current API. 
Using the __call__ method of the Model class was the only way I found to merge two models. But I couldn't find a way to cut layers in the beginning.

**Comment by fchollet** [comment]
Ok, I think what you are trying to do is the following:

```python
branch_input = base_model.get_layer('split_base').output
branch_output = branch_model(branch_input)
all_outputs = [base_model.output] + [branch_output]
new_model = Model(base_model.input, all_outputs)
```

Correct?

**Comment by j-o-d-o** [comment]
Correct me if I am wrong. But that will put the whole branch_model after the Dropout Layer of the base model, including all the previous layers of the branch model and that will only fit if I use a layer with the same shape as the Input of the branch_model and is not want I have in mind. 
Building the model fails if using the Flatten or Dense Layers as input to the branch_model. If using the Conv Layers, building the model works, but training fails with an error about non matching stack sizes for images and kernel. (Theano backend)
If not a new function, an additional argument to the \_\_call__() method of the Container class would be nice. For example: 
```python
# "branch_split" being the layer name where branch_input should be the input to
branch_output = branch_model(branch_input, "branch_split")
```

**Pull request closed without merging**
