### PR TITLE
Use local RandomState instead of seeding the global RNG

### PR DESCRIPTION
**Pull request by YuriyGuts**
### Summary

According to [NumPy NEP 19 — Random Number Generator Policy](https://www.numpy.org/neps/nep-0019-rng-policy.html), instantiating local `RandomState` objects is preferred, rather than seeding the global `np.random` generator.

Seeding the global generator may introduce unexpected behavior in the applications that use Keras and also rely on its state.

Proposed change: use a local `RandomState` object in dataset loaders and the Orthogonal initializer.

### Related Issues

https://github.com/keras-team/keras/issues/12258

### PR Overview

- [x] This PR requires new unit tests [y/n] (make sure tests are included)
- [ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by vikua** [comment]
I don't know how we ended up in situation with two similar PRs. What I usually do is I search for similar PRs which haven't been merged yet before contributing, and if there are some - I either suggest changes to those or create a new PR with non-overlapping changes. 
Otherwise it is a funny strategy - find some PR in OSS repo, create a new one with some improvements, profit ¯\_(ツ)_/¯
But, considering the fact that this PR is a superset of #12232  I can close mine to get things done.

**Comment by zachmayer** [comment]
Looks like https://github.com/keras-team/keras/pull/12232 was closed in favor of this one

**Comment by ConcurrencyPractitioner** [comment]
Oh hi. I just want to point out something regarding this PR. In ```keras/engine/training_arrays.py```,  a method, ```batch_shuffle```, is called repetitively in a loop where it sets a seed before shuffling. My suggestions is that we add an extra seed parameter to the ```fit_loop``` method which calls ```batch_shuffle``` so that we only need to seed once using a local RandomState and then use this instead when invoking ```np.random.shuffle```.

**Comment by ConcurrencyPractitioner** [comment]
```
diff --git a/keras/engine/training_arrays.py b/keras/engine/training_arrays.py
index 466dd6bf..c7029682 100644
--- a/keras/engine/training_arrays.py
+++ b/keras/engine/training_arrays.py
@@ -32,7 +32,8 @@ def fit_loop(model, fit_function, fit_inputs,
              initial_epoch=0,
              steps_per_epoch=None,
              validation_steps=None,
-             validation_freq=1):
+             validation_freq=1,
+             seed=113):
     """Abstract fit function for `fit_function(fit_inputs)`.

     Assumes that fit_function returns a list, labeled by out_labels.
@@ -143,6 +144,8 @@ def fit_loop(model, fit_function, fit_inputs,
             model._feed_targets +
             model._feed_sample_weights)
     indices_for_conversion_to_dense = []
+    rng = np.random.RandomState(seed)
+
     for i in range(len(feed)):
         if issparse(fit_inputs[i]) and not K.is_sparse(feed[i]):
             indices_for_conversion_to_dense.append(i)
@@ -180,7 +183,7 @@ def fit_loop(model, fit_function, fit_inputs,
             if shuffle == 'batch':
                 index_array = batch_shuffle(index_array, batch_size)
             elif shuffle:
-                np.random.shuffle(index_array)
+                rng.shuffle(index_array)

             batches = make_batches(num_train_samples, batch_size)
             for batch_index, (batch_start, batch_end) in enumerate(batches):
``` 

Just my diff for my suggestion.

**Comment by farizrahman4u** [comment]
@ConcurrencyPractitioner can you make that a PR please?

**Pull request merged**
