### PR TITLE
Enable distribution test

### PR DESCRIPTION
**Pull request by SamanehSaadat**
Enabling `distribution_lib_test` to ensure we continuously test our distribution logic. We need this more than before as with larger Gemma models, there is a higher interest in distributed training and inference.

### CODE REVIEW

**Comment by SamanehSaadat** [comment]
Tests were successful locally! I'll look into why they're failing here!

**Comment by fchollet** [comment]
It seems this causes a JAX test to start failing: https://btx.cloud.google.com/invocations/47bbb2b9-2dfd-4350-82d7-04474c8df10b/targets/keras%2Fgithub%2Fubuntu%2Fgpu%2Fjax%2Fpresubmit/log

Can you try unbundling the distribution test command?

**Comment by SamanehSaadat** [comment]
Thanks, Francois! Separating the distribution tests resolved the issue!

**Review by fchollet — APPROVED** [review]
LGTM, thank you!

**Review by mattdangerw — APPROVED** [review]
Nice! LGTM!

**Pull request merged**
