### PR TITLE
Add security policy

### LINKED ISSUE #18761: Add Security Policy
(A similar issue was sent to the previous incarnation of keras-team/keras, before the changes for Keras 3: https://github.com/keras-team/keras/pull/18385#issuecomment-1721833046)

A security policy (SECURITY.md) explains how the project wishes to receive and handle responsible disclosure of potential vulnerabilities. GitHub has special treatment for this file: it can be found by users who enter the project's "Security" panel and users will also see references to it in the "New issue" page.

Is the [security policy used in /tf-keras](https://github.com/keras-team/tf-keras/blob/master/CONTRIBUTING.md#security-vulnerability-reports) reasonable for /keras as well?

If not, then there are two main ways to receive disclosures:
- register an email or website available to receive such reports; and/or
- use [GitHub's private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository)

If you want to use GitHub's reporting system, it must be activated for the repository:
1. Open the repo's settings
2. Click on [Code security & analysis](https://github.com/WebAssembly/wabt/settings/security_analysis)
3. Click "Enable" for "Private vulnerability reporting"

I'll send a PR with the tf-keras policy along with this issue.

Alternatively, the policy can be created in the [keras-team/.github](https://github.com/keras-team/.github) repository. In this case, the policy will be available in all of the org's repos. (I unfortunately can't send a PR there since the repo is empty)

### PR DESCRIPTION
**Pull request by pnacht**
Fixes #18761.

This PR adds a security policy to keras-team/keras. It is currently the same one used in /tf-keras. If you'd rather use something else, let me know.

### CODE REVIEW

**Comment by fchollet** [comment]
The statement "Since Keras is the high-level API of TensorFlow 2, Keras follows the same security practices as TensorFlow" is no longer applicable since Keras is now fully independent from TensorFlow. We should come up with our own security policy.

**Comment by pnacht** [comment]
I've pushed a new policy unrelated to Tensorflow. It now suggests two different, possible methods:

- sending an email. The only email I could find was from the [announcement blogpost](https://keras.io/keras_core/announcement/), let me know if there's a better one!
- using GitHub's [private vulnerability report](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability) feature. Note that this feature needs to be enabled in the repository settings:
  1. Settings > [Code security & analysis](https://github.com/pnacht/cronk/settings/security_analysis)
  2. Enable Private Vulnerability Reporting

Let me know if you'd rather use one or the other or make any other changes to the policy.

**Review by fchollet — APPROVED** [review]
Thanks for the update!

> sending an email. The only email I could find was from the [announcement blogpost](https://keras.io/keras_core/announcement/), let me know if there's a better one!

I think it's not ideal to list my own email, but also we don't have a public-facing team email (the one we have is internal-facing only), so let's go for it for now.

**Comment by pnacht** [comment]
@fchollet, thanks for merging this PR!

However, since you kept it as an option, please remember to also enable the private vulnerability reporting feature in the repo's [Code security & analysis settings](https://github.com/keras-team/keras/settings/security_analysis).

**Pull request merged**
