### PR TITLE
Convert input data into DTensor

### PR DESCRIPTION
**Pull request by hubingallin**

### CODE REVIEW

**Comment by qlzh727** [comment]
Since Bing move to a new team,  I will take the PR from here.

**Comment by hubingallin** [comment]
Context: the PR has failed tests when tests running together, but will pass when running separately. Synced offline with Scott about the issue and the error log, will leave the PR for Scott

**Comment by gbaned** [comment]
Hi @hubingallin Can you please resolve conflicts? Thank you!

**Comment by qlzh727** [comment]
I will close this PR for now, since Bing is working on some other projects.

**Pull request closed without merging**
