### PR TITLE
Added identity layer

### PR DESCRIPTION
**Pull request by AdityaKane2001**
@fchollet 

Please see #17251.

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
LGTM, thanks

**Comment by AdityaKane2001** [comment]
@fchollet 

Resolved the CI build error. Please run the workflow again.

**Review by fchollet — APPROVED** [review]

**Comment by AdityaKane2001** [comment]
@fchollet 

Not sure what's causing the build to fail. Here's the error:
```
ImportError: cannot import name 'layers' from partially initialized module 'keras' (most likely due to a circular import) (/home/kbuilder/.cache/bazel/_bazel_kbuilder/31d6f47147b75c35404d734345be7323/execroot/org_keras/bazel-out/k8-opt/bin/keras/utils/data_utils_test.runfiles/org_keras/keras/__init__.py)
```

*_All_* tests failed with this error.

**Comment by fchollet** [comment]
I have re-applied the change. One modification I had to do is to apply a `tf.identity()` op in the call method.

**Comment by AdityaKane2001** [comment]
@fchollet Thanks a lot for the follow up. Really nice of you to keep me in the loop. Thoroughly appreciate it.

**Pull request merged**
