### PR TITLE
Add options for graphing model and saving model graph  (True or False) in plot_model

### PR DESCRIPTION
**Pull request by SriRangaTarun**
### Summary
I added the 'show' and 'save' parameters to the plot_model function (see the docs for description)

### Related Issues
None

### PR Overview

- [y] This PR requires new unit tests [y/n] (make sure tests are included)
- [y] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [y] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by fchollet** [comment]
Thank you for the PR. What would be the use case for the new arguments?

**Comment by SriRangaTarun** [comment]
@fchollet People may not always want to save the graph created by plot_model; they might just want to see it displayed. Also, some people might want to save the graph for later use and not display it directly. The current implementation leaves the user no option but to display the graph and save it.

**Comment by SriRangaTarun** [comment]
@fchollet If possible, can you remove the import I added in engine/training.py ? I deleted my branch by mistake.

**Comment by fchollet** [comment]
I don't think this is relevant in this context because:

- pydot offers no other option but to save the image we create, so we'll always save the image. It wouldn't make sense to have both `to_file="img.png"` and `save=False` at the same time.
- returning a Jupyter Image object is not necessarily for showing the image (show=True), you might want to get the Image object and post-process it (a common thing would be to resize it). In any case returning the Image object whenever possible (when Jupyter is installed) always seems like a good idea.

**Pull request closed without merging**
