### PR TITLE
Fix undefined behaviour: preprocess_input copying/not copying the input arrays

### PR DESCRIPTION
**Pull request by vkk800**
Before, `preprocess_input` would sometimes write over images it processed. Inadvertently, my commit (https://github.com/keras-team/keras/commit/84e168b5fa55933e02e767ff7c86fcc0232aecc6) from two days ago changed this so that instead of the previous behaviour, preprocess_input would always make a new copy of the input images to work with. This seems, to me, more intuitive behaviour.

This PR gives the user explicit control over the behaviour by introducing `copy` keyword argument to the relevant functions. This way, the earlier behaviour can be regained if the user so wishes. Also, it fixes my earlier commit so that the dtype of the input array is not changed unless necessary (i.e. when inputting other than float arrays).

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR.

I think in general the correct behavior is to modify the inputs in-place, because 99% of the time, feeding your network is the only thing you're doing with these inputs. And in that case making a copy has a significant performance cost.

We can make it an argument (defaulting to `False`), but I don't think that's necessary. Rather we should just explicitly document in the docstring that the function modifies its inputs in place.

Thoughts?

**Comment by vkk800** [comment]
@fchollet  Why I noticed this was because I was writing a Jupyter notebook where in one cell I had something like this:
`preds = model.predict(preprocess_input(imgs))`
The predictions were correct when I ran the notebook for the first time, but if I tried to run this cell again, the predictions would come out incorrectly (since the `preprocess_input` was applied to them twice). Also trying to plot the original images after predicting on them resulted in distorted pictures. I think this behaviour is somewhat confusing; at least I spent a good while figuring out what was wrong.

I did some tests about the performance and probably the biggest problem with copying the images is the doubled memory cost, which can be a problem when processing large images (or large batches).

I feel like there is a use case for both copying and not copying the results so I would suggest leaving the option there and setting the default to `False`.

**Comment by fchollet** [comment]
When, as user, what would be the best UX:

1) search for it, and maybe find about the `copy` argument, and write:

```
preds = model.predict(preprocess_input(imgs, copy=True))
```

2) don't search for it, and just do:

```
preds = model.predict(preprocess_input(np.copy(imgs)))
```

In my opinion 2) is preferable, and doesn't clutter the API. Don't introduce built-in APIs for things that are simple enough with the existing tools.

**Comment by vkk800** [comment]
@fchollet Alright maybe this makes sense. I made a new commit that reverts some of the changes. A new array is, however, still created when the input array has dtype other than `float` and that dtype can't be cast to `float` without allocating a new array (I trust `numpy.ndarray.astype()` to know when this is possible).

There is one more ugliness left, though: with `mode='caffe'`, the return value is a view to the input with the channels reversed and the channels in the original input are left unreversed (but the std and mean shifts are applied). This is because it's impossible to reverse the channels in-place without creating an auxiliary variable that would again lead to a decrease in performance.

**Comment by fchollet** [comment]
> This is because it's impossible to reverse the channels in-place without creating an auxiliary variable that would again lead to a decrease in performance.

This seems inevitable. I don't think it's a big issue.

**Pull request merged**
