### PR TITLE
Breaking down the attention API PR: part 1

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
### Summary

I believe that it will be simpler to merge #8296 by breaking it down into indépendant, small PRs as much as possible. Here is the first one.

### PR Overview

- [ ] This PR requires new unit tests [y/n] (make sure tests are included)
- [x] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by farizrahman4u** [comment]
If there is some git magic we could do to assign commits to the original author for upcoming PRs that would be great.

**Comment by gabrieldemarmiesse** [comment]
Indeed, that'd be nice! Do you know how to? I can try to look it up.

**Comment by gabrieldemarmiesse** [comment]
I just found how. `git commit --author="Author Name <email@address.com>"`. I'll do it for the next commits.

**Comment by fchollet** [comment]
Please keep in mind that I should approve all API changes before merging (which this PR includes).

**Pull request merged**
