### PR TITLE
fix ALLOWED_DTYPES to include complex dtypes

### PR DESCRIPTION
**Pull request by IslamAlam**
This adds support to handle complex `dtypes` for `complex64` `complex128`

### CODE REVIEW

**Comment by IslamAlam** [comment]
> What is the use case for this? Basically none of the Keras APIs support complex dtypes.

@fchollet Thanks for your question! In my Ph.D. research on Physics-informed Machine Learning, I integrate complex coherence equations from InSAR with trainable layers to predict certain physical model assumptions. Complex dtype support is essential for accurately processing this complex coherence data within the machine learning framework. If you have any more questions or suggestions, feel free to ask. Your feedback is valuable!

Here is a simple graph of the model:
image

**Comment by fchollet** [comment]
My main concern here is that virtually all Keras ops have no support for complex dtypes, so you can't do much with them. Instead, if you try to use them, they will get casted to float, which is not what the user expects and can lead to silent bugs.

> Complex dtype support is essential for accurately processing this complex coherence data within the machine learning framework.

Could you simply pass around the real and imaginary parts of your complex tensor as two separate tensors? Your layers would take two inputs, e.g. instead of `def call(self, inputs)` you'd have `def call(self, real, imaginary)`.

**Comment by IslamAlam** [comment]
Thank you for sharing your concerns! I've taken them into account by adding support for complex data types in Keras operations and ensuring that corresponding test cases are included.

Regarding your suggestion, I've actually implemented a workaround similar to what you proposed, and it seems to be working alright. However, I believe incorporating direct support for complex data types in Keras would provide a more solid foundation for users who might need it in the future. Appreciate your input!

**Comment by fchollet** [comment]
> Regarding your suggestion, I've actually implemented a workaround similar to what you proposed, and it seems to be working alright. However, I believe incorporating direct support for complex data types in Keras would provide a more solid foundation for users who might need it in the future. Appreciate your input!

Adding true complex dtype support in Keras would be a large project -- we'd have to make sure that all relevant ops support these new dtypes. Until that's possible, we believe it would be better to leave these dtypes as unsupported. Adding these dtypes creates expectations that the framework cannot fulfill.

**Pull request closed without merging**
