### PR TITLE
refactor with tf ops

### PR DESCRIPTION
**Pull request by fsx950223**
I removed tf-idf tensor assignment which is not recommended in official guide.

### CODE REVIEW

**Comment by mattdangerw** [comment]
Thanks! This looks like a nice simplification. Can I ask what official guide/section you are referring to?

**Comment by fsx950223** [comment]
https://www.tensorflow.org/guide/effective_tf2#do_not_keep_tftensors_in_your_objects

**Comment by mattdangerw** [comment]
Got it. Yeah that note does not fully apply here as we are trying to avoid any tf variable usage inside our tf functions to avoid problems with tf.data + the full range of distribution strategies.

But I still think the cleanup looks good (thanks!). Approving for now. Will make sure this does not break any distribution testing we have internally.

**Review by mattdangerw — APPROVED** [review]

**Comment by mattdangerw** [comment]
Actually I have tested this out more, and sadly I don't think we can land it. The whole point of all these lines transforming a `tf.variable` to a const tensor is to avoid the variable getting picked up in function tracing. There are some environments (mainly distributing with ParameterServerStrategy and applying these layers with tf.data IIRC), where we don't can't have any variable in the function trace.

Here's a quick colab showing the proposed approach would indeed result in variable reads in the function trace:
https://colab.sandbox.google.com/gist/mattdangerw/dbd9164633ffe838957fa6e8f85c0a00/variable-tracing.ipynb

Ideally we wouldn't have to do any of this, and non-trainable variables would just work in all distributions strategies as you would expect. But for now I think we have to keep this indirection, so we calculate our const tensors before tracing the function, and only access those const tensors during call. Not ideally, but where we are at!

**Pull request closed without merging**
