### PR TITLE
Flash attention support.

### PR DESCRIPTION
**Pull request by hazemessamm**
I added support for flash attention for PyTorch.

Let me know what do you think about this current implementation so I can add support for JAX and maybe will try for TF.

### CODE REVIEW

**Review by fchollet — COMMENTED** [review]
Thanks for the PR -- the code looks good! Please add a unit test.

For the JAX version, I think we'd want to rely on a Pallas kernel. We can get help from the JAX team.

**Comment by hazemessamm** [comment]
Hey, sorry for not finishing this PR, I have a quick question, where should I add the tests?

**Comment by fchollet** [comment]
> Hey, sorry for not finishing this PR, I have a quick question, where should I add the tests?

In `keras/src/ops/nn_test.py`. Ops are tested through the op class in e.g. `keras/src/ops/nn.py`, rather than in a backend specific way.

**Comment by fchollet** [comment]
@james77777778 do you think flash attention should be a standalone op, or could this be managed at the level of the dot_product_attention op (e.g. as an argument)?

**Comment by james77777778** [comment]
> @james77777778 do you think flash attention should be a standalone op, or could this be managed at the level of the dot_product_attention op (e.g. as an argument)?

It should be possible to consolidate this into `dot_product_attention`. That’s how it's implemented in torch, and I've seen a similar approach in jax
(https://github.com/jax-ml/jax/blob/81a31f6adf453b2afc39936e15c15d8ad327bf6e/jax/_src/nn/functions.py#L1037-L1041)

As far as I know, for torch, flash attention is utilized if the conditions are met. For jax, we need to specify `implementation="cudnn"` to use it.

**Comment by fchollet** [comment]
Very cool -- @hazemessamm can we do that, e.g. by adding a `flash_attention` argument in `dot_product_attention`? This makes it quite easy to also add support for JAX ( in addition to PyTorch). For TF I think we can skip support for now.

**Review by fchollet — APPROVED** [review]
Awesome work! Thank you.

**Comment by hazemessamm** [comment]
> Awesome work! Thank you.

Thank you, glad I could help.

**Comment by fchollet** [comment]
The test fails on torch + GPU:

> FAILED keras/src/ops/nn_test.py::NNOpsCorrectnessTest::test_dot_product_attention_none_none_(true, false)_true - RuntimeError: No available kernel. Aborting execution.

Do you know if this is an issue with the torch version? What version is required? What torch + GPU setup were you testing on?

**Comment by hazemessamm** [comment]
> The test fails on torch + GPU:
> 
> 
> 
> > FAILED keras/src/ops/nn_test.py::NNOpsCorrectnessTest::test_dot_product_attention_none_none_(true, false)_true - RuntimeError: No available kernel. Aborting execution.
> 
> 
> 
> Do you know if this is an issue with the torch version? What version is required? What torch + GPU setup were you testing on?

I think PyTorch does not support any dtype with flash attention except float16, I think thats the reason why it throws this exception, we can avoid it if we set the dtype of the inputs to float16 when flash attention is enabled. What do you think?

**Comment by hazemessamm** [comment]
> The test fails on torch + GPU:
> 
> > FAILED keras/src/ops/nn_test.py::NNOpsCorrectnessTest::test_dot_product_attention_none_none_(true, false)_true - RuntimeError: No available kernel. Aborting execution.
> 
> Do you know if this is an issue with the torch version? What version is required? What torch + GPU setup were you testing on?

I think flash attention in PyTorch does not work with any dtype except float16 and on specific GPUs, I just tested it on H100 GPU and it worked fine but it did not work on T4 GPU on Colab.

I also just found the following functions in PyTorch that we can use to check whether the inputs and the current GPU can use flash attention or not.

```python
import torch
bsz, num_heads, seqlen, head_dim = 1, 2, 10, 16
query = torch.randn((bsz, num_heads, seqlen, head_dim), dtype=torch.float32, device='cuda:0')

params = torch.backends.cuda.SDPAParams(query, query, query, None, 16**0.5, False)
is_flash_attention_enabled = torch.backends.cuda.can_use_flash_attention(params, False)
```

If you think that this is a good idea then I will use this snippet in the flash attention function in PyTorch backend.

Documentation:
https://pytorch.org/docs/stable/backends.html#torch.backends.cuda.SDPAParams
https://pytorch.org/docs/stable/backends.html#torch.backends.cuda.can_use_flash_attention

**Comment by fchollet** [comment]
> If you think that this is a good idea then I will use this snippet in the flash attention function in PyTorch backend.

That sounds great! Then, we can also skip the PyTorch unit test when this check evaluates to False.

**Review by fchollet — APPROVED** [review]
Looks good, thank you! Can you also add the test back? You can use `pytest.mark.skipif` to skip when unimplemented for PyTorch for TF.

**Comment by hazemessamm** [comment]
I skipped the tests for TensorFlow, NumPy and torch and I just tested it not JAX on T4 GPU on colab and I got this error: `RuntimeError: Require at least Ampere arch to run`, so we will need JAX + GPU tests to run on Ampere arch otherwise we will need to skip the tests for all frameworks.

**Comment by hazemessamm** [comment]
I added some conditions for JAX to skip the tests if they were met, what do you think?.

**Review by fchollet — APPROVED** [review]

**Pull request merged**
