### PR TITLE
Applications: Updated f-string methods in all possible scripts

### PR DESCRIPTION
**Pull request by cyai**

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR.

> Lint / Check the code format (pull_request) Failing after 2m — Check the code format

Please fix.

**Comment by fchollet** [comment]
Please sign the CLA.

**Review by fchollet — APPROVED** [review]

**Comment by fchollet** [comment]
The CLA check is still failure, as well as the code formatting check. Please address.

**Review by qlzh727 — CHANGES_REQUESTED** [review]
Please sign the CLA and run the format script for this PR.

**Comment by gbaned** [comment]
@cyai Can you please check @qlzh727's comments and keep us posted ? Thank you!

**Comment by fchollet** [comment]
The codebase has been reformatted previously. Thanks!

**Pull request closed without merging**
