### PR TITLE
Update example losses to bce- metrics/confusion_metrics.py

### PR DESCRIPTION
**Pull request by Frightera**
I think it is better to use "binary_crossentropy" instead of "mse" as those metrics are for classification purposes.

### CODE REVIEW

**Comment by rchao** [comment]
Gabriel, would you mind taking a look at this change? Thanks.

**Review by grasskin — APPROVED** [review]
Thank you for the PR @Frightera, I agree that the example documentation should be using a classification loss instead - they make more sense for confusion metrics.

**Comment by grasskin** [comment]
Hi @Frightera, would you mind rebasing/updating your branch so we can pass CI checks?

**Comment by Frightera** [comment]
Hi @grasskin, should be fine now.

**Review by grasskin — APPROVED** [review]

**Pull request merged**
