### PR TITLE
Enable `jit_compile=True` for Tensorflow distributed strategies

### PR DESCRIPTION
**Pull request by crohkohl**
Enable jit_compile=True for Tensorflow distributed strategies.

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
LGTM

**Comment by fchollet** [comment]
Tests are failing --

```
E               ValueError: Unknown variable: <KerasVariable shape=(4, 2), dtype=float32, path=my_model/dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
```

**Comment by crohkohl** [comment]
> Tests are failing --
> 
> ```
> E               ValueError: Unknown variable: <KerasVariable shape=(4, 2), dtype=float32, path=my_model/dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
> ```

I cannot find the solution. The `trainable_variables` is empty inside the compile() function for the test case. However, the layers element contains the actual layers. I am confused, probably my knowledge of the internals is too small. Do you have any idea why?

**Comment by fchollet** [comment]
From reading the error message my guess is that the optimizer's `build()` should be called elsewhere. It may be currently called twice.

**Comment by gbaned** [comment]
Hi @crohkohl Can you please resolve conflicts? Thank you!

**Comment by gbaned** [comment]
Hi @crohkohl Can you please resolve conflicts? Thank you!

**Comment by fchollet** [comment]
We've disabled XLA with tf.distribute due to a suspected fundamental incompatibility.

**Comment by kmkolasinski** [comment]
Hi @fchollet, sorry for bringing back this old ticket, I'm trying to track down this issue by reading multiple tickets from the past, however most of them are very old or closed etc. Is there any progress on making `jit_compile=True` working with distributed strategy ? I know that there is some fundamental issue with XLA and Variables in Tensorflow, but maybe you have some updates on this. 

Also we are running older version of tensorflow 2.11 with python 3.8 which works with XLA and multi GPU, we thought to make some updates but we hit this problem recently.

**Pull request closed without merging**
