### PR TITLE
Fixes ConvNeXt and RegNet when input_tensor is given

### PR DESCRIPTION
**Pull request by shanejohnpaul**
Fixes issue https://github.com/keras-team/keras/issues/16990

As mentioned in the comments, RegNet also has this issue so added a fix for both.

### CODE REVIEW

**Review by fchollet — COMMENTED** [review]
Thank you for the PR! Please add a unit test.

**Comment by shanejohnpaul** [comment]
Okay, I'll work on it.

**Comment by shanejohnpaul** [comment]
Could I get some help or refer to some resources on writing unit tests for Keras? I have not written any unit tests.

**Review by fchollet — APPROVED** [review]
Ok, we'll handle on our side then. Thanks!

**Pull request merged**
