### PR TITLE
Add the Precision, Recall and F1 Score metrics in callbacks.py

### PR DESCRIPTION
**Pull request by SriRangaTarun**
### Summary
Add precision, recall and f1 score metrics for binary classification.

### Related Issues
[This issue](https://github.com/keras-team/keras/issues/11846)

### PR Overview
Added precision, recall and f1 score metrics for binary classification in callbacks.py.

- [n] This PR requires new unit tests [y/n] (make sure tests are included)
- [y] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [n] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
Thanks for the PR. When fixing a bug or adding a new functionality, tests helps us maintain your work and make sure it doesn't break in the future. Could you add tests please? Thanks!

**Comment by Dref360** [comment]
A lot of issues with this PR. Please do not open a PR that is not in a good state.
If you need help please go to Slack/StackOverflow/Gitter/Google groups.

Metrics such as Recall or Precision **must** use the StatefulMetric pattern.

I know that @CharlesAuthier is working on this feature as well using StatefulMetrics and should have a PR ready by the end of the week.

**Comment by fchollet** [comment]
We will upgrade the API for handling stateful metrics soon, based on the new API in tf.keras: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/metrics.py

The new API will include built-in support for precision and recall. ETA is probably around January.

**Comment by fchollet** [comment]
(contributions on this feature are super welcome, but please make sure to prioritize porting the new API)

**Comment by Dref360** [comment]
@CharlesAuthier could you modify your work to do something similar the the TF implementation?

**Comment by CharlesAuthier** [comment]
Yep

**Pull request closed without merging**
