### PR TITLE
Fix ModelCheckpoint trained-on batch counting when using steps_per_execution>1

### PR DESCRIPTION
**Pull request by jasnyj**
When setting the steps_per_execution argument to a value N>1 when calling model.compile(), the on_train_batch_end() method of model.fit()'s callbacks only gets called every N batches with an argument batch equal to the 0-indexed index of the last batch which has been trained on. That is, after the first N trained-on batches, on_train_batch_end() gets called with its batch argument equal to N-1, then N trained-on batches later, to 2N-1, etc. until the end of the epoch.

In order to handle this situation, ModelCheckpoint uses a _last_batch_seen member integer variable to record the value of the batch argument of its on_train_batch_end() method the last time this method was called. When on_train_batch_end() is called again, ModelCheckpoint then computes (in its _should_save_on_batch() method) add_batches = batch - self._last_batch_seen in order to know the number of batches which have been trained on between two consecutive calls to its on_train_batch_end() method.

However, the _last_batch_seen member variable is initialized to 0 which means that, when using steps_per_execution=N, the first time on_train_batch_end() is called after N batches have been trained on (with a batch argument equal to N-1), only N-1 batches are counted since add_batches = batch - self._last_batch_seen = (N-1) - 0 = N-1 instead of N. This makes ModelCheckpoint miss one batch when counting them and effectively offset its save_freq contructor argument by 1. Therefore an initialization value of -1 is needed.

In the special cases of steps_per_execution=1 or
steps_per_execution=None (which are equivalent), the bug was hidden by the fact that the condition to check for a new epoch (batch <= self._last_batch_seen) was true since on the first call to on_train_batch_end() both the batch argument and _last_batch_seen variable were equal to 0. In this case, the number of batches trained on is counted by computing add_batches = batch + 1 = 1, which is indeed the correct result.

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR! Please add a unit test for the change.

**Comment by jasnyj** [comment]
I'm new to writing unit tests for Keras. Should I create a new method named like `test_fit_with_ModelCheckpoint_with_steps_per_execution` in the `KerasCallbacksTest` class of the keras/callbacks_test.py file ? I guess I should create a test which fail with the current keras nightly (while obviously being wrong to fail) but works with my change, using asserts to check that the checkpoint was correctly created.

**Comment by fchollet** [comment]
Yes, exactly. You can use a tmp folder for saving the checkpoints (see how it's done in other tests).

**Comment by jasnyj** [comment]
I have just added unit tests which correctly fail without the fix and pass with it.

**Review by fchollet — APPROVED** [review]
LGTM, thank you!

**Comment by gbaned** [comment]
Here are the internal errors, @jasnyj can you please verify ? Thank you!

Traceback (most recent call last):
  File "/py/absl/testing/parameterized.py", line 320, in bound_param_test
    return test_method(self, *testcase_params)
  File "/keras/testing_infra/test_combinations.py", line 291, in decorated
    _test_sequential_model_type(f, self, *args, **kwargs)
  File "/keras/testing_infra/test_combinations.py", line 312, in _test_sequential_model_type
    f(test_or_class, *args, **kwargs)
  File "/keras/callbacks_test.py", line 1762, in test_fit_with_ModelCheckpoint_with_steps_per_execution
    self._run_fit_with_ModelCheckpoint_with_steps_per_execution(
  File "/keras/callbacks_test.py", line 1712, in _run_fit_with_ModelCheckpoint_with_steps_per_execution
    model.compile(
  File "/tensorflow/python/trackable/base.py", line 205, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/py/keras/engine/training_v1.py", line 308, in compile
    raise TypeError(
TypeError: Invalid keyword argument(s) in `compile`: {'steps_per_execution'}

**Comment by jasnyj** [comment]
@gbaned Indeed. The `steps_per_execution` argument to `model.compile(...)` only exists in Keras>=2.4.0. Given the stack trace it seems the test is being executed in v1 mode while it shouldn't as the functionality do not exist in v1. I therefore made the test only run in v2 mode with a `@test_utils.run_v2_only` annotation.

I was however unable to reproduce the error locally (and therefore test if it did go away), `bazel test keras:callbacks_test` doesn't seem to run tests in v1 mode by default in my environment. How can I run tests in v1 mode in the future to catch these errors locally ?

(If you are wondering why I force pushed, it's just that I made the last commit with a wrong email address configured and I had to amend the commit to change it.)

**Comment by gbaned** [comment]
Hi @fchollet Can you please assist on above comments from @jasnyj. Thank you!

**Review by fchollet — APPROVED** [review]
LGTM, thanks

**Pull request merged**
