### PR TITLE
Add random_color_jitter processing layer

### PR DESCRIPTION
**Pull request by shashaka**
I have implemented the RandomColorJitter image processing feature. Please let me know if any further corrections or improvements are required.

here is my [gist](https://colab.research.google.com/drive/1x5fLzop3pWcowPQw38tlRBLpFde_hXzr?usp=sharing)

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
Neat -- thank you for the PR! LGTM

**Comment by fchollet** [comment]
> FAILED keras/src/layers/preprocessing/image_preprocessing/random_color_jitter_test.py::RandomColorJitterTest::test_tf_data_compatibility - AttributeError: 'NoneType' object has no attribute 'assign'

Please take a look.

**Comment by shashaka** [comment]
I have corrected the failed test case. Please let me know if any further corrections are needed.

**Comment by fchollet** [comment]
Thank you!

**Pull request merged**
