### PR TITLE
fix backend _GRAPH_LEARNING_PHASES graph circular reference.

### PR DESCRIPTION
**Pull request by zhjunqin**
The phase cached by backend._GRAPH_LEARNING_PHASES  is a tf.Tensor with attribute 'graph'.
There is a circular reference between key 'graph' and attribute 'graph'.
So we need use a weakref.ref to refer to the tensor phase here.
Otherwise, it would lead to memory leak.

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
Good catch, thanks for the fix!

**Comment by fchollet** [comment]
@zhjunqin there seems to be some test failures. Can you take a look?

**Comment by zhjunqin** [comment]
> @zhjunqin there seems to be some test failures. Can you take a look?

OK, I will check them.

**Comment by zhjunqin** [comment]
> @zhjunqin there seems to be some test failures. Can you take a look?

Fixed, please have a check, thanks.

**Review by fchollet — APPROVED** [review]

**Comment by zhjunqin** [comment]
Seems fail again, I will check again.

BTW. How can I run those check in local?

**Comment by gbaned** [comment]
> Seems fail again, I will check again.
> 
> BTW. How can I run those check in local?

@zhjunqin  You couldn't trigger the checks from your end. Once you completed the verification, please let me know I will trigger checks. Thank you.

**Comment by fchollet** [comment]
> BTW. How can I run those check in local?

Here are the instructions to run unit tests locally: https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md#setup-environment

**Comment by zhjunqin** [comment]
I think I fixed all failed test cases, but there is a test case also failed on master branch.

```
# bazel test keras/saving/saved_model:saved_model_test
```
```
======================================================================
ERROR: test_maintains_losses_test_mode_graph (__main__.TestLayerCallTracing)
TestLayerCallTracing.test_maintains_losses_test_mode_graph
test_maintains_losses_test_mode_graph(mode='graph')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/conda/lib/python3.8/site-packages/absl/testing/parameterized.py", line 314, in bound_param_test
    return test_method(self, **testcase_params)
  File "/conda/lib/python3.8/site-packages/tensorflow/python/framework/test_combinations.py", line 362, in decorated
    execute_test_method()
  File "/conda/lib/python3.8/site-packages/tensorflow/python/framework/test_combinations.py", line 345, in execute_test_method
    test_method(**kwargs_to_pass)
  File "/root/.cache/bazel/_bazel_root/8e0c9e27c4550b3448eb9095c2cd7be4/execroot/org_keras/bazel-out/k8-opt/bin/keras/saving/saved_model/saved_model_test.runfiles/org_keras/keras/saving/saved_model/saved_model_test.py", line 1154, in test_maintains_losses
    self.assertAllEqual(previous_losses, layer.losses)
  File "/conda/lib/python3.8/site-packages/tensorflow/python/framework/test_util.py", line 1447, in decorated
    return f(*args, **kwds)
  File "/conda/lib/python3.8/site-packages/tensorflow/python/framework/test_util.py", line 3112, in assertAllEqual
    a = self._GetNdArray(a)
  File "/conda/lib/python3.8/site-packages/tensorflow/python/framework/test_util.py", line 2856, in _GetNdArray
    return np.array(a)
  File "/conda/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 989, in __array__
    raise NotImplementedError(
NotImplementedError: Cannot convert a symbolic Tensor (layer_with_loss/Sum:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

----------------------------------------------------------------------
Ran 34 tests in 31.662s

FAILED (errors=1)
```

**Review by fchollet — APPROVED** [review]
Thanks for the update! Let's try this again.

**Pull request merged**
