### PR TITLE
Adds show_trainable option to plot_model()

### PR DESCRIPTION
**Pull request by mfidabel**
Fixes missing part of issue #15425 where `model.summary(show_trainable=True)` was implemented but `plot_model(model, show_trainable=True)` wasn't.

Also fixes a failing test case when having pydot & graphviz installed.

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR! Can you provide a few screenshots of what the plots look like?

**Comment by mfidabel** [comment]
> Thanks for the PR! Can you provide a few screenshots of what the plots look like?

Sure, It would look like this:

195469866-dbb40180-f2b7-4b82-8536-32eedeaa59d4

For something like this:

```python
import keras

model = keras.Sequential(
    [
        keras.Input(shape=(230, 230, 3)),
        keras.layers.Conv2D(3, 1),
        keras.layers.MaxPooling2D(2),
        keras.layers.Dense(10),
    ]
)

model.get_layer(index=0).trainable = False

keras.utils.plot_model(
    model,
    to_file="model_trainable.png",
    show_trainable=True,
)
```

Where the Convolutional Layer is the "not trainable" layer.

**Comment by gbaned** [comment]
@fchollet Can you please take a look on the above comment from @mfidabel. Thank you!

**Review by fchollet — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
