### PR TITLE
Fix shape inference in MobileNet v3

### PR DESCRIPTION
**Pull request by shkarupa-alex**
Replace self-written hard_sigmoid with activation layer to solve https://github.com/keras-team/keras/issues/15282

### CODE REVIEW

**Review by nkovela1 — APPROVED** [review]

**Review by nkovela1 — COMMENTED** [review]
This PR is causing breakages with the following tests:

https://github.com/keras-team/keras/blob/master/keras/applications/applications_load_weight_test.py#L180

**Comment by gbaned** [comment]
Hi @shkarupa-alex Can you please check @nkovela1's comments and keep us posted ? Thank you!

**Comment by shkarupa-alex** [comment]
@nkovela1 , could you please share the description and stack trace of test failure you got?

I've made a local dev container as described here https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md
and MobileNetV3-related tests are passed:
```bash
root ➜ /home/keras (patch-2) $ bazel test --test_output=errors //keras/applications:applications_load_weight_test_mobilenet_v3_small
WARNING: The following configs were expanded more than once: [v2]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=243
INFO: Reading rc options for 'test' from /home/keras/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define open_source_build=true --define=use_fast_cpp_protos=false --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --config=short_logs --config=v2
INFO: Reading rc options for 'test' from /home/keras/.bazelrc:
  'test' options: --define open_source_build=true --define=use_fast_cpp_protos=false --config=v2
INFO: Found applicable config definition build:short_logs in file /home/keras/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/keras/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:v2 in file /home/keras/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Analyzed target //keras/applications:applications_load_weight_test_mobilenet_v3_small (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
Target //keras/applications:applications_load_weight_test_mobilenet_v3_small up-to-date:
  bazel-bin/keras/applications/applications_load_weight_test_mobilenet_v3_small
INFO: Elapsed time: 6.156s, Critical Path: 5.80s
INFO: 2 processes: 1 internal, 1 local.
INFO: Build completed successfully, 2 total actions
//keras/applications:applications_load_weight_test_mobilenet_v3_small    PASSED in 5.8s

Executed 1 out of 1 test: 1 test passes.
INFO: Build completed successfully, 2 total actions



root ➜ /home/keras (patch-2) $ bazel test --test_output=errors //keras/applications:applications_load_weight_test_mobilenet_v3_large
WARNING: The following configs were expanded more than once: [v2]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=243
INFO: Reading rc options for 'test' from /home/keras/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define open_source_build=true --define=use_fast_cpp_protos=false --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --config=short_logs --config=v2
INFO: Reading rc options for 'test' from /home/keras/.bazelrc:
  'test' options: --define open_source_build=true --define=use_fast_cpp_protos=false --config=v2
INFO: Found applicable config definition build:short_logs in file /home/keras/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/keras/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:v2 in file /home/keras/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Analyzed target //keras/applications:applications_load_weight_test_mobilenet_v3_large (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
Target //keras/applications:applications_load_weight_test_mobilenet_v3_large up-to-date:
  bazel-bin/keras/applications/applications_load_weight_test_mobilenet_v3_large
INFO: Elapsed time: 6.792s, Critical Path: 6.45s
INFO: 2 processes: 1 internal, 1 local.
INFO: Build completed successfully, 2 total actions
//keras/applications:applications_load_weight_test_mobilenet_v3_large    PASSED in 6.4s

Executed 1 out of 1 test: 1 test passes.
INFO: Build completed successfully, 2 total actions
```

**Comment by shkarupa-alex** [comment]
HardSigmoid used in MobileNetV3 does not match keras hard_sigmoid (different slopes).
Fixed this with layers.Add-Multiply to prevent Lambda wrapper.

Test pointed by @nkovela1 now passes.

**Pull request closed without merging**
