### PR TITLE
implement transform_bounding_boxes for center_crop

### PR DESCRIPTION
**Pull request by shashaka**
I implemented the transform_bounding_boxes method to handle center cropping. 
Could you please review my code and let me know if there are any corrections or improvements needed?

here is [gist](https://colab.research.google.com/drive/1LQEOczv4WLYycS5UnhkXMlZH02CRPSI2?usp=sharing)

### CODE REVIEW

**Comment by lattaai11** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added the transform_bounding_boxes method to handle center cropping of bounding boxes. The method adjusts the bounding box coordinates based on the cropping parameters and ensures they stay within the new image boundaries.

You can review changes in this commit: https://github.com/lattaai11/keras-team-keras-20491/commit/7e107ae64cc7c85fd734d22c60b9c7d4d7b1bff2.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by divyashreepathihalli** [comment]
Thanks @shashaka can you please add a demo colab to show single image and batched image transformation demo.

**Comment by shashaka** [comment]
@divyashreepathihalli 
I updated my [gist](https://colab.research.google.com/drive/1LQEOczv4WLYycS5UnhkXMlZH02CRPSI2?usp=sharing) to include demo for single image and batched one.

**Review by fchollet — COMMENTED** [review]
The code looks good -- please add a unit test for correctness.

**Comment by shashaka** [comment]
I've added unit tests for this. Please let me know if any updates are needed.

**Pull request merged**
