### PR TITLE
Print expanded nested layers feature in models.summary()

### PR DESCRIPTION
**Pull request by krishrustagi**
Issue #15250. I am making this PR.
The changes have been made using the recursion approach. All the nested layers get summarized one by one.

### CODE REVIEW

**Comment by innat** [comment]
@krishrustagi Thanks for your PR. It seems it solves feature request no. [3](https://github.com/keras-team/keras/issues/15239). It will be really handy to debug the nested model/layers. 

However, it seems that in the `LayerUtilsTest` class, there is no test for subclass api modeling. We're not sure if this is on purpose. But we're interested to see how this modification goes on such modeling. So, could you please share the `.summary()` of the following two models written in colab, [LINK](https://colab.research.google.com/drive/1HcE8T_9IQCSZoCItylK_lBGWE3gZW9JB?usp=sharing). Thanks.

**Comment by krishrustagi** [comment]
@innat Thanks for pointing it out! Testing for subclass models was not done by my end. I fixed that and added a unit test for the same.

I used `model_name.summary(line_length=120, expand_nested=True)` and got the following results

[model_1.txt](https://github.com/keras-team/keras/files/7070693/model_1.9.txt)
[model_2.txt](https://github.com/keras-team/keras/files/7070691/model_2.5.txt)

**Comment by innat** [comment]
@krishrustagi 
Thanks. It looks fine. However, I think the name of the nested layer would be clear to mention inside, [here](https://imgur.com/a/nhCDRbN); something like [this](https://imgur.com/a/6ECLRCy). Also, in between `|¯¯` this two special character, using only one type would be nice, for [example](https://imgur.com/a/6ECLRCy).

**Comment by krishrustagi** [comment]
@innat I got the idea from @fchollet 
> I think we should implement it as such:
> 
> 1. Factor out in a separate function the part that prints the layer table (as opposed to the header and footer) of the summary
> 2. When iterating over layers (line 271), test if the layer is a `Model` and has inner layers.
>    If so, immediately call the separate function on it. And and a new kind of line separator to delimitate the nested model
> 
> The goal is to see something like
> 
> ```
> Model: "sequential_4"
> _________________________________________________________________
> Layer (type)                 Output Shape              Param #   
> =================================================================
> dense_5 (Dense)              (None, 512)               112128    
> _________________________________________________________________
> sequential_3 (Sequential)    (None, 32)                579494    
> *****************************************************************
> dense_3 (Dense)              (None, 1024)              525312    
> _________________________________________________________________
> dense_4 (Dense)              (None, 42)                43050     
> *****************************************************************
> =================================================================
> Total params: 691,622
> Trainable params: 691,622
> Non-trainable params: 0
> _________________________________________________________________
> ```
> 
> Also please add a unit test for this change.

The name for the nested_layer is looking good outside. I think that first, it should be the layer name outside `|¯¯` (nested or non-nested) and if it contains any further layers, then it should get expanded. In this case, GeneratorModel is the nested layer name `(layer name)`, and the inner layers it contains should be in between `|¯¯`

The printing should remain as it is:

```
Layer_1
Layer_2 (contain inner layers)
└── Part_1 (inside `|¯¯`)
└── Part_2
    └── Part_2.1
```
This difference of `model.summary()` with the `plot_model` seems right to me.

**Comment by krishrustagi** [comment]
I have replaced `isinstance(layer, type(model))` with `hasattr(layer, 'layers')` because `isinstance(layer, type(model))` was not checking the for the subclass models.

**Comment by krishrustagi** [comment]
@fchollet can you please review this? If there are other changes, please let me know.

**Review by fchollet — APPROVED** [review]
LGTM, thanks for the contribution!

**Pull request merged**
