### PR TITLE
Add test files for  `keras/datasets`

### PR DESCRIPTION
**Pull request by Faisal-Alsrheed**
Added unit tests for `keras/datasets` at `integration_tests`

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR! We can't realistically run this on CI, because we would incur multiple downloads of medium-size files each time we run CI. Maybe you could move it to integration_tests, where only specific tests are run on CI (not everything).

**Comment by Faisal-Alsrheed** [comment]
> Thanks for the PR! We can't realistically run this on CI, because we would incur multiple downloads of medium-size files each time we run CI. Maybe you could move it to integration_tests, where only specific tests are run on CI (not everything).

Done, @fchollet. Thanks to your feedback, I am learning.

**Review by fchollet — COMMENTED** [review]
Thanks for the update -- for better organization, please move the test files under `integration_tests/dataset_tests/`

**Review by fchollet — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
