### PR TITLE
Update Adam in optimizer.py 

### PR DESCRIPTION
**Pull request by abhisheksms**
Added bias correction to first and second moment estimate in the Adam optimizer.

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR!

Please explain in more detail what you are trying to do here.

**Comment by abjoker** [comment]
Thanks for your review

The first moment (mean) and the second moment (variance) of the gradients have been initialized as a vector of zeros. 

I had read from the paper [https://arxiv.org/pdf/1412.6980v8.pdf](url) that doing so would make the moment estimates biased towards zero. To counteract it, a bias correction term is added to both mean and variance which can then be used to update the parameters.

**Comment by abjoker** [comment]
Thanks for your review

The first moment (mean) and the second moment (variance) have been initialized as a vector of zeros. According to the paper [] (https://arxiv.org/pdf/1412.6980.pdf), doing so would lead the moment estimates to be biased towards zero. To counteract it, a bias correction term is added which can then be used to update the parameters.

**Review by fchollet — COMMENTED** [review]
I may be missing something, but:

- These changes would cause a division by zero for the first batch (t = 0), specifically `m_t / (1 - 0.9 ** 0 )`
- This scheme is absent from all canonical Adam implementations (such as the TensorFlow one).
- This scheme would achieve essentially nothing after the first ~20 batches, since the division denominator would quickly converge towards 1. So it's a lot of computation for no clear purpose.

**Comment by abhisheksms** [comment]
I was smart, what the hell have I become?

**Pull request closed without merging**
