### PR TITLE
Round seconds instead of truncating to int

### PR DESCRIPTION
**Pull request by ozabluda**

### CODE REVIEW

**Comment by fchollet** [comment]
This adds 2 ops that will be run for every progbar update (`int` cast and `np.round`), and doesn't add any clear usability benefits (sub-second accuracy in ETA is not necessary). For performance reasons, we won't merge it.

**Comment by ozabluda** [comment]
@fchollet, oops, sorry, this PR got garbled after merging with master. Please reopen it, I've already committed what I actually meant into this branch.

Sub-second accuracy in ETA is not necessary, unless the ETA is subsecond to begin with. For example, if `0.5  < ETA < 1.0`. Also, in this case (say 10 steps, 0.1 sec each) , without this PR, ETA (0 sec) will be inconsistent with total time (1 sec).

**Comment by ozabluda** [comment]
@fchollet, Performance-wise, the two are indistinguishable and minuscule (I am impressed):
```
$ python -m timeit '"%d"%0.5'
100000000 loops, best of 3: 0.0104 usec per loop

$ python -m timeit '"%.0f"%0.5'
100000000 loops, best of 3: 0.0104 usec per loop
```
What, actually, bothers me more is that the standard Python rounding is towards even, while in this case we want to round towards nearest, since we don't care about it being unbiased, and care more about, say `1.5 <= ETA <2.5` rounding to 2. But I wasn't sure is extra complexity of this better rounding would be worth it.

**Comment by ozabluda** [comment]
For the reference the 'garbled' PR could have been rewritten like so (there is no need for `np.round()`):
```
$ python -m timeit -s 'round(1.5 * (2 - 1))'
100000000 loops, best of 3: 0.0126 usec per loop
```

**Pull request closed without merging**
