### PR TITLE
Using a filter to narrow down which warning should not be taken into account with cntk

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
### Summary

Ignoring all warnings can be dangerous because there might be useful ones (eg: depreciation warnings). I propose that we target only the warnings which we don't care about.

### Related Issues

#7636

### PR Overview

- [ ] This PR requires new unit tests [y/n] (make sure tests are included)
- [ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
There are quite a lot of depreciation warnings (which are important to display!) I'll see if I can either fix what is mentioned in the warning or if I can find a way to display only once each warning.

**Comment by gabrieldemarmiesse** [comment]
@taehoonlee would this new implementation work for you? We can display all the warnings without making the logs explode in size. The logs will be even smaller once #11668 is merged.

**Comment by taehoonlee** [comment]
@gabrieldemarmiesse, In my opinion, we can already see useful warnings in TF and TH environments. Also, there are already few duplicates in [the current master's TF env log](https://travis-ci.org/keras-team/keras/jobs/459406481).

**Comment by taehoonlee** [comment]
@gabrieldemarmiesse, Yes I think that they are useful. But currently, there are no CNTK depreciation warnings. We can see the following three CNTK-specific warnings in [CNTK env log of this PR](https://travis-ci.org/keras-team/keras/jobs/459413077):
```
keras/backend/cntk_backend.py:26: UserWarning: CNTK backend warning: GPU is not detected. CNTK's CPU version is not fully optimized,please run with GPU to get better performance.
keras/backend/cntk_backend.py:1495: UserWarning: CNTK Backend only supports accurate masking if `output == new_states[0]` for `output, new_states = step_function(inputs, states)`
keras/backend/cntk_backend.py:1264: UserWarning: Warning: CNTK backend does not support collapse of batch axis with inferred dimension. The reshape did not take place.
```

**Comment by gabrieldemarmiesse** [comment]
I'll rework this PR to something which makes more sense.

**Pull request closed without merging**
