### PR TITLE
add trig funcs for numpy backend

### PR DESCRIPTION
**Pull request by danFromTelAviv**

### CODE REVIEW

**Comment by danFromTelAviv** [comment]
again a timeout

**Comment by gabrieldemarmiesse** [comment]
This timout is really annoying. I hope we find a solution soon.

**Comment by gabrieldemarmiesse** [comment]
Re-triggering the build

**Comment by gabrieldemarmiesse** [comment]
The reference operations file has no newline at the end of the file. Can you add one to be PEP8 complient? Thank you.

**Comment by gabrieldemarmiesse** [comment]
It's weird. I wonder if this file is tested with PEP8. Anyway. Thanks for the PR. The third time's the charm :)

**Pull request merged**
