### PR TITLE
K.cumsum for CNTK backend

### PR DESCRIPTION
**Pull request by abhaikollara**
### PR Overview

- [x] This PR requires new unit tests [y/n] (make sure tests are included)
       Tests for `cumsum` and `cumprod` have been split for the time being
- [N] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [Y] This PR is backwards compatible [y/n]
- [N] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by taehoonlee** [comment]
Thank you for the PR, @abhaikollara. The computation looks inefficient to me. Could you follow [the official example](https://www.cntk.ai/pythondocs/cntk.layers.sequence.html#cntk.layers.sequence.Recurrence) in CNTK?

**Comment by taehoonlee** [comment]
I'm sorry for my poor comments. The result in the official example is a function which takes a `Sequence` not a variable. Thus, it is not appropriate to define it as a Keras' backend operation. Your implementaion is for the best for now.

**Comment by taehoonlee** [comment]
Thus, I think it is better to merge this PR if you resolve the merge conflicts.

**Comment by abhaikollara** [comment]
> I'm sorry for my poor comments. The result in the official example is a function which takes a `Sequence` not a variable. Thus, it is not appropriate to define it as a Keras' backend operation. Your implementaion is for the best for now.

Aah, thanks. I did try to make that work without any luck.
I'll resolve the conflicts now

**Comment by abhaikollara** [comment]
@taehoonlee I've resolved the conflicts, but there seems to be an issue with Travis builds. If it's not too much trouble could you check out #12478

**Comment by abhaikollara** [comment]
@taehoonlee The issues have been solved.

**Pull request merged**
