### PR TITLE
Support Memcache for Samples on (Virtual) Disk

### PR DESCRIPTION
**Pull request by ghostplant**
This is to make use of host memory to cache partial or
complete input samples loaded from disk which will reduce the
overhead of disk access especially for virtual disk provided by
cloud machines.

Signed-off-by: CUI Wei <ghostplant@qq.com>

### CODE REVIEW

**Comment by ghostplant** [comment]
In theory, using multiprocessing to load data from disk concurrently is not suitable in normal cases.

For a slice of SSD, the performance of concurrent data loading from disk is AT-most the same as serial read, due to upper-bounded IOPS of device;
For a slice of HDD, the performance of concurrent data loading from disk will be sharply dropped due to inefficient random access ability;

According to many existing investigation, the theory is proven established.

The primary factor to boost slow-disk-I/O is to make use of memcache to avoid repeated data loading from disk.

https://github.com/keras-team/keras/issues/9502#issuecomment-372044067

**Comment by fchollet** [comment]
Do you have a benchmark, for SSD and HDD?

**Comment by ghostplant** [comment]
Previously I only used SSD for testing and I saw nothing performance improved for multi workers, and it is as expected.
I'll setup an HDD environment then.

**Comment by fchollet** [comment]
Please benchmark `InceptionV3` with ImageNet JPG files and 4 preprocessing workers, if that's easy for you. What is your current setup?

**Comment by ghostplant** [comment]
Sorry, it still needs sometime for a detailed benchmarks. Allow me working on another keras optimization first.

**Comment by ghostplant** [comment]
Here are some benchmark of multiple workers which finally proved useful in multiple cores, while single CPU will usually cause a bad performance, that is why some users see worse performance when changing workers to be larger. So it is reasonable that the number of workers should correspond with the system CPU cores.

It is less likely that a machine with old IDE harddisk can also equipped with high-performance GPU and large memory, so I couldn't run large models on such machines. Instead, I uses example `cifar10_cnn` and the dataset is chosen from cats and dogs provided by kaggle.

=============

As for SSD, the benchmark is as follows:
1) Hardware Configuration: CPU core=16, driver=full SSD, GPU=Tesla P100 x 4, gpuMem=16GB, 
hostMem=260GB;
Model Configuration: model = inception_v3, input datasets = cats and dogs 25k samples;

>>> How the number of workers influences `perf`:
cpu=16, worker= 1, perf = 229ms/step
cpu=16, worker= 2, perf = 221ms/step
cpu=16, worker= 4, perf = 229ms/step  (not effective)
cpu=16, worker= 8, perf = 242ms/step  (worse)
cpu=16, worker=16, perf = 259ms/step  (worse)

=============

As for HDD, the benchmark is as follows:
2) Hardware Configuration: CPU core=2, driver=HDD(AHCI mode), GPU=GF940MX x 1, gpuMem=4GB, hostMem=4GB;
Model Configuration: model = cifar10_cnn, input datasets = cats and dogs 25k samples;

>>> When CPU = 4, how the number of workers influences `perf`:
cpu=4, worker= 1, perf = 63ms/step
cpu=4, worker= 2, perf = 35ms/step
cpu=4, worker= 4, perf = 28ms/step  (good)
cpu=4, worker= 8, perf = 31ms/step
cpu=4, worker=16, perf = 34ms/step

>>> When CPU = 1, how the number of workers influences `perf`:
cpu=1, worker= 1, perf = 349ms/step
cpu=1, worker= 2, perf = 208ms/step
cpu=1, worker= 4, perf = 365ms/step  (worse)
cpu=1, worker= 8, perf = 480ms/step  (worse)
cpu=1, worker=16, perf = 490ms/step  (worse)

=============

So the conclusion of the benchmarks indicates it is not suitable to enable multiple workers when the number cpu is not sufficient, in this case, multiple workers will only drop the performance.

As for cache, I found through other experiments that Linux kernel already supports page cache whatever the harddisk is HDD or SSD so as long as the host memory is adequate, which make user-space cache useless, so I'll cancel this PR.

**Pull request closed without merging**
