### PR TITLE
Fix mixed precision check in TestCase.run_layer_test: compare with output_spec dtype instead of hardcoded float16

### PR DESCRIPTION
**Pull request by shkarupa-alex**

### CODE REVIEW

**Comment by shkarupa-alex** [comment]
Need help with `Tests / Check the code format (pull_request) Failing after 1m`.
File is formatted as described in contribution docs.
```bash
> sh shell/format.sh
Skipped 26 files
All done! ✨ 🍰 ✨
626 files left unchanged.
```

**Comment by fchollet** [comment]
> Tests / Check the code format (pull_request)

Run `sh shell/format.sh` to format the code.

**Comment by fchollet** [comment]
> would reformat /home/runner/work/keras/keras/keras/testing/test_case.py

I suppose you don't have the latest version of `black` installed?

**Comment by shkarupa-alex** [comment]
> > would reformat /home/runner/work/keras/keras/keras/testing/test_case.py
> 
> I suppose you don't have the latest version of `black` installed?

Updated to latest version 24.2.0 (previous version installed with requirements.txt as noted in contribution docs).
Now reformatting replaced `from keras import ...` to `from keras.src import ...`

**Review by fchollet — APPROVED** [review]

**Pull request merged**
