### PR TITLE
Breaking down the attention API PR part 3.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
### Summary

I suppose we can't merge this as-is right? We need some tests, and a basic implementation since this class is abstract?

Any help would be welcome on this.

### PR Overview

- [ ] This PR requires new unit tests [y/n] (make sure tests are included)
- [ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by fchollet** [comment]
I don't think this PR is a good fit to implement attention models at this point.

I believe the `Model` subclassing API would make this use case far easier.

We should come up with side by side code examples of similar models to figure out whether that is the case (the code doesn't have to work, it would just show the workflow with each API, the API in this PR and the model subclassing API).

**Comment by gabrieldemarmiesse** [comment]
Does that mean that we should drop #8296 and this PR?

**Comment by fchollet** [comment]
Possibly, but first we should make a decision: what's the best way to implement attention models in the Keras API today, and would this PR provide a better API?

So make this decision we need to write quick code examples showing how to build common attention models 1) with the model subclassing API, 2) with the API introduced by #8296, and figure out what looks best.

**Comment by gabrieldemarmiesse** [comment]
Closing this PR in favor of #11172 gor organization purposes. This PR can be reopened later on if necessary.

**Pull request closed without merging**
