### PR TITLE
Refactor keras/engine/training.py and keras/engine/training_arrays.py

### PR DESCRIPTION
**Pull request by knightXun**
Make fit_loop function easy read and understand.

### PR Overview

- [ ] This PR requires new unit tests [y/n] (make sure tests are included)
- [ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [ ] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by knightXun** [comment]
still working on this, dont close it.

**Comment by gabrieldemarmiesse** [comment]
You can re-trigger by closing the issue and opening it again.

**Comment by knightXun** [comment]
@gabrieldemarmiesse thank you, this pr give me much confidence to work for keras. I will continue hack on keras. thanks again!

**Comment by knightXun** [comment]
@gabrieldemarmiesse hi, can this pr be merged？

**Comment by knightXun** [comment]
＠fchollet thx.

**Pull request merged**
