### PR TITLE
Use Python logging instead of printing

### PR DESCRIPTION
**Pull request by maggyero**
### Summary

This PR uses the `logging` package instead of the built-in function `print` to report events. This is the standard practice in Python libraries.
See https://docs.python-guide.org/writing/logging/#or-print for the reasons.

### Related Issues

#7777 and #9272 (duplicate).

### PR Overview

- [n] This PR requires new unit tests [y/n] (make sure tests are included)
- [n] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [n] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR.

Printing is for things you want the user to read. Logging is for everything else. The logs of a Keras/TF application are unusable for any purpose other than debugging (it's flooded with a lot of information).

Our current logging setup (which makes use of both) is fine as it is. Moving these statements (which are meant to be read) to a logger would effectively hide them in most cases.

**Comment by mitar** [comment]
I disagree. Keras is used in many settings. As stand-alone scripts or in the cloud setting on a cluster. Having debugging information going to logging is in fact the main way how those statement would be able to be captured and stored into a central logging facility for the whole cluster. Intercepting stdout/stderr is ugly and tricky and it is hard to know where the source is. (So filtering and debugging in a complicated app is tricky.)

Keras should use logging as a library. Then, at any entry point, `__main__` or anything like that, you simply call `logging.basicConfig()` and you get all current functionality back. Even better, if you do not call it, Python calls it for you. So we would not loose any statement and no statement would be hidden (if they are INFO level).

So, this can be made in a backwards compatible way. All statement you think should be kept visible to users when they do not configure logging, should be at level INFO. Then things by default will go to stdout and be same as now. But for those power users who want to control where thing are and probably do more with those logs, we can configure logging to do better things.

**Comment by maggyero** [comment]
@fchollet I think one should be able to silence the messages of any Python library.

For instance, with the `pika` library:

```
import logging

import pika

logging.basicConfig(level=logging.INFO)

parameters = pika.ConnectionParameters()

with pika.BlockingConnection(parameters) as connection:
    channel = connection.channel()
    channel.queue_declare(queue="foobar")
    channel.publish(exchange="", routing_key="foobar", body="Hello, world!")
    (method_frame, header_frame, body) = channel.basic_get(queue="foobar")

logging.info(body.decode())
```

Output:

> INFO:pika.adapters.base_connection:Connecting to ::1:5672
> INFO:pika.adapters.blocking_connection:Created channel=1
> INFO:pika.adapters.blocking_connection:Closing connection (200): Normal shutdown
> INFO:pika.channel:Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN socket=('::1', 54444, 0, 0)->('::1', 5672, 0, 0) params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
> INFO:pika.channel:Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN socket=('::1', 54444, 0, 0)->('::1', 5672, 0, 0) params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
> INFO:pika.connection:Closing connection (200): Normal shutdown
> INFO:pika.connection:Disconnected from RabbitMQ at localhost:5672 (200): Normal shutdown
> INFO:pika.adapters.blocking_connection:Connection closed; result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED socket=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, reason_code=200, reason_text='Normal shutdown')
> INFO:root:Hello, world!

To selectively silence the logging of the `pika` library, one can write this:

```
import logging

import pika

logging.basicConfig(level=logging.INFO)
logging.getLogger("pika").setLevel(logging.CRITICAL)  # this silences pika logging

parameters = pika.ConnectionParameters()

with pika.BlockingConnection(parameters) as connection:
    channel = connection.channel()
    channel.queue_declare(queue="foobar")
    channel.publish(exchange="", routing_key="foobar", body="Hello, world!")
    (method_frame, header_frame, body) = channel.basic_get(queue="foobar")

logging.info(body.decode())
```

Output:

> INFO:root:Hello, world!

But with `keras`, you cannot:

```
import logging

import keras

logging.basicConfig(level=logging.INFO)
logging.getLogger("keras").setLevel(logging.CRITICAL)
```

Output:

> Using TensorFlow backend.

**Comment by harahu** [comment]
Either through this PR or some other: full integration with python's logging library should without a doubt be part of Keras. As a user who regularly uses Keras on VMs and inspect logs in hindsight, it would be really convenient to have Keras actually be logging stuff.

**Comment by auphofBSF** [comment]
> Thanks for the PR.
> 
> Printing is for things you want the user to read. Logging is for everything else. The logs of a Keras/TF application are unusable for any purpose other than debugging (it's flooded with a lot of information).
> 
> Our current logging setup (which makes use of both) is fine as it is. Moving these statements (which are meant to be read) to a logger would effectively hide them in most cases.

In respect of your huge contributions to Keras, I do ask that you reconsider this great PR (pending test cases and docs etc) 

The PR It has useful logging implications for consistency and control of verbosity of messages by higher level apps. Especially as our apps move through different states of development or production.
The tuning of logging can be then easily controlled by the higher level app. (enough already said in other comments #7777 and #9272 (duplicate).

Tensorflow supports this style of logging https://planspace.org/20170322-tensorflow_logging/ , 

Keras is in my opinion lacking adequate and consistent logging for the level and  breadth of functionality that this module is now at. 
This PR #12019  fits directly within the spirit of the Keras Guiding Principles: **User friendliness, Modularity, Easy extensibility, Work with Python.**

**Pull request closed without merging**
