### PR TITLE
Fix `clipnorm` for TF models with `Embedding` layer(s).

### PR DESCRIPTION
**Pull request by aaarrti**
Fix for the issue described in https://github.com/keras-team/keras/issues/18985

### CODE REVIEW

**Comment by fchollet** [comment]
Thank you for the PR. Please take a look at the failing test. https://github.com/keras-team/keras/actions/runs/7303008810/job/19902699292?pr=18986

**Comment by aaarrti** [comment]
> Member

Hi @fchollet, 

sorry, I was a little impatient with the PR and forget to check whether the CI checks pass, I will convert it to draft, until I resolve the issue. So far, I was unable to reproduce the failing test, whether locally nor in GitHub code space. 

I am curious, is there a reason why tests are run only using py39 but `.devcontainer.json` uses `python:3.10`? This makes it more complicated to reproduce the CI setup. I thought `keras` should also support py310, py311 and py312, or did I miss anything?

**Comment by fchollet** [comment]
> I am curious, is there a reason why tests are run only using py39 but .devcontainer.json uses python:3.10? This makes it more complicated to reproduce the CI setup. I thought keras should also support py310, py311 and py312, or did I miss anything?

Right, we should be able to upgrade the GitHub CI actions to py310. Are you able to open a PR for that?

**Review by fchollet — APPROVED** [review]
LGTM, thank you!

**Comment by aaarrti** [comment]
> > I am curious, is there a reason why tests are run only using py39 but .devcontainer.json uses python:3.10? This makes it more complicated to reproduce the CI setup. I thought keras should also support py310, py311 and py312, or did I miss anything?
> 
> Right, we should be able to upgrade the GitHub CI actions to py310. Are you able to open a PR for that?

Let's continue the discussion here https://github.com/keras-team/keras/issues/18989

**Pull request merged**
