### PR TITLE
Improved backend init

### PR DESCRIPTION
**Pull request by nbam**
Improved backend init by adding a KERAS_DIR env variable option and  better backoff strategy that doesn't insist on a writable directory if config files already exist.

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR. I don't think we will merge it, as I don't see it as a necessary feature. If you really want to insist on proceeding, then you should:
- Make a strong case for the feature.
- Make the PR style compliant (line length, remove use of backslashes, remove print statements, error message formatting...)
- Make the PR a lot shorter; having a flag-specified default value for the config dir should only take a few lines.

**Comment by nbam** [comment]
Thanks for the feedback.

This suggested fix resolves several issues.  The main ones being: 
1) It removes the requirement that home directories be writable prior to checking for a readable config.  Some environments don't guarantee writable home directories for security reasons.
2) It provides a mechanism for changing the config path which allows other tooling to better integrate with Keras.  For example, this fix could avoid the dist-keras hack function "def set_keras_base_directory( base_dir='/tmp/' + get_os_username() )"

I thought it would be better to make improvements rather than log issues.  Maybe I'm wrong. :) What's the best way to have these issues addressed?

Thanks again.

**Comment by nbam** [comment]
Looks like some CI is broken

**Comment by nbam** [comment]
I'm not sure what to make of these CI issues.  The tests (py.test tests) pass on my machine.

**Pull request closed without merging**
