### PR TITLE
Updated f-string method

### PR DESCRIPTION
**Pull request by cyai**

### CODE REVIEW

**Comment by rthadur** [comment]
@cyai can you please check the failing lint errors. Thank you

**Review by qlzh727 — CHANGES_REQUESTED** [review]
Please run the format script for this PR. Thanks.

**Comment by gbaned** [comment]
@cyai Can you please check @qlzh727's comments and keep us posted ? Thank you!

**Comment by fchollet** [comment]
The codebase has been reformatted previously. Thanks!

**Pull request closed without merging**
