### PR TITLE
add flow_from_dataframe to ImageDataGenerator

### PR DESCRIPTION
**Pull request by Vijayabhaskar96**
This PR allows the users to directly read the images that are mapped with the CSV files (or any other file that can be read as a pandas/dask dataframe) and also enables the users to use the flow_from_dataframe for regression problems, multi-label classification problems or any problem that expects data from the dataframe.
The `flow_from_dataframe` is similar to `flow_from_directory` except few changes, 

```
Takes the dataframe and the path to a directory, and generates batches of augmented/normalized data.
# Arguments
dataframe: pandas like dataframe.

directory: string,path to the target directory that contains all the images mapped in the dataframe.

x_col: string,column in the dataframe that contains the filenames of the target images.

y_col: string or list of strings,columns in the dataframe that will be the target data.
has_ext: bool, True if filenames in dataframe[x_col] has filename extensions,else False.

target_size: tuple of integers `(height, width)`, default: `(256, 256)`.
                 The dimensions to which all images found will be resized.
color_mode: one of "grayscale", "rbg". Default: "rgb".
                 Whether the images will be converted to have 1 or 3 color channels.
classes: optional list of class subdirectories (e.g. `['dogs', 'cats']`). default: None.
                 If not provided, the list of classes will be automatically
                 inferred from the subdirectory names/structure under `directory`,
                 where each subdirectory will be treated as a different class
                 (and the order of the classes, which will map to the label indices, will be alphanumeric).
                 The dictionary containing the mapping from class names to class
                 indices can be obtained via the attribute `class_indices`.
class_mode: one of "categorical", "binary", "sparse", "input" or None. Default: "categorical".
                 Determines the type of label arrays that are returned: "categorical" will be 2D one-hot 
                 encoded labels,
                 "binary" will be 1D binary labels, "sparse" will be 1D integer labels, "input" will be images 
                 identical to input images (mainly used to work with autoencoders).
                 If None, no labels are returned (the generator will only yield batches of image data, which is 
                 useful to use `model.predict_generator()`, `model.evaluate_generator()`, etc.).
batch_size: size of the batches of data (default: 32).

shuffle: whether to shuffle the data (default: True)

seed: optional random seed for shuffling and transformations.

save_to_dir: None or str (default: None). This allows you to optionally specify a directory to 
                   which to save the augmented pictures being generated (useful for visualizing what you are 
                doing).
save_prefix: str. Prefix to use for filenames of saved pictures (only relevant if `save_to_dir` is 
                set).
save_format: one of "png", "jpeg" (only relevant if `save_to_dir` is set). Default: "png".

follow_links: whether to follow symlinks inside class subdirectories (default: False).

subset: Subset of data (`"training"` or `"validation"`) if
                 `validation_split` is set in `ImageDataGenerator`.
                interpolation: Interpolation method used to resample the image if the
                 target size is different from that of the loaded image.
                 Supported methods are `"nearest"`, `"bilinear"`, and `"bicubic"`.
                 If PIL version 1.1.3 or newer is installed, `"lanczos"` is also
                 supported. If PIL version 3.4.0 or newer is installed, `"box"` and
                 `"hamming"` are also supported. By default, `"nearest"` is used.

```
Example:
```
traindf=pd.read_csv("./train.csv")
testdf=pd.read_csv("./test.csv")
validdf=pd.read_csv("./valid.csv")
train_datagen = ImageDataGenerator(preprocessing_function=preprocess,
                                   width_shift_range=0.2, height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True, rotation_range = 20)
val_datagen = ImageDataGenerator(preprocessing_function=preprocess)
test_datagen = ImageDataGenerator(preprocessing_function=preprocess)
train_iter = train_datagen.flow_from_dataframe(dataframe=traindf,directory="./train/train_img/",x_col="Image_name",
                                               y_col=y_col,has_ext=True,target_size=(224, 224), color_mode='rgb',
                                               class_mode='other',batch_size=32,shuffle=True, seed=42)
valid_iter = val_datagen.flow_from_dataframe(dataframe=validdf,directory="./valid/",x_col="Image_name",
                                               y_col=y_col,has_ext=True,target_size=(224, 224), color_mode='rgb',
                                               class_mode='other',batch_size=32,shuffle=True, seed=42)
test_iter = test_datagen.flow_from_dataframe(dataframe=testdf,directory="./test/test_img/",x_col="Image_name",
                                               has_ext=True,target_size=(224, 224), color_mode='rgb',
                                               class_mode=None,batch_size=100,shuffle=False, seed=42)
```

### CODE REVIEW

**Comment by vkk800** [comment]
Not necessarily something that should be addressed in this PR, but just a comment: much of the code in DataFrameIterator is copied from DirectoryIterator. Thus, it would make sense to write just a generic DataIterator (or FilenameIterator?) class that iterates over arbitrary list of filenames and is inherited by both of those iterators.

**Comment by Vijayabhaskar96** [comment]
I agree with your comment, I just made this for myself in my free time, I thought it would be a useful tool for beginners and I'm not planning to optimize this code as I have less free time currently, but I encourage anyone to make this faster and better.

**Comment by Dref360** [comment]
We could merge it, but as @vkk800 said, we would need an abstraction from an Iterator.

It also requires testing

**Comment by fchollet** [comment]
If you would like to continue working on this PR (taking into account comments by @vkk800 and @Dref360), please open it on https://github.com/keras-team/keras-preprocessing (since the `preprocessing` module is no longer part of this codebase).

**Pull request closed without merging**
