### PR TITLE
UNK words map to an average vector instead of zeros

### PR DESCRIPTION
**Pull request by abhaikollara**
### Summary
Unknown words (UNKs) map to a vector that averages over all vectors in the embedding matrix rather than to an all-zero vector.

### Related Issues
#12124 

### PR Overview

- [x] This PR requires new unit tests [**N**] (make sure tests are included)
- [x] This PR requires to update the documentation [**N**] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [**Y**]
- [x] This PR changes the current API [**N**] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR.

Is there any data on the potential benefits?

In general it's better to use zeros vectors in these cases, because that enables you to set `mask_zero=True` in the first `Embedding` layer, which would mask the unknown entries completely in the rest of the network (e.g. if using a RNN). Here we don't use masking because our model is a 1D convnet, and conv layers don't support masking.

**Comment by fchollet** [comment]
Edited my comment. I think we should merge this, but she should document it in the code. Thanks!

**Comment by abhaikollara** [comment]
I tried running both models, the average vector version seems to be slightly worse 😅. Should I close the PR ?

**Comment by fchollet** [comment]
Possibly because it's easier for the model to learn than a zeros vector (which stands out) stands for nothing, whereas a mean vector is still a point in the embedding space, and therefore has a meaning (and you don't know what it is until you lookup nearby words).

Let's close. Thanks for the PR anyway! You can check out this https://github.com/keras-team/keras/projects/1 for more ideas.

**Pull request closed without merging**
