### PR TITLE
Add depthwise conv2d for Theano and CNTK

### PR DESCRIPTION
**Pull request by taehoonlee**
This PR enables `DepthwiseConv2D`, initially designed for TensorFlow only, to work on Theano and CNTK. This PR includes the following:
- moving `class DepthwiseConv2D` from `keras/applications/mobilenet.py` to `keras/layers/convolutional.py` without modification,
- adding `depthwise_conv2d` for Theano and CNTK,
- revising `test_depthwise_conv_2d` in `backend_test.py` with respect to existing backend test styles,
- adding `test_depthwise_conv_2d` in `convolutional_test.py`.

### CODE REVIEW

**Comment by fchollet** [comment]
Sounds great! Have you checked that MobileNet inference with `imagenet` weights gives the expected results with Theano and CNTK?

Merging your other PR  has introduced a merge conflict with this one, please fix.

**Comment by taehoonlee** [comment]
@fchollet, The conflict has been resolved. The inference results are the following: Rather, the outputs of TensorFlow look strange to me.

```bash
 $ cat test_mobilenet.py
from keras.applications.mobilenet import MobileNet
from keras.preprocessing import image
from keras.applications.mobilenet import preprocess_input, decode_predictions
import numpy as np

model = MobileNet(weights='imagenet')

img = image.load_img('cat.png', target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

print('Predicted:', decode_predictions(model.predict(x), top=3)[0])

 $ KERAS_BACKEND=cntk python test_mobilenet.py
Using CNTK backend
Selected GPU[0] Tesla P100-PCIE-16GB as the process wide default device.
('Predicted:', [(u'n02123159', u'tiger_cat', 0.25886607), (u'n02124075', u'Egyptian_cat', 0.14433344), (u'n02123045', u'tabby', 0.06473238)])

 $ KERAS_BACKEND=tensorflow python test_mobilenet.py
Using TensorFlow backend.
('Predicted:', [(u'n03482405', u'hamper', 0.21035318), (u'n02123159', u'tiger_cat', 0.11360751), (u'n04074963', u'remote_control', 0.09508653)])

 $ KERAS_BACKEND=theano python test_mobilenet.py
Using Theano backend.
('Predicted:', [(u'n02123159', u'tiger_cat', 0.2602814), (u'n02124075', u'Egyptian_cat', 0.14234008), (u'n02123045', u'tabby', 0.06521355)])
```

**Comment by fchollet** [comment]
It's orthogonal to this PR, but we should try to determine at what commit the discrepancy arose. A possible candidate would be some recent modifications to BN in TF. It could also be a preprocessing issue.

**Comment by taehoonlee** [comment]
I think that this PR is enough by itself because all the backend and layer tests were passed. As you said @fchollet, I'll try to investigate the discrepancy for each application. Currently,
- TensorFlow differs in `MobileNet`, `ResNet50`
- Theano differs in `InceptionV3`
- OK in `VGG16`, `VGG19`, `DenseNet121`
- Versions: Keras 2.1.3, TensorFlow 1.3.0, Theano 1.0.1, CNTK 2.3.1

The results are the following:
```bash
 $ KERAS_BACKEND=theano python test_resnet50.py
Using Theano backend.
('Predicted:', [(u'n02124075', u'Egyptian_cat', 0.17173238), (u'n02123597', u'Siamese_cat', 0.10258683), (u'n02130308', u'cheetah', 0.0565808)])

 $ KERAS_BACKEND=cntk python test_resnet50.py
Using CNTK backend
Selected GPU[0] Tesla P100-PCIE-16GB as the process wide default device.
('Predicted:', [(u'n02124075', u'Egyptian_cat', 0.17055313), (u'n02123597', u'Siamese_cat', 0.11803201), (u'n03482405', u'hamper', 0.055440076)])

 $ KERAS_BACKEND=tensorflow python test_resnet50.py
Using TensorFlow backend.
('Predicted:', [(u'n02124075', u'Egyptian_cat', 0.116303556), (u'n02123597', u'Siamese_cat', 0.075559795), (u'n02130308', u'cheetah', 0.048775144)])

 $ KERAS_BACKEND=cntk python test_inception3.py
Using CNTK backend
Selected GPU[0] Tesla P100-PCIE-16GB as the process wide default device.
('Predicted:', [(u'n02123045', u'tabby', 0.69501376), (u'n02123159', u'tiger_cat', 0.11184513), (u'n02356798', u'fox_squirrel', 0.069066964)])

 $ KERAS_BACKEND=tensorflow python test_inception3.py
Using TensorFlow backend.
('Predicted:', [(u'n02123045', u'tabby', 0.70286405), (u'n02123159', u'tiger_cat', 0.110841505), (u'n02356798', u'fox_squirrel', 0.067352444)])

 $ KERAS_BACKEND=theano python test_inception3.py
Using Theano backend.
('Predicted:', [(u'n02123045', u'tabby', 0.6191356), (u'n02123159', u'tiger_cat', 0.14174756), (u'n02124075', u'Egyptian_cat', 0.10547265)])

 $ KERAS_BACKEND=cntk python test_vgg16.py
Using CNTK backend
Selected GPU[0] Tesla P100-PCIE-16GB as the process wide default device.
('Predicted:', [(u'n01687978', u'agama', 0.12963562), (u'n01675722', u'banded_gecko', 0.09029942), (u'n02317335', u'starfish', 0.086037084)])

 $ KERAS_BACKEND=tensorflow python test_vgg16.py
Using TensorFlow backend.
('Predicted:', [(u'n01687978', u'agama', 0.12963554), (u'n01675722', u'banded_gecko', 0.09029918), (u'n02317335', u'starfish', 0.08603718)])

 $ KERAS_BACKEND=theano python test_vgg16.py
Using Theano backend.
('Predicted:', [(u'n01687978', u'agama', 0.12963551), (u'n01675722', u'banded_gecko', 0.090299465), (u'n02317335', u'starfish', 0.086037494)])

 $ KERAS_BACKEND=cntk python test_vgg19.py
Using CNTK backend
Selected GPU[0] Tesla P100-PCIE-16GB as the process wide default device.
('Predicted:', [(u'n02137549', u'mongoose', 0.16966635), (u'n03124170', u'cowboy_hat', 0.088505425), (u'n01496331', u'electric_ray', 0.08285297)])

 $ KERAS_BACKEND=tensorflow python test_vgg19.py
Using TensorFlow backend.
('Predicted:', [(u'n02137549', u'mongoose', 0.16966705), (u'n03124170', u'cowboy_hat', 0.088505276), (u'n01496331', u'electric_ray', 0.082852826)])

 $ KERAS_BACKEND=theano python test_vgg19.py
Using Theano backend.
('Predicted:', [(u'n02137549', u'mongoose', 0.16966648), (u'n03124170', u'cowboy_hat', 0.088506155), (u'n01496331', u'electric_ray', 0.082852475)])

 $ KERAS_BACKEND=cntk python test_densenet121.py
Using CNTK backend
Selected GPU[0] Tesla P100-PCIE-16GB as the process wide default device.
('Predicted:', [(u'n02124075', u'Egyptian_cat', 0.30215406), (u'n02123394', u'Persian_cat', 0.08100653), (u'n02123045', u'tabby', 0.04857644)])

 $ KERAS_BACKEND=tensorflow python test_densenet121.py
Using TensorFlow backend.
('Predicted:', [(u'n02124075', u'Egyptian_cat', 0.2955615), (u'n02123394', u'Persian_cat', 0.08364624), (u'n02123045', u'tabby', 0.048363034)])

 $ KERAS_BACKEND=theano python test_densenet121.py
Using Theano backend.
('Predicted:', [(u'n02124075', u'Egyptian_cat', 0.29556265), (u'n02123394', u'Persian_cat', 0.08364609), (u'n02123045', u'tabby', 0.048363138)])
```

**Comment by fchollet** [comment]
These predictions seem all in line with each other. There are small numerical differences between backends (as well as a potential small implementation difference with pooling windows for Theano), which can result with small prediction differences for one specific picture.

The TF MobileNet seems broken though. The predictions are not random, but it looks like we have a serious issue.

**Pull request merged**
