### PR TITLE
Remove hardcoded channels_last in efficientnet_v2 and replace with ba…

### PR DESCRIPTION
**Pull request by Inquisitive-ME**
remove hardcoded data_format in efficientnet_v2 and replace with the data_format from the backend

### CODE REVIEW

**Review by fchollet — COMMENTED** [review]
Thanks for the PR. Is this tested?

**Comment by Inquisitive-ME** [comment]
What would be the best method for testing. What i have done so far is modify the keras that comes with tensorflow 2.13 to validate these minor changes.

I'm not sure how to test in Keras 3.0 it seems that all the tests in keras/applications/applications_test.py will fail with the backend set to channels_first. Is this something worth digging into to fix?

**Comment by fchollet** [comment]
> I'm not sure how to test in Keras 3.0 it seems that all the tests in keras/applications/applications_test.py will fail with the backend set to channels_first. Is this something worth digging into to fix?

Most will pass. Some will fail when the application isn't compatible with channels_first, e.g. ConvNeXt, DenseNet, EfficientNet, MobileNet.

**Comment by Inquisitive-ME** [comment]
I updated keras/applications/applications_test so that it will run all the tests on channels first and skip the architectures that do not support channels first (ConvNeXt, DenseNet, NASNet)
This led to also fix MobilenetV3 for channels first

**Comment by fchollet** [comment]
Looks like CI is failing because the VM can't handle applications tests. Will have to test offline.

**Comment by Inquisitive-ME** [comment]
I was running it locally. But I can take a look and see if I can figure out why it would fail. Adding the extra tests does roughly double the time it would take to complete. Is it possible it is a timeout issue?

**Review by fchollet — APPROVED** [review]
LGTM, thanks!

It is both a timeout and a memory issue. Presumably caused by some of the larger applications (also the fact that the total test size has nearly doubled with this PR).

**Comment by qlzh727** [comment]
Since this is breaking head right now, can we do a rollback for this one?

**Pull request merged**
