### PR TITLE
Fix documentation text being mistakenly rendered as code

### PR DESCRIPTION
**Pull request by guberti**
The `label_mode` argument in the documentation of `image_dataset_from_directory` currently [renders like this on tensorflow.org](https://www.tensorflow.org/api_docs/python/tf/keras/utils/image_dataset_from_directory):
image
This occurs because the documentation renderer expects there to be some text explanation between the name of an argument and a list of possible options (e.g. see the `output_mode` argument in [tf.keras.layers.Hashing](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Hashing)). This PR fixes this glitch by adding one line of explanation, as the renderer wants.

A bit of regex work (`ag "^[ ]*[a-z_]*:\n[ ]*-"`) shows the issue also occurs in `text_dataset.py` and `dataset_utils.py` - I've fixed those too.

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by gbaned** [comment]
@guberti Can you please resolve conflicts? Thanks!

**Comment by fchollet** [comment]
The files have moved to the `utils/` directory.

**Comment by guberti** [comment]
@fchollet Merge conflicts fixed, thanks for taking a look.

**Pull request merged**
