### PR TITLE
 Support constants in StackedRNNCells

### PR DESCRIPTION
**Pull request by myutwo150**
This PR is probably useful for implementing (some variants of) attention RNNs.

1.  Enable the `constants` argument in `StackedRNNCells.call`. The constants will be routed to an underlying cell if it also supports `constants`.
2. Handle the shape of the constants properly in `StackedRNNCells.build` so that an RNN cell with constants can be stacked on top of another cell. Before this PR,
- If the bottom cell does not support `constants`: 
```python
constants = Input((32,))
x = Input((None, 5))
x = RNN([GRUCell(16), RNNCellWithConstants(32)])(x, constants=constants)
```
The `GRUCell` fails to build because `input_shape`, which is now a list `[step_input_shape] + constants_shape`, is passed to `GRUCell.build` directly. We should only pass `step_input_shape` to `GRUCell.build` in this case.

- If the bottom cell also supports `constants`: 
```python
constants = Input((32,))
x = Input((None, 5))
x = RNN([RNNCellWithConstants(16), RNNCellWithConstants(32)])(x, constants=constants)
```
The top cell fails to build because the `input_shape` passed to it is incorrect.

Also modified the test to cover the two cases above.

### CODE REVIEW

**Comment by fchollet** [comment]
Re-running tests

**Comment by fchollet** [comment]
That's a reasonable behavior change. Code LGTM.

**Comment by myutwo150** [comment]
Thanks for reviewing! Seems like the tests are passing now.

**Comment by LeZhengThu** [comment]
Hi, can anyone help explain the argument "constants"? I'm a bit lost about the argument. Thanks.

**Comment by fchollet** [comment]
They're constant tensors passed to the underlying cell at every call.

**Comment by LeZhengThu** [comment]
@fchollet Does these tensors have timesteps?  Are they something like the static features fed in the network?

**Comment by fchollet** [comment]
No, they don't have timesteps. They're passed to each cell call. They have no concept of time, that's why they're called "constants".

**Pull request merged**
