### PR TITLE
Update metrics.py

### PR DESCRIPTION
**Pull request by Yashashree304**
Fixes issue https://github.com/tensorflow/tensorflow/issues/54117

### CODE REVIEW

**Comment by gbaned** [comment]
@Yashashree304  Can you please resolve conflicts? Thanks!

**Comment by Yashashree304** [comment]
@gbaned @fchollet Sorry for late response was stuck up in something. But I am unable to resolve conflicts can you please help me?

**Comment by fchollet** [comment]
Just close this PR, pull a fresh copy of the repo, and create a new PR. The PR is a 2-line change only anyway.

**Comment by Yashashree304** [comment]
Okay Thanks!

**Pull request closed without merging**
