### PR TITLE
[keras/estimator/__init__.py] Standardise docstring usage of "Default to"

### PR DESCRIPTION
**Pull request by SamuelMarks**
This is one of many PRs. Discussion + request to split into multiple PRs @ #17748

### CODE REVIEW

**Review by haifeng-jin — COMMENTED** [review]
I am not familiar with this part. There are 2 questions to be answered.
1. Is 2.0 referring TF 2.0? If so, it is already released and the description can be further changed.
2. The file is wrapped in `# LINT.IfChange`. We may need more changes to pass the test.

@qlzh727 may help answer them.

**Comment by qlzh727** [comment]
> I am not familiar with this part. There are 2 questions to be answered.
> 
> 1. Is 2.0 referring TF 2.0? If so, it is already released and the description can be further changed.
yes, the 2.0 here refers to TF 2.0 release.

> 2. The file is wrapped in `# LINT.IfChange`. We may need more changes to pass the test.
The change here should be fine since it only touch the comment/docstring, and not the code.
> 
> @qlzh727 may help answer them.

**Comment by haifeng-jin** [comment]
Thanks @qlzh727 for the answer!
Then we need to change the description of the saver completely.

@k-w-w may know what would be the most accurate description here.

**Comment by k-w-w** [comment]
Looks like the default was never changed to `checkpoint`, and at this point probably won't be...

Lets remove the 2.0 part. If we want to roll this out we can always add it back.

**Comment by haifeng-jin** [comment]
Pending on author's change.

**Comment by SamuelMarks** [comment]
Sure thing, made the edit

**Comment by SamuelMarks** [comment]
Sure thing, made the edit. Yeah I noticed that issue when I was going through the codebase and had planned a different issue on this point but happy to merge it all into this one PR.

**Review by haifeng-jin — APPROVED** [review]

**Comment by haifeng-jin** [comment]
This is a duplicate for #17957.

**Pull request closed without merging**
