### PR TITLE
Displayed some examples in the docs.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
### Summary

The keras examples are great, but do not benefit from a good visibility. I believe we could add them to the docs. It requires very little work since all the code and docstrings have already been written.

### PR Overview

There is some black magic at work with `compile`. I took the code from https://gist.github.com/rduplain/1249199

We can control which files get displayed with `mkdocs.yml`. For the moment only two are displayed. Here is the result:

- [ ] This PR requires new unit tests [y/n] (make sure tests are included)
- [ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by fchollet** [comment]
Featuring more examples and tutorials on the docs website is a great idea! I'm thinking we might want to editorialize them a bit first to make them more readable (more tutorial-like).

I'll be away at NeurIPS for the week but I'll start reviewing more PRs after I'm back.

**Comment by Dref360** [comment]
Could you fix the conflicts? Other than that LGTM

**Comment by gabrieldemarmiesse** [comment]
Thanks a lot @Dref360 for taking a look at it. Github should really send emails when there are conflicts. Let me fix it right now.

**Comment by gabrieldemarmiesse** [comment]
@Dref360 Should be good to go.

**Pull request merged**
