### PR TITLE
Use TorchEpochIterator for fit and evaluate too.

### PR DESCRIPTION
**Pull request by hertschuh**
`TorchEpochIterator` was only used for `predict`.

### CODE REVIEW

**Review by haifeng-jin — APPROVED** [review]
Thanks for the PR! LGTM

**Review by fchollet — COMMENTED** [review]
Thanks for the PR. Does this lead to performance gains?

**Comment by hertschuh** [comment]
> Thanks for the PR. Does this lead to performance gains?

@haifeng-jin what was the reason to add DataLoader support?

**Comment by hertschuh** [comment]
These change were actually made as part of https://github.com/keras-team/keras/pull/18991

**Pull request closed without merging**
