### PR TITLE
Remove legacy backend tests

### PR DESCRIPTION
**Pull request by taehoonlee**
### Summary

This PR removes legacy backend tests, which are now clearly not required.

### Related Issues

- #9555: the refactoring of `test_conv`,
- #9557: the refactoring of `test_rnn`,
- #9558: the refactoring of `test_depthwise_conv`,
- #9570: the refactoring of `test_separable_conv2d`,
- #9580: the refactoring of `test_pool`.

### PR Overview

- [ ] This PR requires new unit tests [y/n] (make sure tests are included)
- [ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
That explains a lot of thing which I was wondering about.

**Comment by taehoonlee** [comment]
@gabrieldemarmiesse, I had marked the legacy codes with `legacy_test`, but someone changed them as `test_legacy`, which resulted in enabling the tests again. Maybe that's why you are confused.

**Comment by gabrieldemarmiesse** [comment]
I re enabled them. It was because I didn't understand why there was dead code in the codebase.

**Comment by taehoonlee** [comment]
@gabrieldemarmiesse, OK. We must remove them, in order not to make someone confused again.

**Comment by gabrieldemarmiesse** [comment]
I totally agree on that.

**Comment by gabrieldemarmiesse** [comment]
LGTM!

**Pull request merged**
