### PR TITLE
FIX BUG in load_weights_from_hdf5_group_by_name" legacy_h5_format.py

### LINKED ISSUE #20536: BUG in load_weights_from_hdf5_group_by_name
https://github.com/keras-team/keras/blob/5d36ee1f219bb650dd108c35b257c783cd034ffd/keras/src/legacy/saving/legacy_h5_format.py#L521-L525

model.trainable_weights + model.non_trainable_weights references all weights instead of top-level

### PR DESCRIPTION
**Pull request by edwardyehuang**
FIX #20536

### CODE REVIEW

**Comment by edwardyehuang** [comment]
> Looks good, thanks for the fix. Please add a unit test so we avoid breaking this in the future.

It looks like I need to create a mock H5 data structure to test this function. Is there any other option? e.g. split the function?

**Comment by fchollet** [comment]
Can you add a unit test that targets the user-facing case in which the issue appeared?

**Comment by edwardyehuang** [comment]
> Can you add a unit test that targets the user-facing case in which the issue appeared?

Yes, I can

https://github.com/keras-team/keras/blob/0078f24ca94bb10063fe7478a70dbaef701f176a/keras/src/legacy/saving/legacy_h5_format.py#L453-L470

but the issue appeared in the function `load_weights_from_hdf5_group_by_name` that has two parameters: `f(HDF5 pointer)` and `model`.  So I need to mock the HDF5 pointer and model

**Comment by fchollet** [comment]
> A simple way to mock them is to create a mock model, save the weights in temporary files or memory, and then read them. However, I am not sure if this is a good practice for unit testing.

This is fine. Create a very simple model that has the issue, save it to a temporary folder (see unit tests in `keras/src/saving/saving_lib_test.py` for examples), and read it.

**Comment by edwardyehuang** [comment]
> > A simple way to mock them is to create a mock model, save the weights in temporary files or memory, and then read them. However, I am not sure if this is a good practice for unit testing.
> 
> This is fine. Create a very simple model that has the issue, save it to a temporary folder (see unit tests in `keras/src/saving/saving_lib_test.py` for examples), and read it.

I noticed that `keras/src/legacy/saving/legacy_h5_format_test.py` already has a mock subclassed model and corresponding tests `DISABLED_test_subclassed_model_weights`. I just added a top-level weight to this model.


However, the test `DISABLED_test_subclassed_model_weights` is marked as `DISABLED`. Does it need to be removed in this PR? @fchollet

**Comment by fchollet** [comment]
> However, the test DISABLED_test_subclassed_model_weights is marked as DISABLED. Does it need to be removed in this PR?

I just undisabled the tests, check it out.

**Review by fchollet — APPROVED** [review]

**Pull request merged**
