### PR TITLE
Exclude default bazel paths for VsCode

### PR DESCRIPTION
**Pull request by bhack**
This is required for performance and also to avoid to have a confusing ghost duplicated github repositories in the Vscode git tab

### CODE REVIEW

**Review by haifeng-jin — APPROVED** [review]
LGTM

**Review by haifeng-jin — APPROVED** [review]
LGTM

**Comment by bhack** [comment]
[Is the linter ready](https://github.com/keras-team/keras/pull/15006#issuecomment-888540155) now?

**Comment by haifeng-jin** [comment]
The linter is not ready yet : )

**Review by haifeng-jin — CHANGES_REQUESTED** [review]
Please remove the "," at the end of the line.
https://github.com/keras-team/keras/pull/15343/files#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686R12

**Review by haifeng-jin — APPROVED** [review]

**Pull request merged**
