### PR TITLE
Update gradient_descent.py

### PR DESCRIPTION
**Pull request by Mohamad-Jaallouk**
Fix a broken link of a research paper.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @Mohamad-Jaallouk Can you please sign CLA. Thank you!

**Review by fchollet — COMMENTED** [review]
LGTM, thanks!

Please make sure this is also fixed in optimizers/optimizer_experimental.

**Review by fchollet — APPROVED** [review]
LGTM, thanks!

**Comment by gbaned** [comment]
@Mohamad-Jaallouk Can you please fix the Lint errors https://github.com/keras-team/keras/runs/7979620559?check_suite_focus=true Thank you!

**Comment by Mohamad-Jaallouk** [comment]
Hi @gbaned, Not sure where is the problem. When I run lint.sh I get:

> no issues with isort
no issues with flake8
All done! ✨ 🍰 ✨
700 files would be left unchanged.
no issues with black
linting success!

**Comment by fchollet** [comment]
> Not sure where is the problem. When I run lint.sh I get:

The error is

```
keras/engine/training.py:2163:81: E501 line too long (95 > 80 characters)
```
So it does not seem to be related to the contents of the PR.

**Comment by gbaned** [comment]
@Mohamad-Jaallouk Can you please check @fchollet's comments and keep us posted ? Thank you!

**Review by fchollet — APPROVED** [review]

**Comment by Mohamad-Jaallouk** [comment]
> > Not sure where is the problem. When I run lint.sh I get:
> 
> The error is
> 
> ```
> keras/engine/training.py:2163:81: E501 line too long (95 > 80 characters)
> ```
> 
> So it does not seem to be related to the contents of the PR.

I think I can't do more in this PR. Probably close this one and open a new one might help?

**Pull request closed without merging**
