### PR TITLE
Multi head attention, optimising einsum equations for qkv, to leverage data locality issue #20220

### PR DESCRIPTION
**Pull request by tendulkar**
Explained the reason for this change, along with performance benchmarks
https://github.com/keras-team/keras/issues/20220

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR. It's a clever observation. However, after testing Gemma inference after the change, with XLA-compiled JAX, we find consistently 3.5% slower performance.

|         |             | Before the change |       | After the change |       |          |
|---------|-------------|-------------------|-------|------------------|-------|----------|
| Seq len | # sentences | Avg               | Std   | Avg              | Std   | Avg Diff |
|     128 |         100 |             3.639 | 0.948 |            3.767 | 0.979 |    +3.52% |
|     256 |         100 |              5.33 | 2.753 |            5.519 |  2.85 |    +3.55% |
|     512 |         100 |              7.63 |  5.73 |             7.89 |  5.91 |    +3.41% |
|    1024 |         100 |             9.575 | 7.686 |            9.912 | 7.938 |   + 3.52% |

Some thoughts:

- It would be helpful if you shared your benchmarking Colab.
- You seem to use TF eagerly. Eager execution is slow and unoptimized, and we don't target eager performance (eager is always a debugging mode, with all backends, no actual training/inference run should use it, for performance reasons).
- XLA compilation involves many optimizations in memory layout.

You could try a benchmark that uses XLA compilation with both TF and JAX.

**Comment by gbaned** [comment]
Hi @tendulkar Can you please sign CLA? Thank you!

**Comment by tendulkar** [comment]
@fchollet 
I tried it on tensorflow with XLA compiled, I'm getting slower performance as well. Here is the [colab](https://colab.research.google.com/drive/15wecmAsKntlwEQBUn_nUXuOI8VnyIZqC#scrollTo=kEHwRv2a1Dm0). 

Can you help me understand why is this happening ? if XLA optimises the code, either it should optimise both to same performance or "poorly" written code to slower and "better" written code to faster. Why better written code is optimised to slower than poorly written code (Just want to understand it better) ?

**Comment by fchollet** [comment]
Compilers aren't magic, they do a good job but are rarely optimal. This is why, for instance, there are performance differences between the exact same code written in XLA-compiled TF and XLA-compiled JAX, despite both using the same XLA compiler. The differences sometimes favor one and sometimes the other.

In this case both ways of writing the code get optimized, but one happens to benefit more from the optimization. There's no deep meaning to it.

**Pull request closed without merging**
