### PR TITLE
Check all input tensors.

### PR DESCRIPTION
**Pull request by hgaiser**
Presumably this was an error when copy/pasting, causing only the last input tensor to be checked.

### CODE REVIEW

**Comment by fchollet** [comment]
The tests and possibly the Model constructor logic will need to be updated. https://travis-ci.org/keras-team/keras/jobs/392231240

**Comment by fchollet** [comment]
I just fixed it. Thank you for pointing out the issue.

**Comment by hgaiser** [comment]
Thank you for fixing it, I didn't have time to look into it further.

**Comment by Saisuchith** [comment]
thank you for fixing it

**Pull request closed without merging**
