### PR TITLE
Updated Complex dtype input support for layers

### LINKED ISSUE #19860: [Feature request] Complex dtype input support for layers
See the original issue in tensorflow's repo: https://github.com/tensorflow/tensorflow/issues/65306

### Current behavior?

The following code works well for tf2.15 but fails tf2.16.1 with the introduction of keras3,

```
import tensorflow as tf
print(tf.__version__)

class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs

    def build(self, input_shape):
        self.kernel = self.add_weight(shape=[int(input_shape[-1]),
                                         self.num_outputs], )

    def call(self, inputs):
        kernel = tf.cast(self.kernel, tf.complex64)
        return tf.matmul(inputs, kernel)

layer = MyDenseLayer(10)
layer(tf.zeros([10, 5], dtype=tf.complex64))
```

For short, tf2.16.1 with newly introduced keras 3 seems not supporting the input tensor for a layer in complex dtype

### Relevant log output

```shell
[usr/local/lib/python3.10/dist-packages/keras/src/backend/common/variables.py](https://localhost:8080/#) in standardize_dtype(dtype)
    428 
    429     if dtype not in dtypes.ALLOWED_DTYPES:
--> 430         raise ValueError(f"Invalid dtype: {dtype}")
    431     return dtype
    432 

ValueError: Invalid dtype: complex64
```

It would be better that keras3 can support complex valued input for layers as keras did before. Complex valued input is very common in quantum machine learning use cases.

### PR DESCRIPTION
**Pull request by mehtamansi29**
Updated complex dtype for ALLOWED_DTYPES=complex64,complex128 in the documentation. Please have a look at the changes and do the needful. Thank you. Fixes #19860

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR! We'd need to add some test with a custom layer with complex inputs to verify that it works (and make sure we won't break it in the future). Also, current tests seem to be failing.

**Comment by jhoydis** [comment]
Hi,
Is there any progress on this feature? Having layers with complex inputs is a crucial requirement for many areas of application.
Any information on this issue would be appreciated. Thanks!

**Comment by mehtamansi29** [comment]
Hi @jhoydis - 

I am working on adding some test with a custom layer with complex inputs. Will update with successful test once its done. Thanks..!!

**Comment by arnefib** [comment]
Hi, thanks for looking into this - just some comment: I tried applying the proposed fix (add complex64/128 in ALLOWED_DTYPES) to activate complex type support for layers, but noticed this doesn't fix if fully: using slicing operation (I used layers.__getitem__ through [..] syntax, but expect this maps to any other tf.slice/strided_slice) with complex64 type input results in float32 type output instead of expected complex64. Kind regards!

**Comment by fchollet** [comment]
So what shall we do with this PR?

**Comment by mehtamansi29** [comment]
> So what shall we do with this PR?

Hi @fchollet - Sorry for the delay. 
I am working on adding test for complex input. I'll update soon(maybe today or tomorrow), once newly added  test case will get passed. Thanks..!!

**Comment by fchollet** [comment]
Are you doing ok with the test fixes across the different backends? I see that TF is passing at least, that's good!

**Comment by mehtamansi29** [comment]
> Are you doing ok with the test fixes across the different backends? I see that TF is passing at least, that's good!

Hi @fchollet - For Torch backend I am not doing test fixes for complex dtype as torch doesn't support it. And for JAX backend running the failed test in my local same test went passed. But when commit it, that is failing. 
But as TF passing is good and custom layer with complex input case is working fine then  can I leave it different backend(JAX and torch) as it is ?

**Comment by fchollet** [comment]
> For Torch backend I am not doing test fixes for complex dtype as torch doesn't support it.

Then you should explicitly exclude torch from these unit tests via a pytest skip decorator.

> And for JAX backend running the failed test in my local same test went passed. But when commit it, that is failing.

What is the issue here?

**Comment by fchollet** [comment]
Thanks for the update.

> This branch has conflicts that must be resolved

Can you please solve the conflicts?

**Comment by mehtamansi29** [comment]
> Thanks for the update.
> 
> > This branch has conflicts that must be resolved
> 
> Can you please solve the conflicts?

Sure @fchollet - I'll resolve it and update the commit by tomorrow. 
Every test case got passes except torch(even after adding pytest skip decorator in keras/src/backend/common/dtypes_test.py file).

**Review by fchollet — APPROVED** [review]
Thanks, I'll fix the remainder forward.

**Comment by mehtamansi29** [comment]
> Thanks, I'll fix the remainder forward.

Thanks..!!

**Comment by jhoydis** [comment]
Please see #20278 for a related issue that seems to be introduced with this merge.

**Pull request merged**
