### PR TITLE
get_layer function cannot detect submodel's layers by name #9590

### PR DESCRIPTION
**Pull request by tchaton**
I have added a check on the instance of the layer.
If it is a model, I call again get_layer on the sub_model

### CODE REVIEW

**Comment by fchollet** [comment]
This PR seems to have formatting issues, please fix.

**Comment by tchaton** [comment]
What do you mean * sry ?

2018-04-16 20:23 GMT+00:00 thomas chaton <thomas.chaton.ai@gmail.com>:

**Comment by Dref360** [comment]
If you look at the diff, https://github.com/keras-team/keras/pull/9950/files
You do more than fixing the issue. Please keep the PR as clean as possible.

**Comment by fchollet** [comment]
Specifically, it seems you (your editor) replaced groups of spaces with tabs.

**Comment by tchaton** [comment]
Oh I am sorry to make you lose a precious time about such a simple commit.
I will look into it tomorrow and try to make it fine this time. If it
doesn't, I just added two lines of code which could be added on your side.

2018-04-17 21:31 GMT+00:00 François Chollet <notifications@github.com>:

**Pull request closed without merging**
