### PR TITLE
Add JAX and Torch GPU Test setup

### PR DESCRIPTION
**Pull request by sampathweb**
Creates trigger files.  Will update the `build.sh` in separate PR to work for JAX and Torch.

### CODE REVIEW

**Review by qlzh727 — COMMENTED** [review]
Just wondering whether 3 GPU builds will consume too much computation resource (since this is presubmit, which might trigger multiple runs per PR).

Can u check with infra team about the current resource pool size and usages?

**Comment by sampathweb** [comment]
> Just wondering whether 3 GPU builds will consume too much computation resource (since this is presubmit, which might trigger multiple runs per PR).
> 
> Can u check with infra team about the current resource pool size and usages?

Valid concern. Right now the TF GPU test takes ~ 4 mins - https://source.cloud.google.com/results/invocations/9e557e12-d454-479e-97ed-55a5f12a3b2d/targets

**Comment by qlzh727** [comment]
> > Just wondering whether 3 GPU builds will consume too much computation resource (since this is presubmit, which might trigger multiple runs per PR).
> > Can u check with infra team about the current resource pool size and usages?
> 
> Valid concern. Right now the TF GPU test takes ~ 4 mins - https://source.cloud.google.com/results/invocations/9e557e12-d454-479e-97ed-55a5f12a3b2d/targets

I see. How about just merge three backends GPU test together for now. We can split them later if it takes long time to run.

Also please make sure to run all 3 of them even if some of them are failed.

**Comment by sampathweb** [comment]
> > > Just wondering whether 3 GPU builds will consume too much computation resource (since this is presubmit, which might trigger multiple runs per PR).
> > > Can u check with infra team about the current resource pool size and usages?
> > 
> > 
> > Valid concern. Right now the TF GPU test takes ~ 4 mins - https://source.cloud.google.com/results/invocations/9e557e12-d454-479e-97ed-55a5f12a3b2d/targets
> 
> I see. How about just merge three backends GPU test together for now. We can split them later if it takes long time to run.
> 
> Also please make sure to run all 3 of them even if some of them are failed.

Sure.  I can do that.  Just that the output may not be pretty to review.  But I see your point.  I can make that change and reduces the number of machines we are provisioning.

**Review by fchollet — APPROVED** [review]
Thanks -- LGTM

**Comment by sampathweb** [comment]
> Thanks -- LGTM

Should we combine the TF, JAX, Torch GPU tests in one run or have them as separate?  I see Scott's point that it will reduce the number of machines provisioned, but might make reading the errors slightly difficult with a long long.  I can make changes to use one presubmit or keep it as three.

**Comment by fchollet** [comment]
I would advocate for running 3 separate jobs in order to reduce total runtime -- unless it's eating too much quota, in which case a single job might be preferable.

**Comment by sampathweb** [comment]
> I would advocate for running 3 separate jobs in order to reduce total runtime -- unless it's eating too much quota, in which case a single job might be preferable.

Ok.  We can start with 3 separate jobs.  If we run into quota issues, we can consolidate into one.  Does that work @qlzh727 ?

**Comment by qlzh727** [comment]
> > I would advocate for running 3 separate jobs in order to reduce total runtime -- unless it's eating too much quota, in which case a single job might be preferable.
> 
> Ok. We can start with 3 separate jobs. If we run into quota issues, we can consolidate into one. Does that work @qlzh727 ?

Ack, let's try that first.

**Review by qlzh727 — APPROVED** [review]

**Pull request merged**
