### PR TITLE
Bugfix/normalization invert

### PR DESCRIPTION
**Pull request by jerabaul29**
Fix bug #17486 , by:

- making sure the ```invert``` attribute is tracked when saving / loading
- adding extra test for this case.

Notes:

- I am not too familiar with the keras tests setup, so the test I added may need editing
- there are several tests around my new additional test, it is possible that one may want to add extra "invert" tests corresponding to each of these.

### CODE REVIEW

**Review by qlzh727 — CHANGES_REQUESTED** [review]
Thanks for the fix, overall LGTM, please fix the format.

**Comment by qlzh727** [comment]
> Thanks for the fix, overall LGTM, please fix the format.

See https://github.com/keras-team/keras/actions/runs/4044365513/jobs/6958299676

**Comment by qlzh727** [comment]
The format is still broken. Please use the format script in the repo https://github.com/keras-team/keras/blob/master/shell/format.sh

**Comment by jerabaul29** [comment]
FYI: I first tried running this script on the full repository. The ```isort``` command failed:

```
~/Desktop/Git/keras [bugfix/normalization_invert|✔]> isort -sl keras
WARNING: Unable to parse file keras due to [Errno 21] Is a directory: '/home/jrmet/Desktop/Git/keras/keras'
~/Desktop/Git/keras/keras [bugfix/normalization_invert|✔]> isort -sl keras
WARNING: Unable to parse file keras due to [Errno 2] No such file or directory: '/home/jrmet/Desktop/Git/keras/keras/keras'
```

Then the ```black``` command found many hits that "needed" refactor, far outside what I was writing / modifying:

```
~/Desktop/Git/keras [bugfix/normalization_invert|✔]> black --line-length 80 keras
reformatted /home/jrmet/Desktop/Git/keras/keras/applications/mobilenet_v2.py
reformatted /home/jrmet/Desktop/Git/keras/keras/applications/mobilenet_v3.py
reformatted /home/jrmet/Desktop/Git/keras/keras/benchmarks/metrics_memory_benchmark_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/benchmarks/eager_microbenchmarks_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/benchmarks/keras_examples_benchmarks/mnist_conv_custom_training_benchmark_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/benchmarks/layer_benchmarks/layer_benchmarks_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/callbacks_v1.py
reformatted /home/jrmet/Desktop/Git/keras/keras/distribute/custom_training_loop_optimizer_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/distribute/distributed_training_utils.py
reformatted /home/jrmet/Desktop/Git/keras/keras/distribute/dataset_creator_model_fit_test_base.py
reformatted /home/jrmet/Desktop/Git/keras/keras/distribute/custom_training_loop_models_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/distribute/keras_embedding_model_correctness_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/distribute/distribute_coordinator_utils.py
reformatted /home/jrmet/Desktop/Git/keras/keras/distribute/mirrored_variable_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/distribute/saved_model_test_base.py
reformatted /home/jrmet/Desktop/Git/keras/keras/distribute/multi_worker_callback_tf2_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/dtensor/integration_test_utils.py
reformatted /home/jrmet/Desktop/Git/keras/keras/distribute/distributed_training_utils_v1.py
reformatted /home/jrmet/Desktop/Git/keras/keras/distribute/keras_utils_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/distribute/sharded_variable_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/dtensor/utils_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/engine/keras_tensor.py
reformatted /home/jrmet/Desktop/Git/keras/keras/engine/data_adapter.py
reformatted /home/jrmet/Desktop/Git/keras/keras/distribute/distribute_strategy_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/engine/training_arrays_v1.py
reformatted /home/jrmet/Desktop/Git/keras/keras/engine/base_layer.py
reformatted /home/jrmet/Desktop/Git/keras/keras/callbacks_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/engine/base_layer_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/engine/training_generator_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/feature_column/sequence_feature_column_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/feature_column/dense_features_v2_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/engine/training_utils_v1.py
reformatted /home/jrmet/Desktop/Git/keras/keras/feature_column/dense_features_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/integration_test/parameter_server_custom_training_loop_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/engine/functional_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/integration_test/parameter_server_keras_preprocessing_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/integration_test/multi_worker_tutorial_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/integration_test/saved_model_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/engine/training_v1.py
reformatted /home/jrmet/Desktop/Git/keras/keras/layers/convolutional/base_conv.py
reformatted /home/jrmet/Desktop/Git/keras/keras/layers/attention/multi_head_attention.py
reformatted /home/jrmet/Desktop/Git/keras/keras/layers/pooling/max_pooling1d.py
reformatted /home/jrmet/Desktop/Git/keras/keras/layers/preprocessing/discretization_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/layers/preprocessing/text_vectorization.py
reformatted /home/jrmet/Desktop/Git/keras/keras/layers/preprocessing/preprocessing_stage_functional_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/layers/preprocessing/normalization_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/layers/reshaping/cropping2d.py
reformatted /home/jrmet/Desktop/Git/keras/keras/layers/reshaping/cropping3d.py
reformatted /home/jrmet/Desktop/Git/keras/keras/layers/rnn/legacy_cell_wrappers.py
reformatted /home/jrmet/Desktop/Git/keras/keras/layers/rnn/gru_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/layers/rnn/legacy_cells.py
reformatted /home/jrmet/Desktop/Git/keras/keras/engine/training_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/layers/rnn/lstm_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/layers/rnn/base_rnn_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/mixed_precision/autocast_variable.py
reformatted /home/jrmet/Desktop/Git/keras/keras/mixed_precision/layer_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/mixed_precision/mixed_precision_graph_rewrite_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/metrics/base_metric_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/metrics/metrics.py
reformatted /home/jrmet/Desktop/Git/keras/keras/models/cloning_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/optimizers/legacy/nadam_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/mixed_precision/loss_scale_optimizer_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/optimizers/utils.py
reformatted /home/jrmet/Desktop/Git/keras/keras/optimizers/legacy/optimizer_v2.py
reformatted /home/jrmet/Desktop/Git/keras/keras/preprocessing/sequence.py
reformatted /home/jrmet/Desktop/Git/keras/keras/saving/legacy/saved_model/layer_serialization.py
reformatted /home/jrmet/Desktop/Git/keras/keras/optimizers/optimizer_v1.py
reformatted /home/jrmet/Desktop/Git/keras/keras/saving/object_registration_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/saving/legacy/saving_utils.py
reformatted /home/jrmet/Desktop/Git/keras/keras/metrics/metrics_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/saving/legacy/saved_model/save_impl.py
reformatted /home/jrmet/Desktop/Git/keras/keras/saving/saving_lib.py
reformatted /home/jrmet/Desktop/Git/keras/keras/testing_infra/test_combinations.py
reformatted /home/jrmet/Desktop/Git/keras/keras/saving/legacy/saved_model/load.py
reformatted /home/jrmet/Desktop/Git/keras/keras/tests/custom_training_loop_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/saving/legacy/save_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/saving/legacy/saved_model/saved_model_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/tests/model_subclassing_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/utils/generic_utils.py
reformatted /home/jrmet/Desktop/Git/keras/keras/tests/tracking_util_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/utils/dataset_utils_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/utils/object_identity.py
reformatted /home/jrmet/Desktop/Git/keras/keras/utils/losses_utils.py
reformatted /home/jrmet/Desktop/Git/keras/keras/utils/sidecar_evaluator_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/utils/tf_utils_test.py
reformatted /home/jrmet/Desktop/Git/keras/keras/utils/metrics_utils.py

All done! ✨ 🍰 ✨
86 files reformatted, 629 files left unchanged.
```

So I ended up running black on just the files I modified, which is what is committed now.

Not sure how you want modified where, if this is still not what you want, can you apply these changes yourself? Thanks :) .

**Review by qlzh727 — APPROVED** [review]

**Review by qlzh727 — CHANGES_REQUESTED** [review]
Btw, it seems that the unit test is failed for the newly added test. Please fix. Thanks.

**Comment by jerabaul29** [comment]
Sorry, I was confused on how to set ```invert=True``` in the tests. Should be fixed now. I was probably running the test in a wrong way on my end which is why I did not catch it.

A small note: is there a way for me to see the output of the CI/CD before you validate every step? :) I think not seeing the CI/CD output before you allow it to run is making it harder for me to catch this kind of stupid mistakes that the CI/CD would have reported to me at once otherwise :) . (I suppose CI/CD does not run automatically when I push so that you cannot get ddos:ed or something like this?)

**Comment by jerabaul29** [comment]
Any update on this? It is a quite 'impactful' bug (as models using inverse normalisation layer get destroyed with a save and load cycle as of today), would be great to push :) .

**Pull request merged**
