### PR TITLE
Rewrite triu and tril in tensorflow backend

### PR DESCRIPTION
**Pull request by dugujiujian1999**
* Use a new way to handle them.
* Add a new unit test.

Fix: https://github.com/keras-team/keras/issues/19043 and https://github.com/keras-team/keras/issues/19045

### CODE REVIEW

**Comment by dugujiujian1999** [comment]
Maybe we don't need document here?

**Comment by dugujiujian1999** [comment]
WIP, make it faster

**Comment by dugujiujian1999** [comment]
Looks like something tf.linalg.band_part breaks something.

**Review by divyashreepathihalli — APPROVED** [review]

**Review by fchollet — APPROVED** [review]
LGTM, thank you

**Pull request merged**
