### PR TITLE
Added MarkDown formatting support to examples/babi_memnn.py

### PR DESCRIPTION
**Pull request by joosephook**
### Summary
This pull request adds MarkDown formatting to ```examples/babi_memnn.py```.
### Related Issues
https://github.com/keras-team/keras/issues/12219
### PR Overview
- [ ] This PR requires new unit tests [y/n] (make sure tests are included)
- [ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
Could you add a screenshot of the resulting page in the docs? Thanks!

**Comment by joosephook** [comment]
Sure thing!

The result:
babi_memnn1
babi_memnn2

**Comment by gabrieldemarmiesse** [comment]
It would be nice if we could click on the name of the paper and end up in the arxiv page. You can do it like this: `[name_of_the_paper](url_of_the_paper)`

**Comment by joosephook** [comment]
Paper titles now link to the corresponding papers as you said.
It won't past PEP8 as one of the titles is very long.

Result:
babi_memnn1

**Comment by gabrieldemarmiesse** [comment]
> It won't pass PEP8 as one of the titles is very long. 

You can break in the middle of the title name I believe.

**Comment by joosephook** [comment]
You're absolutely right, it worked! I did try breaking before, but now in the middle of the title.
The resulting page didn't change, so I won't upload a screenshot of the result.

**Pull request merged**
